-- +migrate Up

CREATE TYPE fuel_category_t AS ENUM ('GASOLINE','DIESEL');

CREATE TYPE user_role_t AS ENUM (
    'SYSTEM_ADMIN','REFINERY_ADMIN','FACILITY_MANAGER',
    'FACILITY_OPERATOR','DEPOT_STAFF','STATION_MANAGER','DRIVER');

CREATE TYPE role_scope_t AS ENUM (
    'COMPANY','REGION','REFINERY','FACILITY','DEPOT','STATION');

CREATE TYPE vehicle_status_t AS ENUM (
    'AVAILABLE','ASSIGNED','IN_TRANSIT','UNDER_MAINTENANCE','DECOMMISSIONED');

CREATE TYPE measurement_method_t AS ENUM ('WEIGHT_BRIDGE','MANUAL_APPROVED');

CREATE TYPE approval_status_t AS ENUM ('PENDING','APPROVED','REJECTED','ESCALATED');

CREATE TYPE do_status_t AS ENUM (
    'DRAFT','PENDING_APPROVAL','APPROVED','ASSIGNED','IN_PROGRESS',
    'DELIVERED','RECONCILED','CLOSED','DISPUTED','CANCELLED');

CREATE TYPE destination_type_t AS ENUM ('STATION','REFINERY_FACILITY');

CREATE TYPE trip_status_t AS ENUM (
    'CREATED','DRIVER_ACKNOWLEDGED','PRE_TRIP_INSPECTION','LOADING','LOADED',
    'IN_TRANSIT','ARRIVED','UNLOADING','DELIVERED','RECONCILED','CLOSED',
    'DISPUTED','CANCELLED');

CREATE TYPE trip_event_type_t AS ENUM (
    'DRIVER_ACKNOWLEDGED','PRE_TRIP_INSPECTION_STARTED',
    'PRE_TRIP_INSPECTION_COMPLETED','ARRIVED_AT_FACILITY',
    'LOADING_STARTED','COMPARTMENT_FILLED','COMPARTMENT_SEALED',
    'WEIGHT_BRIDGE_TARE_RECORDED','WEIGHT_BRIDGE_GROSS_RECORDED',
    'WEIGHT_BRIDGE_APPROVED','LOADING_COMPLETED','DEPARTED_FACILITY',
    'ROUTE_DEVIATION_DETECTED','ARRIVED_AT_DESTINATION',
    'UNLOADING_STARTED','COMPARTMENT_DELIVERED','SEAL_VERIFIED',
    'SEAL_MISMATCH_FLAGGED','DELIVERY_COMPLETED','VARIANCE_FLAGGED',
    'TRIP_CANCELLED','RETURN_INITIATED');

CREATE TYPE photo_event_t AS ENUM (
    'WEIGHT_BRIDGE_TARE','WEIGHT_BRIDGE_GROSS','COMPARTMENT_SEALED',
    'STATION_TANK_BEFORE','PUMP_METER_READING','STATION_TANK_AFTER',
    'VARIANCE_EVIDENCE');

CREATE TYPE document_type_t AS ENUM ('DELIVERY_ORDER','BILL_OF_LADING','DELIVERY_RECEIPT');

CREATE TYPE seal_status_t AS ENUM ('INTACT','MISMATCHED','BROKEN','MISSING');

CREATE TYPE compartment_delivery_status_t AS ENUM ('PENDING','DELIVERED','DISPUTED');

CREATE TYPE notification_type_t AS ENUM (
    'DO_RAISED','DO_APPROVED','TRIP_ASSIGNED','LOADING_COMPLETE',
    'TRIP_DEPARTED','DELIVERY_COMPLETE','VARIANCE_FLAGGED','SEAL_MISMATCH',
    'ROUTE_DEVIATION_WARN','ROUTE_DEVIATION_ESCALATE',
    'MANUAL_MEASUREMENT_PENDING','MANUAL_MEASUREMENT_ESCALATED',
    'DRIVER_LICENSE_EXPIRING','VEHICLE_KEUR_EXPIRING','RETURN_TRIP_CREATED');
