// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_log (
    user_id, action, entity_type, entity_id,
    before_state, after_state, ip_address, user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, created_at
`

type InsertAuditLogParams struct {
	UserID      pgtype.Int8     `json:"user_id"`
	Action      string          `json:"action"`
	EntityType  string          `json:"entity_type"`
	EntityID    pgtype.Int8     `json:"entity_id"`
	BeforeState json.RawMessage `json:"before_state"`
	AfterState  json.RawMessage `json:"after_state"`
	IpAddress   *netip.Addr     `json:"ip_address"`
	UserAgent   pgtype.Text     `json:"user_agent"`
}

type InsertAuditLogRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// =============================================================================
// SECTION 31 — AUDIT LOG (APPEND-ONLY)
// =============================================================================
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i InsertAuditLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listAuditLogByAction = `-- name: ListAuditLogByAction :many
SELECT
    al.id, al.user_id, al.action, al.entity_type, al.entity_id, al.before_state, al.after_state, al.ip_address, al.user_agent, al.created_at,
    u.username,
    u.full_name
FROM audit_log al
LEFT JOIN users u ON u.id = al.user_id
WHERE al.action = $1
ORDER BY al.created_at DESC
LIMIT $2
`

type ListAuditLogByActionParams struct {
	Action string `json:"action"`
	Limit  int32  `json:"limit"`
}

type ListAuditLogByActionRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	BeforeState json.RawMessage    `json:"before_state"`
	AfterState  json.RawMessage    `json:"after_state"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    pgtype.Text        `json:"username"`
	FullName    pgtype.Text        `json:"full_name"`
}

func (q *Queries) ListAuditLogByAction(ctx context.Context, arg ListAuditLogByActionParams) ([]ListAuditLogByActionRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByAction, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogByActionRow{}
	for rows.Next() {
		var i ListAuditLogByActionRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByEntity = `-- name: ListAuditLogByEntity :many
SELECT
    al.id, al.user_id, al.action, al.entity_type, al.entity_id, al.before_state, al.after_state, al.ip_address, al.user_agent, al.created_at,
    u.username,
    u.full_name
FROM audit_log al
LEFT JOIN users u ON u.id = al.user_id
WHERE al.entity_type = $1
  AND al.entity_id   = $2
ORDER BY al.created_at DESC
LIMIT $3
`

type ListAuditLogByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.Int8 `json:"entity_id"`
	Limit      int32       `json:"limit"`
}

type ListAuditLogByEntityRow struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	BeforeState json.RawMessage    `json:"before_state"`
	AfterState  json.RawMessage    `json:"after_state"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    pgtype.Text        `json:"username"`
	FullName    pgtype.Text        `json:"full_name"`
}

func (q *Queries) ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]ListAuditLogByEntityRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogByEntityRow{}
	for rows.Next() {
		var i ListAuditLogByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT id, user_id, action, entity_type, entity_id, before_state, after_state, ip_address, user_agent, created_at
FROM audit_log
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditLogByUserParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
