// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compartment_seals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSealMismatchesByTrip = `-- name: CountSealMismatchesByTrip :one
SELECT COUNT(*)::INT AS mismatch_count
FROM compartment_seals
WHERE trip_id = $1
  AND verification_status IN ('MISMATCHED', 'BROKEN', 'MISSING')
`

func (q *Queries) CountSealMismatchesByTrip(ctx context.Context, tripID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countSealMismatchesByTrip, tripID)
	var mismatch_count int32
	err := row.Scan(&mismatch_count)
	return mismatch_count, err
}

const getSealByTripAndCompartment = `-- name: GetSealByTripAndCompartment :one

SELECT id, trip_id, compartment_id, seal_number_issued, issued_by, issued_at, seal_number_verified, verified_by, verified_at, verification_status, notes
FROM compartment_seals
WHERE trip_id      = $1
  AND compartment_id = $2
`

type GetSealByTripAndCompartmentParams struct {
	TripID        int64 `json:"trip_id"`
	CompartmentID int64 `json:"compartment_id"`
}

// =============================================================================
// SECTION 25 — COMPARTMENT SEALS
// =============================================================================
func (q *Queries) GetSealByTripAndCompartment(ctx context.Context, arg GetSealByTripAndCompartmentParams) (CompartmentSeal, error) {
	row := q.db.QueryRow(ctx, getSealByTripAndCompartment, arg.TripID, arg.CompartmentID)
	var i CompartmentSeal
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.SealNumberIssued,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SealNumberVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationStatus,
		&i.Notes,
	)
	return i, err
}

const issueSeal = `-- name: IssueSeal :one
INSERT INTO compartment_seals (
    trip_id, compartment_id, seal_number_issued, issued_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, trip_id, compartment_id, seal_number_issued, issued_by, issued_at, seal_number_verified, verified_by, verified_at, verification_status, notes
`

type IssueSealParams struct {
	TripID           int64  `json:"trip_id"`
	CompartmentID    int64  `json:"compartment_id"`
	SealNumberIssued string `json:"seal_number_issued"`
	IssuedBy         int64  `json:"issued_by"`
}

func (q *Queries) IssueSeal(ctx context.Context, arg IssueSealParams) (CompartmentSeal, error) {
	row := q.db.QueryRow(ctx, issueSeal,
		arg.TripID,
		arg.CompartmentID,
		arg.SealNumberIssued,
		arg.IssuedBy,
	)
	var i CompartmentSeal
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.SealNumberIssued,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SealNumberVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationStatus,
		&i.Notes,
	)
	return i, err
}

const listMismatchedSealsByTrip = `-- name: ListMismatchedSealsByTrip :many
SELECT id, trip_id, compartment_id, seal_number_issued, issued_by, issued_at, seal_number_verified, verified_by, verified_at, verification_status, notes
FROM compartment_seals
WHERE trip_id             = $1
  AND verification_status IN ('MISMATCHED', 'BROKEN', 'MISSING')
`

func (q *Queries) ListMismatchedSealsByTrip(ctx context.Context, tripID int64) ([]CompartmentSeal, error) {
	rows, err := q.db.Query(ctx, listMismatchedSealsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompartmentSeal{}
	for rows.Next() {
		var i CompartmentSeal
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.SealNumberIssued,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.SealNumberVerified,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationStatus,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSealsByTrip = `-- name: ListSealsByTrip :many
SELECT
    cs.id, cs.trip_id, cs.compartment_id, cs.seal_number_issued, cs.issued_by, cs.issued_at, cs.seal_number_verified, cs.verified_by, cs.verified_at, cs.verification_status, cs.notes,
    vc.compartment_number,
    ui.full_name AS issued_by_name,
    uv.full_name AS verified_by_name
FROM compartment_seals    cs
JOIN vehicle_compartments vc ON vc.id = cs.compartment_id
JOIN users                ui ON ui.id = cs.issued_by
LEFT JOIN users           uv ON uv.id = cs.verified_by
WHERE cs.trip_id = $1
ORDER BY vc.compartment_number
`

type ListSealsByTripRow struct {
	ID                 int64              `json:"id"`
	TripID             int64              `json:"trip_id"`
	CompartmentID      int64              `json:"compartment_id"`
	SealNumberIssued   string             `json:"seal_number_issued"`
	IssuedBy           int64              `json:"issued_by"`
	IssuedAt           pgtype.Timestamptz `json:"issued_at"`
	SealNumberVerified pgtype.Text        `json:"seal_number_verified"`
	VerifiedBy         pgtype.Int8        `json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	VerificationStatus NullSealStatusT    `json:"verification_status"`
	Notes              pgtype.Text        `json:"notes"`
	CompartmentNumber  int16              `json:"compartment_number"`
	IssuedByName       string             `json:"issued_by_name"`
	VerifiedByName     pgtype.Text        `json:"verified_by_name"`
}

func (q *Queries) ListSealsByTrip(ctx context.Context, tripID int64) ([]ListSealsByTripRow, error) {
	rows, err := q.db.Query(ctx, listSealsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSealsByTripRow{}
	for rows.Next() {
		var i ListSealsByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.SealNumberIssued,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.SealNumberVerified,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.VerificationStatus,
			&i.Notes,
			&i.CompartmentNumber,
			&i.IssuedByName,
			&i.VerifiedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSealBreak = `-- name: RecordSealBreak :one
UPDATE compartment_seals
SET
    verified_by         = $2,
    verified_at         = NOW(),
    verification_status = $3,
    notes               = $4
WHERE id = $1
RETURNING id, trip_id, compartment_id, seal_number_issued, issued_by, issued_at, seal_number_verified, verified_by, verified_at, verification_status, notes
`

type RecordSealBreakParams struct {
	ID                 int64           `json:"id"`
	VerifiedBy         pgtype.Int8     `json:"verified_by"`
	VerificationStatus NullSealStatusT `json:"verification_status"`
	Notes              pgtype.Text     `json:"notes"`
}

func (q *Queries) RecordSealBreak(ctx context.Context, arg RecordSealBreakParams) (CompartmentSeal, error) {
	row := q.db.QueryRow(ctx, recordSealBreak,
		arg.ID,
		arg.VerifiedBy,
		arg.VerificationStatus,
		arg.Notes,
	)
	var i CompartmentSeal
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.SealNumberIssued,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SealNumberVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationStatus,
		&i.Notes,
	)
	return i, err
}

const verifySeal = `-- name: VerifySeal :one
UPDATE compartment_seals
SET
    seal_number_verified = $2,
    verified_by          = $3,
    verified_at          = NOW(),
    verification_status  = CASE
        WHEN seal_number_issued = $2 THEN 'INTACT'::seal_status_t
        ELSE 'MISMATCHED'::seal_status_t
    END,
    notes = $4
WHERE id = $1
RETURNING id, trip_id, compartment_id, seal_number_issued, issued_by, issued_at, seal_number_verified, verified_by, verified_at, verification_status, notes
`

type VerifySealParams struct {
	ID                 int64       `json:"id"`
	SealNumberVerified pgtype.Text `json:"seal_number_verified"`
	VerifiedBy         pgtype.Int8 `json:"verified_by"`
	Notes              pgtype.Text `json:"notes"`
}

func (q *Queries) VerifySeal(ctx context.Context, arg VerifySealParams) (CompartmentSeal, error) {
	row := q.db.QueryRow(ctx, verifySeal,
		arg.ID,
		arg.SealNumberVerified,
		arg.VerifiedBy,
		arg.Notes,
	)
	var i CompartmentSeal
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.SealNumberIssued,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.SealNumberVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.VerificationStatus,
		&i.Notes,
	)
	return i, err
}
