// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveDeliveryOrder = `-- name: ApproveDeliveryOrder :one
UPDATE delivery_orders
SET
    status      = 'APPROVED',
    approved_by = $2,
    approved_at = NOW(),
    updated_at  = NOW()
WHERE id = $1
  AND status = 'PENDING_APPROVAL'
RETURNING id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
`

type ApproveDeliveryOrderParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) ApproveDeliveryOrder(ctx context.Context, arg ApproveDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, approveDeliveryOrder, arg.ID, arg.ApprovedBy)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignVehicleAndDriverToDO = `-- name: AssignVehicleAndDriverToDO :one
UPDATE delivery_orders
SET
    status              = 'ASSIGNED',
    assigned_vehicle_id = $2,
    assigned_driver_id  = $3,
    assigned_at         = NOW(),
    updated_at          = NOW()
WHERE id = $1
  AND status = 'APPROVED'
RETURNING id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
`

type AssignVehicleAndDriverToDOParams struct {
	ID                int64       `json:"id"`
	AssignedVehicleID pgtype.Int8 `json:"assigned_vehicle_id"`
	AssignedDriverID  pgtype.Int8 `json:"assigned_driver_id"`
}

func (q *Queries) AssignVehicleAndDriverToDO(ctx context.Context, arg AssignVehicleAndDriverToDOParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, assignVehicleAndDriverToDO, arg.ID, arg.AssignedVehicleID, arg.AssignedDriverID)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelDeliveryOrder = `-- name: CancelDeliveryOrder :one
UPDATE delivery_orders
SET status = 'CANCELLED', updated_at = NOW()
WHERE id = $1
  AND status NOT IN ('IN_PROGRESS', 'DELIVERED', 'RECONCILED', 'CLOSED')
RETURNING id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
`

func (q *Queries) CancelDeliveryOrder(ctx context.Context, id int64) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, cancelDeliveryOrder, id)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeliveryOrder = `-- name: CreateDeliveryOrder :one
INSERT INTO delivery_orders (
    do_number, origin_facility_id, destination_type,
    destination_station_id, destination_facility_id,
    scheduled_date, notes, raised_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
`

type CreateDeliveryOrderParams struct {
	DoNumber              string           `json:"do_number"`
	OriginFacilityID      int64            `json:"origin_facility_id"`
	DestinationType       DestinationTypeT `json:"destination_type"`
	DestinationStationID  pgtype.Int8      `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8      `json:"destination_facility_id"`
	ScheduledDate         pgtype.Date      `json:"scheduled_date"`
	Notes                 pgtype.Text      `json:"notes"`
	RaisedBy              int64            `json:"raised_by"`
}

func (q *Queries) CreateDeliveryOrder(ctx context.Context, arg CreateDeliveryOrderParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, createDeliveryOrder,
		arg.DoNumber,
		arg.OriginFacilityID,
		arg.DestinationType,
		arg.DestinationStationID,
		arg.DestinationFacilityID,
		arg.ScheduledDate,
		arg.Notes,
		arg.RaisedBy,
	)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryOrder = `-- name: GetDeliveryOrder :one

SELECT id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
FROM delivery_orders
WHERE id = $1
`

// =============================================================================
// SECTION 19 — DELIVERY ORDERS
// =============================================================================
func (q *Queries) GetDeliveryOrder(ctx context.Context, id int64) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrder, id)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryOrderByNumber = `-- name: GetDeliveryOrderByNumber :one
SELECT id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
FROM delivery_orders
WHERE do_number = $1
`

func (q *Queries) GetDeliveryOrderByNumber(ctx context.Context, doNumber string) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrderByNumber, doNumber)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextDOSequenceNumber = `-- name: GetNextDOSequenceNumber :one
SELECT COALESCE(
    MAX(
        CAST(SPLIT_PART(do_number, '-', 4) AS INTEGER)
    ), 0
) AS last_seq
FROM delivery_orders
WHERE do_number LIKE $1
  AND EXTRACT(YEAR FROM created_at) = EXTRACT(YEAR FROM NOW())
`

// Returns the current max sequence for a facility prefix in the current year.
// Application formats this into DO number: DO-{RU}-{YYYY}-{seq:05d}.
func (q *Queries) GetNextDOSequenceNumber(ctx context.Context, doNumber string) (interface{}, error) {
	row := q.db.QueryRow(ctx, getNextDOSequenceNumber, doNumber)
	var last_seq interface{}
	err := row.Scan(&last_seq)
	return last_seq, err
}

const listDOsByDriver = `-- name: ListDOsByDriver :many
SELECT id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
FROM delivery_orders
WHERE assigned_driver_id = $1
ORDER BY scheduled_date DESC
`

func (q *Queries) ListDOsByDriver(ctx context.Context, assignedDriverID pgtype.Int8) ([]DeliveryOrder, error) {
	rows, err := q.db.Query(ctx, listDOsByDriver, assignedDriverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryOrder{}
	for rows.Next() {
		var i DeliveryOrder
		if err := rows.Scan(
			&i.ID,
			&i.DoNumber,
			&i.Status,
			&i.OriginFacilityID,
			&i.DestinationType,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.ScheduledDate,
			&i.Notes,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AssignedVehicleID,
			&i.AssignedDriverID,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDOsByOriginFacility = `-- name: ListDOsByOriginFacility :many
SELECT id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
FROM delivery_orders
WHERE origin_facility_id = $1
ORDER BY scheduled_date DESC, created_at DESC
`

func (q *Queries) ListDOsByOriginFacility(ctx context.Context, originFacilityID int64) ([]DeliveryOrder, error) {
	rows, err := q.db.Query(ctx, listDOsByOriginFacility, originFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryOrder{}
	for rows.Next() {
		var i DeliveryOrder
		if err := rows.Scan(
			&i.ID,
			&i.DoNumber,
			&i.Status,
			&i.OriginFacilityID,
			&i.DestinationType,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.ScheduledDate,
			&i.Notes,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AssignedVehicleID,
			&i.AssignedDriverID,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDOsByStatus = `-- name: ListDOsByStatus :many
SELECT
    dor.id, dor.do_number, dor.status, dor.origin_facility_id, dor.destination_type, dor.destination_station_id, dor.destination_facility_id, dor.scheduled_date, dor.notes, dor.raised_by, dor.approved_by, dor.approved_at, dor.assigned_vehicle_id, dor.assigned_driver_id, dor.assigned_at, dor.created_at, dor.updated_at,
    v.plate_number  AS vehicle_plate,
    u.full_name     AS raised_by_name
FROM delivery_orders dor
LEFT JOIN vehicles   v ON v.id = dor.assigned_vehicle_id
LEFT JOIN users      u ON u.id = dor.raised_by
WHERE dor.status = $1
ORDER BY dor.scheduled_date ASC, dor.created_at ASC
`

type ListDOsByStatusRow struct {
	ID                    int64              `json:"id"`
	DoNumber              string             `json:"do_number"`
	Status                DoStatusT          `json:"status"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	ScheduledDate         pgtype.Date        `json:"scheduled_date"`
	Notes                 pgtype.Text        `json:"notes"`
	RaisedBy              int64              `json:"raised_by"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	AssignedVehicleID     pgtype.Int8        `json:"assigned_vehicle_id"`
	AssignedDriverID      pgtype.Int8        `json:"assigned_driver_id"`
	AssignedAt            pgtype.Timestamptz `json:"assigned_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	VehiclePlate          pgtype.Text        `json:"vehicle_plate"`
	RaisedByName          pgtype.Text        `json:"raised_by_name"`
}

func (q *Queries) ListDOsByStatus(ctx context.Context, status DoStatusT) ([]ListDOsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listDOsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDOsByStatusRow{}
	for rows.Next() {
		var i ListDOsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.DoNumber,
			&i.Status,
			&i.OriginFacilityID,
			&i.DestinationType,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.ScheduledDate,
			&i.Notes,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AssignedVehicleID,
			&i.AssignedDriverID,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VehiclePlate,
			&i.RaisedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDOsByVehicle = `-- name: ListDOsByVehicle :many
SELECT id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
FROM delivery_orders
WHERE assigned_vehicle_id = $1
ORDER BY scheduled_date DESC
`

func (q *Queries) ListDOsByVehicle(ctx context.Context, assignedVehicleID pgtype.Int8) ([]DeliveryOrder, error) {
	rows, err := q.db.Query(ctx, listDOsByVehicle, assignedVehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryOrder{}
	for rows.Next() {
		var i DeliveryOrder
		if err := rows.Scan(
			&i.ID,
			&i.DoNumber,
			&i.Status,
			&i.OriginFacilityID,
			&i.DestinationType,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.ScheduledDate,
			&i.Notes,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AssignedVehicleID,
			&i.AssignedDriverID,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDOsForDispatchQueue = `-- name: ListDOsForDispatchQueue :many
SELECT
    dor.id, dor.do_number, dor.status, dor.origin_facility_id, dor.destination_type, dor.destination_station_id, dor.destination_facility_id, dor.scheduled_date, dor.notes, dor.raised_by, dor.approved_by, dor.approved_at, dor.assigned_vehicle_id, dor.assigned_driver_id, dor.assigned_at, dor.created_at, dor.updated_at,
    gs.name  AS destination_name,
    gs.code  AS destination_code
FROM delivery_orders dor
LEFT JOIN gas_stations gs ON gs.id = dor.destination_station_id
WHERE dor.origin_facility_id = $1
  AND dor.status IN ('APPROVED', 'ASSIGNED')
ORDER BY dor.scheduled_date ASC, dor.created_at ASC
`

type ListDOsForDispatchQueueRow struct {
	ID                    int64              `json:"id"`
	DoNumber              string             `json:"do_number"`
	Status                DoStatusT          `json:"status"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	ScheduledDate         pgtype.Date        `json:"scheduled_date"`
	Notes                 pgtype.Text        `json:"notes"`
	RaisedBy              int64              `json:"raised_by"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	AssignedVehicleID     pgtype.Int8        `json:"assigned_vehicle_id"`
	AssignedDriverID      pgtype.Int8        `json:"assigned_driver_id"`
	AssignedAt            pgtype.Timestamptz `json:"assigned_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DestinationName       pgtype.Text        `json:"destination_name"`
	DestinationCode       pgtype.Text        `json:"destination_code"`
}

// Approved DOs awaiting or having vehicle assignment, scoped to a facility.
func (q *Queries) ListDOsForDispatchQueue(ctx context.Context, originFacilityID int64) ([]ListDOsForDispatchQueueRow, error) {
	rows, err := q.db.Query(ctx, listDOsForDispatchQueue, originFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDOsForDispatchQueueRow{}
	for rows.Next() {
		var i ListDOsForDispatchQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.DoNumber,
			&i.Status,
			&i.OriginFacilityID,
			&i.DestinationType,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.ScheduledDate,
			&i.Notes,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.AssignedVehicleID,
			&i.AssignedDriverID,
			&i.AssignedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationName,
			&i.DestinationCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDOStatus = `-- name: UpdateDOStatus :one
UPDATE delivery_orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, do_number, status, origin_facility_id, destination_type, destination_station_id, destination_facility_id, scheduled_date, notes, raised_by, approved_by, approved_at, assigned_vehicle_id, assigned_driver_id, assigned_at, created_at, updated_at
`

type UpdateDOStatusParams struct {
	ID     int64     `json:"id"`
	Status DoStatusT `json:"status"`
}

func (q *Queries) UpdateDOStatus(ctx context.Context, arg UpdateDOStatusParams) (DeliveryOrder, error) {
	row := q.db.QueryRow(ctx, updateDOStatus, arg.ID, arg.Status)
	var i DeliveryOrder
	err := row.Scan(
		&i.ID,
		&i.DoNumber,
		&i.Status,
		&i.OriginFacilityID,
		&i.DestinationType,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.ScheduledDate,
		&i.Notes,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.AssignedVehicleID,
		&i.AssignedDriverID,
		&i.AssignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
