// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignCompartmentToDOItem = `-- name: AssignCompartmentToDOItem :one
UPDATE delivery_order_items
SET
    compartment_id = $2,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, do_id, fuel_type_code, compartment_id, requested_volume_l, allocated_volume_l, created_at, updated_at
`

type AssignCompartmentToDOItemParams struct {
	ID            int64       `json:"id"`
	CompartmentID pgtype.Int8 `json:"compartment_id"`
}

func (q *Queries) AssignCompartmentToDOItem(ctx context.Context, arg AssignCompartmentToDOItemParams) (DeliveryOrderItem, error) {
	row := q.db.QueryRow(ctx, assignCompartmentToDOItem, arg.ID, arg.CompartmentID)
	var i DeliveryOrderItem
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.FuelTypeCode,
		&i.CompartmentID,
		&i.RequestedVolumeL,
		&i.AllocatedVolumeL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeliveryOrderItem = `-- name: CreateDeliveryOrderItem :one
INSERT INTO delivery_order_items (
    do_id, fuel_type_code, requested_volume_l
) VALUES (
    $1, $2, $3
)
RETURNING id, do_id, fuel_type_code, compartment_id, requested_volume_l, allocated_volume_l, created_at, updated_at
`

type CreateDeliveryOrderItemParams struct {
	DoID             int64          `json:"do_id"`
	FuelTypeCode     string         `json:"fuel_type_code"`
	RequestedVolumeL pgtype.Numeric `json:"requested_volume_l"`
}

func (q *Queries) CreateDeliveryOrderItem(ctx context.Context, arg CreateDeliveryOrderItemParams) (DeliveryOrderItem, error) {
	row := q.db.QueryRow(ctx, createDeliveryOrderItem, arg.DoID, arg.FuelTypeCode, arg.RequestedVolumeL)
	var i DeliveryOrderItem
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.FuelTypeCode,
		&i.CompartmentID,
		&i.RequestedVolumeL,
		&i.AllocatedVolumeL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDOItem = `-- name: DeleteDOItem :exec
DELETE FROM delivery_order_items
WHERE id = $1
`

func (q *Queries) DeleteDOItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDOItem, id)
	return err
}

const getDeliveryOrderItem = `-- name: GetDeliveryOrderItem :one

SELECT id, do_id, fuel_type_code, compartment_id, requested_volume_l, allocated_volume_l, created_at, updated_at
FROM delivery_order_items
WHERE id = $1
`

// =============================================================================
// SECTION 20 — DELIVERY ORDER ITEMS
// =============================================================================
func (q *Queries) GetDeliveryOrderItem(ctx context.Context, id int64) (DeliveryOrderItem, error) {
	row := q.db.QueryRow(ctx, getDeliveryOrderItem, id)
	var i DeliveryOrderItem
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.FuelTypeCode,
		&i.CompartmentID,
		&i.RequestedVolumeL,
		&i.AllocatedVolumeL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDOItemsByDO = `-- name: ListDOItemsByDO :many
SELECT
    doi.id, doi.do_id, doi.fuel_type_code, doi.compartment_id, doi.requested_volume_l, doi.allocated_volume_l, doi.created_at, doi.updated_at,
    ft.name     AS fuel_type_name,
    ft.category AS fuel_category
FROM delivery_order_items doi
JOIN fuel_types ft ON ft.code = doi.fuel_type_code
WHERE doi.do_id = $1
ORDER BY doi.id
`

type ListDOItemsByDORow struct {
	ID               int64              `json:"id"`
	DoID             int64              `json:"do_id"`
	FuelTypeCode     string             `json:"fuel_type_code"`
	CompartmentID    pgtype.Int8        `json:"compartment_id"`
	RequestedVolumeL pgtype.Numeric     `json:"requested_volume_l"`
	AllocatedVolumeL pgtype.Numeric     `json:"allocated_volume_l"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FuelTypeName     string             `json:"fuel_type_name"`
	FuelCategory     FuelCategoryT      `json:"fuel_category"`
}

func (q *Queries) ListDOItemsByDO(ctx context.Context, doID int64) ([]ListDOItemsByDORow, error) {
	rows, err := q.db.Query(ctx, listDOItemsByDO, doID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDOItemsByDORow{}
	for rows.Next() {
		var i ListDOItemsByDORow
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.FuelTypeCode,
			&i.CompartmentID,
			&i.RequestedVolumeL,
			&i.AllocatedVolumeL,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FuelTypeName,
			&i.FuelCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDOItemAllocatedVolume = `-- name: UpdateDOItemAllocatedVolume :one
UPDATE delivery_order_items
SET
    allocated_volume_l = $2,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, do_id, fuel_type_code, compartment_id, requested_volume_l, allocated_volume_l, created_at, updated_at
`

type UpdateDOItemAllocatedVolumeParams struct {
	ID               int64          `json:"id"`
	AllocatedVolumeL pgtype.Numeric `json:"allocated_volume_l"`
}

func (q *Queries) UpdateDOItemAllocatedVolume(ctx context.Context, arg UpdateDOItemAllocatedVolumeParams) (DeliveryOrderItem, error) {
	row := q.db.QueryRow(ctx, updateDOItemAllocatedVolume, arg.ID, arg.AllocatedVolumeL)
	var i DeliveryOrderItem
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.FuelTypeCode,
		&i.CompartmentID,
		&i.RequestedVolumeL,
		&i.AllocatedVolumeL,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
