// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
    user_id, employee_number, sim_b2_number, sim_b2_expiry, home_depot_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, employee_number, sim_b2_number, sim_b2_expiry, home_depot_id, current_shift_start, current_shift_end, is_on_shift, created_at, updated_at
`

type CreateDriverParams struct {
	UserID         int64       `json:"user_id"`
	EmployeeNumber pgtype.Text `json:"employee_number"`
	SimB2Number    string      `json:"sim_b2_number"`
	SimB2Expiry    pgtype.Date `json:"sim_b2_expiry"`
	HomeDepotID    pgtype.Int8 `json:"home_depot_id"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.UserID,
		arg.EmployeeNumber,
		arg.SimB2Number,
		arg.SimB2Expiry,
		arg.HomeDepotID,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeNumber,
		&i.SimB2Number,
		&i.SimB2Expiry,
		&i.HomeDepotID,
		&i.CurrentShiftStart,
		&i.CurrentShiftEnd,
		&i.IsOnShift,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endDriverShift = `-- name: EndDriverShift :exec
UPDATE drivers
SET
    is_on_shift       = FALSE,
    current_shift_end = NOW(),
    updated_at        = NOW()
WHERE id = $1
`

func (q *Queries) EndDriverShift(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, endDriverShift, id)
	return err
}

const getDriver = `-- name: GetDriver :one

SELECT
    d.id, d.user_id, d.employee_number, d.sim_b2_number, d.sim_b2_expiry, d.home_depot_id, d.current_shift_start, d.current_shift_end, d.is_on_shift, d.created_at, d.updated_at,
    u.username,
    u.full_name,
    u.telegram_user_id,
    u.active AS user_active
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.id = $1
`

type GetDriverRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	TelegramUserID    pgtype.Int8        `json:"telegram_user_id"`
	UserActive        bool               `json:"user_active"`
}

// =============================================================================
// SECTION 14 — DRIVERS
// =============================================================================
func (q *Queries) GetDriver(ctx context.Context, id int64) (GetDriverRow, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i GetDriverRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeNumber,
		&i.SimB2Number,
		&i.SimB2Expiry,
		&i.HomeDepotID,
		&i.CurrentShiftStart,
		&i.CurrentShiftEnd,
		&i.IsOnShift,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.UserActive,
	)
	return i, err
}

const getDriverByUserID = `-- name: GetDriverByUserID :one
SELECT
    d.id, d.user_id, d.employee_number, d.sim_b2_number, d.sim_b2_expiry, d.home_depot_id, d.current_shift_start, d.current_shift_end, d.is_on_shift, d.created_at, d.updated_at,
    u.username,
    u.full_name,
    u.telegram_user_id,
    u.active AS user_active
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.user_id = $1
`

type GetDriverByUserIDRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	TelegramUserID    pgtype.Int8        `json:"telegram_user_id"`
	UserActive        bool               `json:"user_active"`
}

func (q *Queries) GetDriverByUserID(ctx context.Context, userID int64) (GetDriverByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getDriverByUserID, userID)
	var i GetDriverByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeNumber,
		&i.SimB2Number,
		&i.SimB2Expiry,
		&i.HomeDepotID,
		&i.CurrentShiftStart,
		&i.CurrentShiftEnd,
		&i.IsOnShift,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.UserActive,
	)
	return i, err
}

const listAvailableDriversForDispatch = `-- name: ListAvailableDriversForDispatch :many
SELECT
    d.id, d.user_id, d.employee_number, d.sim_b2_number, d.sim_b2_expiry, d.home_depot_id, d.current_shift_start, d.current_shift_end, d.is_on_shift, d.created_at, d.updated_at,
    u.full_name,
    u.telegram_user_id
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.is_on_shift  = TRUE
  AND d.sim_b2_expiry > CURRENT_DATE
  AND u.active       = TRUE
  AND NOT EXISTS (
        SELECT 1 FROM trips t
        WHERE t.driver_id = d.id
          AND t.status NOT IN ('CLOSED', 'CANCELLED', 'RECONCILED')
      )
ORDER BY u.full_name
`

type ListAvailableDriversForDispatchRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FullName          string             `json:"full_name"`
	TelegramUserID    pgtype.Int8        `json:"telegram_user_id"`
}

// Available = on shift, valid SIM B2, no active trip.
func (q *Queries) ListAvailableDriversForDispatch(ctx context.Context) ([]ListAvailableDriversForDispatchRow, error) {
	rows, err := q.db.Query(ctx, listAvailableDriversForDispatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAvailableDriversForDispatchRow{}
	for rows.Next() {
		var i ListAvailableDriversForDispatchRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmployeeNumber,
			&i.SimB2Number,
			&i.SimB2Expiry,
			&i.HomeDepotID,
			&i.CurrentShiftStart,
			&i.CurrentShiftEnd,
			&i.IsOnShift,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.TelegramUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversByDepot = `-- name: ListDriversByDepot :many
SELECT
    d.id, d.user_id, d.employee_number, d.sim_b2_number, d.sim_b2_expiry, d.home_depot_id, d.current_shift_start, d.current_shift_end, d.is_on_shift, d.created_at, d.updated_at,
    u.full_name,
    u.telegram_user_id,
    u.active AS user_active
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.home_depot_id = $1
  AND u.active = TRUE
ORDER BY u.full_name
`

type ListDriversByDepotRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FullName          string             `json:"full_name"`
	TelegramUserID    pgtype.Int8        `json:"telegram_user_id"`
	UserActive        bool               `json:"user_active"`
}

func (q *Queries) ListDriversByDepot(ctx context.Context, homeDepotID pgtype.Int8) ([]ListDriversByDepotRow, error) {
	rows, err := q.db.Query(ctx, listDriversByDepot, homeDepotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversByDepotRow{}
	for rows.Next() {
		var i ListDriversByDepotRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmployeeNumber,
			&i.SimB2Number,
			&i.SimB2Expiry,
			&i.HomeDepotID,
			&i.CurrentShiftStart,
			&i.CurrentShiftEnd,
			&i.IsOnShift,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.TelegramUserID,
			&i.UserActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversWithExpiringLicense = `-- name: ListDriversWithExpiringLicense :many
SELECT
    d.id, d.user_id, d.employee_number, d.sim_b2_number, d.sim_b2_expiry, d.home_depot_id, d.current_shift_start, d.current_shift_end, d.is_on_shift, d.created_at, d.updated_at,
    u.full_name,
    u.telegram_user_id
FROM drivers d
JOIN users u ON u.id = d.user_id
WHERE d.sim_b2_expiry BETWEEN CURRENT_DATE AND (CURRENT_DATE + INTERVAL '30 days')
  AND u.active = TRUE
ORDER BY d.sim_b2_expiry ASC
`

type ListDriversWithExpiringLicenseRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FullName          string             `json:"full_name"`
	TelegramUserID    pgtype.Int8        `json:"telegram_user_id"`
}

// 30-day advance warning window.
func (q *Queries) ListDriversWithExpiringLicense(ctx context.Context) ([]ListDriversWithExpiringLicenseRow, error) {
	rows, err := q.db.Query(ctx, listDriversWithExpiringLicense)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversWithExpiringLicenseRow{}
	for rows.Next() {
		var i ListDriversWithExpiringLicenseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmployeeNumber,
			&i.SimB2Number,
			&i.SimB2Expiry,
			&i.HomeDepotID,
			&i.CurrentShiftStart,
			&i.CurrentShiftEnd,
			&i.IsOnShift,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.TelegramUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startDriverShift = `-- name: StartDriverShift :exec
UPDATE drivers
SET
    is_on_shift         = TRUE,
    current_shift_start = NOW(),
    current_shift_end   = NULL,
    updated_at          = NOW()
WHERE id = $1
`

func (q *Queries) StartDriverShift(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, startDriverShift, id)
	return err
}

const updateDriverHomeDepot = `-- name: UpdateDriverHomeDepot :exec
UPDATE drivers
SET home_depot_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateDriverHomeDepotParams struct {
	ID          int64       `json:"id"`
	HomeDepotID pgtype.Int8 `json:"home_depot_id"`
}

func (q *Queries) UpdateDriverHomeDepot(ctx context.Context, arg UpdateDriverHomeDepotParams) error {
	_, err := q.db.Exec(ctx, updateDriverHomeDepot, arg.ID, arg.HomeDepotID)
	return err
}

const updateDriverLicense = `-- name: UpdateDriverLicense :one
UPDATE drivers
SET
    sim_b2_number = $2,
    sim_b2_expiry = $3,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, user_id, employee_number, sim_b2_number, sim_b2_expiry, home_depot_id, current_shift_start, current_shift_end, is_on_shift, created_at, updated_at
`

type UpdateDriverLicenseParams struct {
	ID          int64       `json:"id"`
	SimB2Number string      `json:"sim_b2_number"`
	SimB2Expiry pgtype.Date `json:"sim_b2_expiry"`
}

func (q *Queries) UpdateDriverLicense(ctx context.Context, arg UpdateDriverLicenseParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriverLicense, arg.ID, arg.SimB2Number, arg.SimB2Expiry)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmployeeNumber,
		&i.SimB2Number,
		&i.SimB2Expiry,
		&i.HomeDepotID,
		&i.CurrentShiftStart,
		&i.CurrentShiftEnd,
		&i.IsOnShift,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
