// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facility_loading_bays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoadingBay = `-- name: CreateLoadingBay :one
INSERT INTO facility_loading_bays (
    facility_id, bay_code, qr_payload, fuel_type_code
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, facility_id, bay_code, qr_payload, fuel_type_code, active, created_at
`

type CreateLoadingBayParams struct {
	FacilityID   int64       `json:"facility_id"`
	BayCode      string      `json:"bay_code"`
	QrPayload    string      `json:"qr_payload"`
	FuelTypeCode pgtype.Text `json:"fuel_type_code"`
}

func (q *Queries) CreateLoadingBay(ctx context.Context, arg CreateLoadingBayParams) (FacilityLoadingBay, error) {
	row := q.db.QueryRow(ctx, createLoadingBay,
		arg.FacilityID,
		arg.BayCode,
		arg.QrPayload,
		arg.FuelTypeCode,
	)
	var i FacilityLoadingBay
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.BayCode,
		&i.QrPayload,
		&i.FuelTypeCode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateLoadingBay = `-- name: DeactivateLoadingBay :exec
UPDATE facility_loading_bays
SET active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateLoadingBay(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateLoadingBay, id)
	return err
}

const getLoadingBay = `-- name: GetLoadingBay :one

SELECT id, facility_id, bay_code, qr_payload, fuel_type_code, active, created_at
FROM facility_loading_bays
WHERE id = $1
`

// =============================================================================
// SECTION 7 — FACILITY LOADING BAYS
// =============================================================================
func (q *Queries) GetLoadingBay(ctx context.Context, id int64) (FacilityLoadingBay, error) {
	row := q.db.QueryRow(ctx, getLoadingBay, id)
	var i FacilityLoadingBay
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.BayCode,
		&i.QrPayload,
		&i.FuelTypeCode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getLoadingBayByQRPayload = `-- name: GetLoadingBayByQRPayload :one
SELECT flb.id, flb.facility_id, flb.bay_code, flb.qr_payload, flb.fuel_type_code, flb.active, flb.created_at, rf.id AS refinery_id
FROM facility_loading_bays flb
JOIN refinery_facilities rf ON rf.id = flb.facility_id
WHERE flb.qr_payload = $1
  AND flb.active = TRUE
`

type GetLoadingBayByQRPayloadRow struct {
	ID           int64              `json:"id"`
	FacilityID   int64              `json:"facility_id"`
	BayCode      string             `json:"bay_code"`
	QrPayload    string             `json:"qr_payload"`
	FuelTypeCode pgtype.Text        `json:"fuel_type_code"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RefineryID   int64              `json:"refinery_id"`
}

func (q *Queries) GetLoadingBayByQRPayload(ctx context.Context, qrPayload string) (GetLoadingBayByQRPayloadRow, error) {
	row := q.db.QueryRow(ctx, getLoadingBayByQRPayload, qrPayload)
	var i GetLoadingBayByQRPayloadRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.BayCode,
		&i.QrPayload,
		&i.FuelTypeCode,
		&i.Active,
		&i.CreatedAt,
		&i.RefineryID,
	)
	return i, err
}

const listLoadingBaysByFacility = `-- name: ListLoadingBaysByFacility :many
SELECT id, facility_id, bay_code, qr_payload, fuel_type_code, active, created_at
FROM facility_loading_bays
WHERE facility_id = $1
  AND active = TRUE
ORDER BY bay_code
`

func (q *Queries) ListLoadingBaysByFacility(ctx context.Context, facilityID int64) ([]FacilityLoadingBay, error) {
	rows, err := q.db.Query(ctx, listLoadingBaysByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacilityLoadingBay{}
	for rows.Next() {
		var i FacilityLoadingBay
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.BayCode,
			&i.QrPayload,
			&i.FuelTypeCode,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoadingBayFuelType = `-- name: UpdateLoadingBayFuelType :one
UPDATE facility_loading_bays
SET fuel_type_code = $2
WHERE id = $1
RETURNING id, facility_id, bay_code, qr_payload, fuel_type_code, active, created_at
`

type UpdateLoadingBayFuelTypeParams struct {
	ID           int64       `json:"id"`
	FuelTypeCode pgtype.Text `json:"fuel_type_code"`
}

func (q *Queries) UpdateLoadingBayFuelType(ctx context.Context, arg UpdateLoadingBayFuelTypeParams) (FacilityLoadingBay, error) {
	row := q.db.QueryRow(ctx, updateLoadingBayFuelType, arg.ID, arg.FuelTypeCode)
	var i FacilityLoadingBay
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.BayCode,
		&i.QrPayload,
		&i.FuelTypeCode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const validateLoadingBayQR = `-- name: ValidateLoadingBayQR :one
SELECT flb.id, flb.facility_id, flb.bay_code, flb.fuel_type_code
FROM facility_loading_bays flb
WHERE flb.qr_payload = $1
  AND flb.facility_id = $2
  AND flb.active = TRUE
`

type ValidateLoadingBayQRParams struct {
	QrPayload  string `json:"qr_payload"`
	FacilityID int64  `json:"facility_id"`
}

type ValidateLoadingBayQRRow struct {
	ID           int64       `json:"id"`
	FacilityID   int64       `json:"facility_id"`
	BayCode      string      `json:"bay_code"`
	FuelTypeCode pgtype.Text `json:"fuel_type_code"`
}

// Validates QR payload belongs to the expected facility and is active.
func (q *Queries) ValidateLoadingBayQR(ctx context.Context, arg ValidateLoadingBayQRParams) (ValidateLoadingBayQRRow, error) {
	row := q.db.QueryRow(ctx, validateLoadingBayQR, arg.QrPayload, arg.FacilityID)
	var i ValidateLoadingBayQRRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.BayCode,
		&i.FuelTypeCode,
	)
	return i, err
}
