// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facility_storage_tanks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageTank = `-- name: CreateStorageTank :one
INSERT INTO facility_storage_tanks (
    facility_id, tank_code, fuel_type_code,
    capacity_l, current_volume_l, min_operational_l
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type CreateStorageTankParams struct {
	FacilityID      int64          `json:"facility_id"`
	TankCode        string         `json:"tank_code"`
	FuelTypeCode    string         `json:"fuel_type_code"`
	CapacityL       pgtype.Numeric `json:"capacity_l"`
	CurrentVolumeL  pgtype.Numeric `json:"current_volume_l"`
	MinOperationalL pgtype.Numeric `json:"min_operational_l"`
}

func (q *Queries) CreateStorageTank(ctx context.Context, arg CreateStorageTankParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, createStorageTank,
		arg.FacilityID,
		arg.TankCode,
		arg.FuelTypeCode,
		arg.CapacityL,
		arg.CurrentVolumeL,
		arg.MinOperationalL,
	)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const creditStorageTankVolume = `-- name: CreditStorageTankVolume :one
UPDATE facility_storage_tanks
SET
    current_volume_l = current_volume_l + $2,
    last_updated_at  = NOW()
WHERE id = $1
  AND active = TRUE
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type CreditStorageTankVolumeParams struct {
	ID             int64          `json:"id"`
	CurrentVolumeL pgtype.Numeric `json:"current_volume_l"`
}

// Credit volume on return-to-facility trip delivery.
func (q *Queries) CreditStorageTankVolume(ctx context.Context, arg CreditStorageTankVolumeParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, creditStorageTankVolume, arg.ID, arg.CurrentVolumeL)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deductStorageTankVolume = `-- name: DeductStorageTankVolume :one
UPDATE facility_storage_tanks
SET
    current_volume_l  = current_volume_l - $2,
    reserved_volume_l = GREATEST(0, reserved_volume_l - $2),
    last_updated_at   = NOW()
WHERE id = $1
  AND active = TRUE
  AND current_volume_l >= $2
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type DeductStorageTankVolumeParams struct {
	ID             int64          `json:"id"`
	CurrentVolumeL pgtype.Numeric `json:"current_volume_l"`
}

// Deduct from current volume at loading completion (simultaneously clears reservation).
func (q *Queries) DeductStorageTankVolume(ctx context.Context, arg DeductStorageTankVolumeParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, deductStorageTankVolume, arg.ID, arg.CurrentVolumeL)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageTank = `-- name: GetStorageTank :one

SELECT id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
FROM facility_storage_tanks
WHERE id = $1
`

// =============================================================================
// SECTION 8 — FACILITY STORAGE TANKS
// =============================================================================
func (q *Queries) GetStorageTank(ctx context.Context, id int64) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, getStorageTank, id)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageTankAvailableVolume = `-- name: GetStorageTankAvailableVolume :one
SELECT
    id,
    facility_id,
    fuel_type_code,
    capacity_l,
    current_volume_l,
    reserved_volume_l,
    (current_volume_l - reserved_volume_l) AS available_volume_l
FROM facility_storage_tanks
WHERE id = $1
  AND active = TRUE
`

type GetStorageTankAvailableVolumeRow struct {
	ID               int64          `json:"id"`
	FacilityID       int64          `json:"facility_id"`
	FuelTypeCode     string         `json:"fuel_type_code"`
	CapacityL        pgtype.Numeric `json:"capacity_l"`
	CurrentVolumeL   pgtype.Numeric `json:"current_volume_l"`
	ReservedVolumeL  pgtype.Numeric `json:"reserved_volume_l"`
	AvailableVolumeL int32          `json:"available_volume_l"`
}

func (q *Queries) GetStorageTankAvailableVolume(ctx context.Context, id int64) (GetStorageTankAvailableVolumeRow, error) {
	row := q.db.QueryRow(ctx, getStorageTankAvailableVolume, id)
	var i GetStorageTankAvailableVolumeRow
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.AvailableVolumeL,
	)
	return i, err
}

const getStorageTankByFacilityAndFuel = `-- name: GetStorageTankByFacilityAndFuel :one
SELECT id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
FROM facility_storage_tanks
WHERE facility_id = $1
  AND fuel_type_code = $2
  AND active = TRUE
`

type GetStorageTankByFacilityAndFuelParams struct {
	FacilityID   int64  `json:"facility_id"`
	FuelTypeCode string `json:"fuel_type_code"`
}

func (q *Queries) GetStorageTankByFacilityAndFuel(ctx context.Context, arg GetStorageTankByFacilityAndFuelParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, getStorageTankByFacilityAndFuel, arg.FacilityID, arg.FuelTypeCode)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listStorageTanksByFacility = `-- name: ListStorageTanksByFacility :many
SELECT id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
FROM facility_storage_tanks
WHERE facility_id = $1
  AND active = TRUE
ORDER BY fuel_type_code
`

func (q *Queries) ListStorageTanksByFacility(ctx context.Context, facilityID int64) ([]FacilityStorageTank, error) {
	rows, err := q.db.Query(ctx, listStorageTanksByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FacilityStorageTank{}
	for rows.Next() {
		var i FacilityStorageTank
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.TankCode,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.CurrentVolumeL,
			&i.ReservedVolumeL,
			&i.MinOperationalL,
			&i.Active,
			&i.LastUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseStorageTankReservation = `-- name: ReleaseStorageTankReservation :one
UPDATE facility_storage_tanks
SET
    reserved_volume_l = GREATEST(0, reserved_volume_l - $2),
    last_updated_at   = NOW()
WHERE id = $1
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type ReleaseStorageTankReservationParams struct {
	ID              int64          `json:"id"`
	ReservedVolumeL pgtype.Numeric `json:"reserved_volume_l"`
}

// Release reservation (on DO cancellation or manual override).
func (q *Queries) ReleaseStorageTankReservation(ctx context.Context, arg ReleaseStorageTankReservationParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, releaseStorageTankReservation, arg.ID, arg.ReservedVolumeL)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const reserveStorageTankVolume = `-- name: ReserveStorageTankVolume :one
UPDATE facility_storage_tanks
SET
    reserved_volume_l = reserved_volume_l + $2,
    last_updated_at   = NOW()
WHERE id = $1
  AND active = TRUE
  AND (current_volume_l - reserved_volume_l) >= $2
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type ReserveStorageTankVolumeParams struct {
	ID              int64          `json:"id"`
	ReservedVolumeL pgtype.Numeric `json:"reserved_volume_l"`
}

// Atomically reserve volume at DO approval. Fails if insufficient available.
func (q *Queries) ReserveStorageTankVolume(ctx context.Context, arg ReserveStorageTankVolumeParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, reserveStorageTankVolume, arg.ID, arg.ReservedVolumeL)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStorageTankVolume = `-- name: UpdateStorageTankVolume :one
UPDATE facility_storage_tanks
SET
    current_volume_l = $2,
    last_updated_at  = NOW()
WHERE id = $1
RETURNING id, facility_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reserved_volume_l, min_operational_l, active, last_updated_at, created_at
`

type UpdateStorageTankVolumeParams struct {
	ID             int64          `json:"id"`
	CurrentVolumeL pgtype.Numeric `json:"current_volume_l"`
}

// Manual correction by SYSTEM_ADMIN (audited separately via audit_log).
func (q *Queries) UpdateStorageTankVolume(ctx context.Context, arg UpdateStorageTankVolumeParams) (FacilityStorageTank, error) {
	row := q.db.QueryRow(ctx, updateStorageTankVolume, arg.ID, arg.CurrentVolumeL)
	var i FacilityStorageTank
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReservedVolumeL,
		&i.MinOperationalL,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
