// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fuel_types.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFuelType = `-- name: CreateFuelType :one
INSERT INTO fuel_types (
    code, name, category, ron_cn,
    density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
`

type CreateFuelTypeParams struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	Category             FuelCategoryT  `json:"category"`
	RonCn                pgtype.Int2    `json:"ron_cn"`
	DensityKgPerLAt15c   pgtype.Numeric `json:"density_kg_per_l_at_15c"`
	EvaporationFactorPct pgtype.Numeric `json:"evaporation_factor_pct"`
	IsSubsidized         bool           `json:"is_subsidized"`
}

func (q *Queries) CreateFuelType(ctx context.Context, arg CreateFuelTypeParams) (FuelType, error) {
	row := q.db.QueryRow(ctx, createFuelType,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.RonCn,
		arg.DensityKgPerLAt15c,
		arg.EvaporationFactorPct,
		arg.IsSubsidized,
	)
	var i FuelType
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Category,
		&i.RonCn,
		&i.DensityKgPerLAt15c,
		&i.EvaporationFactorPct,
		&i.IsSubsidized,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateFuelType = `-- name: DeactivateFuelType :exec
UPDATE fuel_types
SET active = FALSE, updated_at = NOW()
WHERE code = $1
`

func (q *Queries) DeactivateFuelType(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deactivateFuelType, code)
	return err
}

const getFuelType = `-- name: GetFuelType :one

SELECT code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
FROM fuel_types
WHERE code = $1
`

// =============================================================================
// SECTION 2 — FUEL TYPES
// =============================================================================
func (q *Queries) GetFuelType(ctx context.Context, code string) (FuelType, error) {
	row := q.db.QueryRow(ctx, getFuelType, code)
	var i FuelType
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Category,
		&i.RonCn,
		&i.DensityKgPerLAt15c,
		&i.EvaporationFactorPct,
		&i.IsSubsidized,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveFuelTypes = `-- name: ListActiveFuelTypes :many
SELECT code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
FROM fuel_types
WHERE active = TRUE
ORDER BY category, ron_cn
`

func (q *Queries) ListActiveFuelTypes(ctx context.Context) ([]FuelType, error) {
	rows, err := q.db.Query(ctx, listActiveFuelTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelType{}
	for rows.Next() {
		var i FuelType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Category,
			&i.RonCn,
			&i.DensityKgPerLAt15c,
			&i.EvaporationFactorPct,
			&i.IsSubsidized,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelTypes = `-- name: ListFuelTypes :many
SELECT code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
FROM fuel_types
ORDER BY category, ron_cn
`

func (q *Queries) ListFuelTypes(ctx context.Context) ([]FuelType, error) {
	rows, err := q.db.Query(ctx, listFuelTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelType{}
	for rows.Next() {
		var i FuelType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Category,
			&i.RonCn,
			&i.DensityKgPerLAt15c,
			&i.EvaporationFactorPct,
			&i.IsSubsidized,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFuelTypesByCategory = `-- name: ListFuelTypesByCategory :many
SELECT code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
FROM fuel_types
WHERE category = $1
  AND active = TRUE
ORDER BY ron_cn
`

func (q *Queries) ListFuelTypesByCategory(ctx context.Context, category FuelCategoryT) ([]FuelType, error) {
	rows, err := q.db.Query(ctx, listFuelTypesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FuelType{}
	for rows.Next() {
		var i FuelType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Category,
			&i.RonCn,
			&i.DensityKgPerLAt15c,
			&i.EvaporationFactorPct,
			&i.IsSubsidized,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFuelType = `-- name: UpdateFuelType :one
UPDATE fuel_types
SET
    name                    = $2,
    density_kg_per_l_at_15c = $3,
    evaporation_factor_pct  = $4,
    is_subsidized           = $5,
    updated_at              = NOW()
WHERE code = $1
RETURNING code, name, category, ron_cn, density_kg_per_l_at_15c, evaporation_factor_pct, is_subsidized, active, created_at, updated_at
`

type UpdateFuelTypeParams struct {
	Code                 string         `json:"code"`
	Name                 string         `json:"name"`
	DensityKgPerLAt15c   pgtype.Numeric `json:"density_kg_per_l_at_15c"`
	EvaporationFactorPct pgtype.Numeric `json:"evaporation_factor_pct"`
	IsSubsidized         bool           `json:"is_subsidized"`
}

func (q *Queries) UpdateFuelType(ctx context.Context, arg UpdateFuelTypeParams) (FuelType, error) {
	row := q.db.QueryRow(ctx, updateFuelType,
		arg.Code,
		arg.Name,
		arg.DensityKgPerLAt15c,
		arg.EvaporationFactorPct,
		arg.IsSubsidized,
	)
	var i FuelType
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Category,
		&i.RonCn,
		&i.DensityKgPerLAt15c,
		&i.EvaporationFactorPct,
		&i.IsSubsidized,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
