// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gas_stations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStation = `-- name: CreateStation :one
INSERT INTO gas_stations (
    code, name, spbu_license_number, region_code, primary_facility_id,
    location, address, operating_hours_start, operating_hours_end,
    contact_name, contact_phone
) VALUES (
    $1, $2, $3, $4, $5,
    ST_SetSRID(ST_MakePoint($6, $7), 4326),
    $8, $9, $10, $11, $12
)
RETURNING id, code, name, spbu_license_number, region_code, primary_facility_id, location, address, operating_hours_start, operating_hours_end, contact_name, contact_phone, active, created_at, updated_at
`

type CreateStationParams struct {
	Code                string      `json:"code"`
	Name                string      `json:"name"`
	SpbuLicenseNumber   string      `json:"spbu_license_number"`
	RegionCode          string      `json:"region_code"`
	PrimaryFacilityID   int64       `json:"primary_facility_id"`
	StMakepoint         interface{} `json:"st_makepoint"`
	StMakepoint_2       interface{} `json:"st_makepoint_2"`
	Address             pgtype.Text `json:"address"`
	OperatingHoursStart pgtype.Time `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time `json:"operating_hours_end"`
	ContactName         pgtype.Text `json:"contact_name"`
	ContactPhone        pgtype.Text `json:"contact_phone"`
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (GasStation, error) {
	row := q.db.QueryRow(ctx, createStation,
		arg.Code,
		arg.Name,
		arg.SpbuLicenseNumber,
		arg.RegionCode,
		arg.PrimaryFacilityID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.Address,
		arg.OperatingHoursStart,
		arg.OperatingHoursEnd,
		arg.ContactName,
		arg.ContactPhone,
	)
	var i GasStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpbuLicenseNumber,
		&i.RegionCode,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.Address,
		&i.OperatingHoursStart,
		&i.OperatingHoursEnd,
		&i.ContactName,
		&i.ContactPhone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateStation = `-- name: DeactivateStation :exec
UPDATE gas_stations
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateStation, id)
	return err
}

const getStation = `-- name: GetStation :one

SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.id = $1
`

type GetStationRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

// =============================================================================
// SECTION 15 — GAS STATIONS
// =============================================================================
func (q *Queries) GetStation(ctx context.Context, id int64) (GetStationRow, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i GetStationRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpbuLicenseNumber,
		&i.RegionCode,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.Address,
		&i.OperatingHoursStart,
		&i.OperatingHoursEnd,
		&i.ContactName,
		&i.ContactPhone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getStationByCode = `-- name: GetStationByCode :one
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.code = $1
`

type GetStationByCodeRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) GetStationByCode(ctx context.Context, code string) (GetStationByCodeRow, error) {
	row := q.db.QueryRow(ctx, getStationByCode, code)
	var i GetStationByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpbuLicenseNumber,
		&i.RegionCode,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.Address,
		&i.OperatingHoursStart,
		&i.OperatingHoursEnd,
		&i.ContactName,
		&i.ContactPhone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const listAllActiveStations = `-- name: ListAllActiveStations :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.active = TRUE
ORDER BY gs.region_code, gs.name
`

type ListAllActiveStationsRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) ListAllActiveStations(ctx context.Context) ([]ListAllActiveStationsRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveStations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveStationsRow{}
	for rows.Next() {
		var i ListAllActiveStationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveStationsByRefineryScope = `-- name: ListAllActiveStationsByRefineryScope :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
JOIN refinery_facilities rf ON rf.id = gs.primary_facility_id
WHERE gs.active = TRUE
  AND rf.refinery_id = $1
ORDER BY gs.region_code, gs.name
`

type ListAllActiveStationsByRefineryScopeRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) ListAllActiveStationsByRefineryScope(ctx context.Context, refineryID int64) ([]ListAllActiveStationsByRefineryScopeRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveStationsByRefineryScope, refineryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveStationsByRefineryScopeRow{}
	for rows.Next() {
		var i ListAllActiveStationsByRefineryScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveStationsByStationScope = `-- name: ListAllActiveStationsByStationScope :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.active = TRUE
  AND gs.id = $1
ORDER BY gs.region_code, gs.name
`

type ListAllActiveStationsByStationScopeRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) ListAllActiveStationsByStationScope(ctx context.Context, id int64) ([]ListAllActiveStationsByStationScopeRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveStationsByStationScope, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveStationsByStationScopeRow{}
	for rows.Next() {
		var i ListAllActiveStationsByStationScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationsByFacility = `-- name: ListStationsByFacility :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.primary_facility_id = $1
  AND gs.active = TRUE
ORDER BY gs.name
`

type ListStationsByFacilityRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) ListStationsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListStationsByFacilityRow, error) {
	rows, err := q.db.Query(ctx, listStationsByFacility, primaryFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationsByFacilityRow{}
	for rows.Next() {
		var i ListStationsByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationsByRegion = `-- name: ListStationsByRegion :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
WHERE gs.region_code = $1
  AND gs.active = TRUE
ORDER BY gs.name
`

type ListStationsByRegionRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

func (q *Queries) ListStationsByRegion(ctx context.Context, regionCode string) ([]ListStationsByRegionRow, error) {
	rows, err := q.db.Query(ctx, listStationsByRegion, regionCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationsByRegionRow{}
	for rows.Next() {
		var i ListStationsByRegionRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationsServedByFacility = `-- name: ListStationsServedByFacility :many
SELECT
    gs.id, gs.code, gs.name, gs.spbu_license_number, gs.region_code, gs.primary_facility_id, gs.location, gs.address, gs.operating_hours_start, gs.operating_hours_end, gs.contact_name, gs.contact_phone, gs.active, gs.created_at, gs.updated_at,
    ST_X(gs.location) AS longitude,
    ST_Y(gs.location) AS latitude
FROM gas_stations gs
JOIN station_facility_whitelist sfw ON sfw.station_id = gs.id
WHERE sfw.facility_id = $1
  AND gs.active = TRUE
ORDER BY gs.name
`

type ListStationsServedByFacilityRow struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Longitude           interface{}        `json:"longitude"`
	Latitude            interface{}        `json:"latitude"`
}

// Returns all stations where the facility is in the supply whitelist.
func (q *Queries) ListStationsServedByFacility(ctx context.Context, facilityID int64) ([]ListStationsServedByFacilityRow, error) {
	rows, err := q.db.Query(ctx, listStationsServedByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationsServedByFacilityRow{}
	for rows.Next() {
		var i ListStationsServedByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SpbuLicenseNumber,
			&i.RegionCode,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.Address,
			&i.OperatingHoursStart,
			&i.OperatingHoursEnd,
			&i.ContactName,
			&i.ContactPhone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStation = `-- name: UpdateStation :one
UPDATE gas_stations
SET
    name                  = $2,
    contact_name          = $3,
    contact_phone         = $4,
    operating_hours_start = $5,
    operating_hours_end   = $6,
    address               = $7,
    updated_at            = NOW()
WHERE id = $1
RETURNING id, code, name, spbu_license_number, region_code, primary_facility_id, location, address, operating_hours_start, operating_hours_end, contact_name, contact_phone, active, created_at, updated_at
`

type UpdateStationParams struct {
	ID                  int64       `json:"id"`
	Name                string      `json:"name"`
	ContactName         pgtype.Text `json:"contact_name"`
	ContactPhone        pgtype.Text `json:"contact_phone"`
	OperatingHoursStart pgtype.Time `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time `json:"operating_hours_end"`
	Address             pgtype.Text `json:"address"`
}

func (q *Queries) UpdateStation(ctx context.Context, arg UpdateStationParams) (GasStation, error) {
	row := q.db.QueryRow(ctx, updateStation,
		arg.ID,
		arg.Name,
		arg.ContactName,
		arg.ContactPhone,
		arg.OperatingHoursStart,
		arg.OperatingHoursEnd,
		arg.Address,
	)
	var i GasStation
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.SpbuLicenseNumber,
		&i.RegionCode,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.Address,
		&i.OperatingHoursStart,
		&i.OperatingHoursEnd,
		&i.ContactName,
		&i.ContactPhone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
