// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gps_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkGPSEventUUIDExists = `-- name: CheckGPSEventUUIDExists :one
SELECT EXISTS (
    SELECT 1 FROM gps_events WHERE event_uuid = $1
) AS exists
`

func (q *Queries) CheckGPSEventUUIDExists(ctx context.Context, eventUuid uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkGPSEventUUIDExists, eventUuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getLatestGPSEventByTrip = `-- name: GetLatestGPSEventByTrip :one
SELECT id, trip_id, latitude, longitude, speed_kmh, heading_deg, event_timestamp
FROM gps_events
WHERE trip_id = $1
ORDER BY event_timestamp DESC
LIMIT 1
`

type GetLatestGPSEventByTripRow struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
}

func (q *Queries) GetLatestGPSEventByTrip(ctx context.Context, tripID int64) (GetLatestGPSEventByTripRow, error) {
	row := q.db.QueryRow(ctx, getLatestGPSEventByTrip, tripID)
	var i GetLatestGPSEventByTripRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Latitude,
		&i.Longitude,
		&i.SpeedKmh,
		&i.HeadingDeg,
		&i.EventTimestamp,
	)
	return i, err
}

const insertGPSEvent = `-- name: InsertGPSEvent :one

INSERT INTO gps_events (
    trip_id, event_uuid,
    latitude, longitude,
    location,
    speed_kmh, heading_deg, accuracy_m,
    event_timestamp
) VALUES (
    $1, $2,
    $3, $4,
    ST_SetSRID(ST_MakePoint($4, $3), 4326),
    $5, $6, $7,
    $8
)
RETURNING id, trip_id, event_uuid, latitude, longitude,
          speed_kmh, heading_deg, accuracy_m,
          event_timestamp, received_at
`

type InsertGPSEventParams struct {
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
}

type InsertGPSEventRow struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

// =============================================================================
// SECTION 26 — GPS EVENTS (APPEND-ONLY, PARTITIONED)
// =============================================================================
// Partition routing is transparent; insert to parent table.
func (q *Queries) InsertGPSEvent(ctx context.Context, arg InsertGPSEventParams) (InsertGPSEventRow, error) {
	row := q.db.QueryRow(ctx, insertGPSEvent,
		arg.TripID,
		arg.EventUuid,
		arg.Latitude,
		arg.Longitude,
		arg.SpeedKmh,
		arg.HeadingDeg,
		arg.AccuracyM,
		arg.EventTimestamp,
	)
	var i InsertGPSEventRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventUuid,
		&i.Latitude,
		&i.Longitude,
		&i.SpeedKmh,
		&i.HeadingDeg,
		&i.AccuracyM,
		&i.EventTimestamp,
		&i.ReceivedAt,
	)
	return i, err
}

const listGPSEventsByTrip = `-- name: ListGPSEventsByTrip :many
SELECT id, trip_id, latitude, longitude, speed_kmh, heading_deg, event_timestamp
FROM gps_events
WHERE trip_id = $1
ORDER BY event_timestamp ASC
`

type ListGPSEventsByTripRow struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
}

func (q *Queries) ListGPSEventsByTrip(ctx context.Context, tripID int64) ([]ListGPSEventsByTripRow, error) {
	rows, err := q.db.Query(ctx, listGPSEventsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGPSEventsByTripRow{}
	for rows.Next() {
		var i ListGPSEventsByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Latitude,
			&i.Longitude,
			&i.SpeedKmh,
			&i.HeadingDeg,
			&i.EventTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGPSEventsByTripAndTimeRange = `-- name: ListGPSEventsByTripAndTimeRange :many
SELECT id, trip_id, latitude, longitude, speed_kmh, heading_deg, event_timestamp
FROM gps_events
WHERE trip_id         = $1
  AND event_timestamp >= $2
  AND event_timestamp <= $3
ORDER BY event_timestamp ASC
`

type ListGPSEventsByTripAndTimeRangeParams struct {
	TripID           int64              `json:"trip_id"`
	EventTimestamp   pgtype.Timestamptz `json:"event_timestamp"`
	EventTimestamp_2 pgtype.Timestamptz `json:"event_timestamp_2"`
}

type ListGPSEventsByTripAndTimeRangeRow struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
}

// Route reconstruction for a trip segment.
func (q *Queries) ListGPSEventsByTripAndTimeRange(ctx context.Context, arg ListGPSEventsByTripAndTimeRangeParams) ([]ListGPSEventsByTripAndTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, listGPSEventsByTripAndTimeRange, arg.TripID, arg.EventTimestamp, arg.EventTimestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGPSEventsByTripAndTimeRangeRow{}
	for rows.Next() {
		var i ListGPSEventsByTripAndTimeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Latitude,
			&i.Longitude,
			&i.SpeedKmh,
			&i.HeadingDeg,
			&i.EventTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
