// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalStatusT string

const (
	ApprovalStatusTPENDING   ApprovalStatusT = "PENDING"
	ApprovalStatusTAPPROVED  ApprovalStatusT = "APPROVED"
	ApprovalStatusTREJECTED  ApprovalStatusT = "REJECTED"
	ApprovalStatusTESCALATED ApprovalStatusT = "ESCALATED"
)

func (e *ApprovalStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatusT(s)
	case string:
		*e = ApprovalStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatusT: %T", src)
	}
	return nil
}

type NullApprovalStatusT struct {
	ApprovalStatusT ApprovalStatusT `json:"approval_status_t"`
	Valid           bool            `json:"valid"` // Valid is true if ApprovalStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatusT), nil
}

func (e ApprovalStatusT) Valid() bool {
	switch e {
	case ApprovalStatusTPENDING,
		ApprovalStatusTAPPROVED,
		ApprovalStatusTREJECTED,
		ApprovalStatusTESCALATED:
		return true
	}
	return false
}

func AllApprovalStatusTValues() []ApprovalStatusT {
	return []ApprovalStatusT{
		ApprovalStatusTPENDING,
		ApprovalStatusTAPPROVED,
		ApprovalStatusTREJECTED,
		ApprovalStatusTESCALATED,
	}
}

type CompartmentDeliveryStatusT string

const (
	CompartmentDeliveryStatusTPENDING   CompartmentDeliveryStatusT = "PENDING"
	CompartmentDeliveryStatusTDELIVERED CompartmentDeliveryStatusT = "DELIVERED"
	CompartmentDeliveryStatusTDISPUTED  CompartmentDeliveryStatusT = "DISPUTED"
)

func (e *CompartmentDeliveryStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompartmentDeliveryStatusT(s)
	case string:
		*e = CompartmentDeliveryStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for CompartmentDeliveryStatusT: %T", src)
	}
	return nil
}

type NullCompartmentDeliveryStatusT struct {
	CompartmentDeliveryStatusT CompartmentDeliveryStatusT `json:"compartment_delivery_status_t"`
	Valid                      bool                       `json:"valid"` // Valid is true if CompartmentDeliveryStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompartmentDeliveryStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.CompartmentDeliveryStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompartmentDeliveryStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompartmentDeliveryStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompartmentDeliveryStatusT), nil
}

func (e CompartmentDeliveryStatusT) Valid() bool {
	switch e {
	case CompartmentDeliveryStatusTPENDING,
		CompartmentDeliveryStatusTDELIVERED,
		CompartmentDeliveryStatusTDISPUTED:
		return true
	}
	return false
}

func AllCompartmentDeliveryStatusTValues() []CompartmentDeliveryStatusT {
	return []CompartmentDeliveryStatusT{
		CompartmentDeliveryStatusTPENDING,
		CompartmentDeliveryStatusTDELIVERED,
		CompartmentDeliveryStatusTDISPUTED,
	}
}

type DestinationTypeT string

const (
	DestinationTypeTSTATION          DestinationTypeT = "STATION"
	DestinationTypeTREFINERYFACILITY DestinationTypeT = "REFINERY_FACILITY"
)

func (e *DestinationTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DestinationTypeT(s)
	case string:
		*e = DestinationTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for DestinationTypeT: %T", src)
	}
	return nil
}

type NullDestinationTypeT struct {
	DestinationTypeT DestinationTypeT `json:"destination_type_t"`
	Valid            bool             `json:"valid"` // Valid is true if DestinationTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDestinationTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.DestinationTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DestinationTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDestinationTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DestinationTypeT), nil
}

func (e DestinationTypeT) Valid() bool {
	switch e {
	case DestinationTypeTSTATION,
		DestinationTypeTREFINERYFACILITY:
		return true
	}
	return false
}

func AllDestinationTypeTValues() []DestinationTypeT {
	return []DestinationTypeT{
		DestinationTypeTSTATION,
		DestinationTypeTREFINERYFACILITY,
	}
}

type DoStatusT string

const (
	DoStatusTDRAFT           DoStatusT = "DRAFT"
	DoStatusTPENDINGAPPROVAL DoStatusT = "PENDING_APPROVAL"
	DoStatusTAPPROVED        DoStatusT = "APPROVED"
	DoStatusTASSIGNED        DoStatusT = "ASSIGNED"
	DoStatusTINPROGRESS      DoStatusT = "IN_PROGRESS"
	DoStatusTDELIVERED       DoStatusT = "DELIVERED"
	DoStatusTRECONCILED      DoStatusT = "RECONCILED"
	DoStatusTCLOSED          DoStatusT = "CLOSED"
	DoStatusTDISPUTED        DoStatusT = "DISPUTED"
	DoStatusTCANCELLED       DoStatusT = "CANCELLED"
)

func (e *DoStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DoStatusT(s)
	case string:
		*e = DoStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for DoStatusT: %T", src)
	}
	return nil
}

type NullDoStatusT struct {
	DoStatusT DoStatusT `json:"do_status_t"`
	Valid     bool      `json:"valid"` // Valid is true if DoStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDoStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.DoStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DoStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDoStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DoStatusT), nil
}

func (e DoStatusT) Valid() bool {
	switch e {
	case DoStatusTDRAFT,
		DoStatusTPENDINGAPPROVAL,
		DoStatusTAPPROVED,
		DoStatusTASSIGNED,
		DoStatusTINPROGRESS,
		DoStatusTDELIVERED,
		DoStatusTRECONCILED,
		DoStatusTCLOSED,
		DoStatusTDISPUTED,
		DoStatusTCANCELLED:
		return true
	}
	return false
}

func AllDoStatusTValues() []DoStatusT {
	return []DoStatusT{
		DoStatusTDRAFT,
		DoStatusTPENDINGAPPROVAL,
		DoStatusTAPPROVED,
		DoStatusTASSIGNED,
		DoStatusTINPROGRESS,
		DoStatusTDELIVERED,
		DoStatusTRECONCILED,
		DoStatusTCLOSED,
		DoStatusTDISPUTED,
		DoStatusTCANCELLED,
	}
}

type DocumentTypeT string

const (
	DocumentTypeTDELIVERYORDER   DocumentTypeT = "DELIVERY_ORDER"
	DocumentTypeTBILLOFLADING    DocumentTypeT = "BILL_OF_LADING"
	DocumentTypeTDELIVERYRECEIPT DocumentTypeT = "DELIVERY_RECEIPT"
)

func (e *DocumentTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentTypeT(s)
	case string:
		*e = DocumentTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentTypeT: %T", src)
	}
	return nil
}

type NullDocumentTypeT struct {
	DocumentTypeT DocumentTypeT `json:"document_type_t"`
	Valid         bool          `json:"valid"` // Valid is true if DocumentTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentTypeT), nil
}

func (e DocumentTypeT) Valid() bool {
	switch e {
	case DocumentTypeTDELIVERYORDER,
		DocumentTypeTBILLOFLADING,
		DocumentTypeTDELIVERYRECEIPT:
		return true
	}
	return false
}

func AllDocumentTypeTValues() []DocumentTypeT {
	return []DocumentTypeT{
		DocumentTypeTDELIVERYORDER,
		DocumentTypeTBILLOFLADING,
		DocumentTypeTDELIVERYRECEIPT,
	}
}

type FuelCategoryT string

const (
	FuelCategoryTGASOLINE FuelCategoryT = "GASOLINE"
	FuelCategoryTDIESEL   FuelCategoryT = "DIESEL"
)

func (e *FuelCategoryT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FuelCategoryT(s)
	case string:
		*e = FuelCategoryT(s)
	default:
		return fmt.Errorf("unsupported scan type for FuelCategoryT: %T", src)
	}
	return nil
}

type NullFuelCategoryT struct {
	FuelCategoryT FuelCategoryT `json:"fuel_category_t"`
	Valid         bool          `json:"valid"` // Valid is true if FuelCategoryT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFuelCategoryT) Scan(value interface{}) error {
	if value == nil {
		ns.FuelCategoryT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FuelCategoryT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFuelCategoryT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FuelCategoryT), nil
}

func (e FuelCategoryT) Valid() bool {
	switch e {
	case FuelCategoryTGASOLINE,
		FuelCategoryTDIESEL:
		return true
	}
	return false
}

func AllFuelCategoryTValues() []FuelCategoryT {
	return []FuelCategoryT{
		FuelCategoryTGASOLINE,
		FuelCategoryTDIESEL,
	}
}

type MeasurementMethodT string

const (
	MeasurementMethodTWEIGHTBRIDGE   MeasurementMethodT = "WEIGHT_BRIDGE"
	MeasurementMethodTMANUALAPPROVED MeasurementMethodT = "MANUAL_APPROVED"
)

func (e *MeasurementMethodT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeasurementMethodT(s)
	case string:
		*e = MeasurementMethodT(s)
	default:
		return fmt.Errorf("unsupported scan type for MeasurementMethodT: %T", src)
	}
	return nil
}

type NullMeasurementMethodT struct {
	MeasurementMethodT MeasurementMethodT `json:"measurement_method_t"`
	Valid              bool               `json:"valid"` // Valid is true if MeasurementMethodT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeasurementMethodT) Scan(value interface{}) error {
	if value == nil {
		ns.MeasurementMethodT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeasurementMethodT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeasurementMethodT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeasurementMethodT), nil
}

func (e MeasurementMethodT) Valid() bool {
	switch e {
	case MeasurementMethodTWEIGHTBRIDGE,
		MeasurementMethodTMANUALAPPROVED:
		return true
	}
	return false
}

func AllMeasurementMethodTValues() []MeasurementMethodT {
	return []MeasurementMethodT{
		MeasurementMethodTWEIGHTBRIDGE,
		MeasurementMethodTMANUALAPPROVED,
	}
}

type NotificationTypeT string

const (
	NotificationTypeTDORAISED                   NotificationTypeT = "DO_RAISED"
	NotificationTypeTDOAPPROVED                 NotificationTypeT = "DO_APPROVED"
	NotificationTypeTTRIPASSIGNED               NotificationTypeT = "TRIP_ASSIGNED"
	NotificationTypeTLOADINGCOMPLETE            NotificationTypeT = "LOADING_COMPLETE"
	NotificationTypeTTRIPDEPARTED               NotificationTypeT = "TRIP_DEPARTED"
	NotificationTypeTDELIVERYCOMPLETE           NotificationTypeT = "DELIVERY_COMPLETE"
	NotificationTypeTVARIANCEFLAGGED            NotificationTypeT = "VARIANCE_FLAGGED"
	NotificationTypeTSEALMISMATCH               NotificationTypeT = "SEAL_MISMATCH"
	NotificationTypeTROUTEDEVIATIONWARN         NotificationTypeT = "ROUTE_DEVIATION_WARN"
	NotificationTypeTROUTEDEVIATIONESCALATE     NotificationTypeT = "ROUTE_DEVIATION_ESCALATE"
	NotificationTypeTMANUALMEASUREMENTPENDING   NotificationTypeT = "MANUAL_MEASUREMENT_PENDING"
	NotificationTypeTMANUALMEASUREMENTESCALATED NotificationTypeT = "MANUAL_MEASUREMENT_ESCALATED"
	NotificationTypeTDRIVERLICENSEEXPIRING      NotificationTypeT = "DRIVER_LICENSE_EXPIRING"
	NotificationTypeTVEHICLEKEUREXPIRING        NotificationTypeT = "VEHICLE_KEUR_EXPIRING"
	NotificationTypeTRETURNTRIPCREATED          NotificationTypeT = "RETURN_TRIP_CREATED"
)

func (e *NotificationTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTypeT(s)
	case string:
		*e = NotificationTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTypeT: %T", src)
	}
	return nil
}

type NullNotificationTypeT struct {
	NotificationTypeT NotificationTypeT `json:"notification_type_t"`
	Valid             bool              `json:"valid"` // Valid is true if NotificationTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTypeT), nil
}

func (e NotificationTypeT) Valid() bool {
	switch e {
	case NotificationTypeTDORAISED,
		NotificationTypeTDOAPPROVED,
		NotificationTypeTTRIPASSIGNED,
		NotificationTypeTLOADINGCOMPLETE,
		NotificationTypeTTRIPDEPARTED,
		NotificationTypeTDELIVERYCOMPLETE,
		NotificationTypeTVARIANCEFLAGGED,
		NotificationTypeTSEALMISMATCH,
		NotificationTypeTROUTEDEVIATIONWARN,
		NotificationTypeTROUTEDEVIATIONESCALATE,
		NotificationTypeTMANUALMEASUREMENTPENDING,
		NotificationTypeTMANUALMEASUREMENTESCALATED,
		NotificationTypeTDRIVERLICENSEEXPIRING,
		NotificationTypeTVEHICLEKEUREXPIRING,
		NotificationTypeTRETURNTRIPCREATED:
		return true
	}
	return false
}

func AllNotificationTypeTValues() []NotificationTypeT {
	return []NotificationTypeT{
		NotificationTypeTDORAISED,
		NotificationTypeTDOAPPROVED,
		NotificationTypeTTRIPASSIGNED,
		NotificationTypeTLOADINGCOMPLETE,
		NotificationTypeTTRIPDEPARTED,
		NotificationTypeTDELIVERYCOMPLETE,
		NotificationTypeTVARIANCEFLAGGED,
		NotificationTypeTSEALMISMATCH,
		NotificationTypeTROUTEDEVIATIONWARN,
		NotificationTypeTROUTEDEVIATIONESCALATE,
		NotificationTypeTMANUALMEASUREMENTPENDING,
		NotificationTypeTMANUALMEASUREMENTESCALATED,
		NotificationTypeTDRIVERLICENSEEXPIRING,
		NotificationTypeTVEHICLEKEUREXPIRING,
		NotificationTypeTRETURNTRIPCREATED,
	}
}

type PhotoEventT string

const (
	PhotoEventTWEIGHTBRIDGETARE  PhotoEventT = "WEIGHT_BRIDGE_TARE"
	PhotoEventTWEIGHTBRIDGEGROSS PhotoEventT = "WEIGHT_BRIDGE_GROSS"
	PhotoEventTCOMPARTMENTSEALED PhotoEventT = "COMPARTMENT_SEALED"
	PhotoEventTSTATIONTANKBEFORE PhotoEventT = "STATION_TANK_BEFORE"
	PhotoEventTPUMPMETERREADING  PhotoEventT = "PUMP_METER_READING"
	PhotoEventTSTATIONTANKAFTER  PhotoEventT = "STATION_TANK_AFTER"
	PhotoEventTVARIANCEEVIDENCE  PhotoEventT = "VARIANCE_EVIDENCE"
)

func (e *PhotoEventT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PhotoEventT(s)
	case string:
		*e = PhotoEventT(s)
	default:
		return fmt.Errorf("unsupported scan type for PhotoEventT: %T", src)
	}
	return nil
}

type NullPhotoEventT struct {
	PhotoEventT PhotoEventT `json:"photo_event_t"`
	Valid       bool        `json:"valid"` // Valid is true if PhotoEventT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPhotoEventT) Scan(value interface{}) error {
	if value == nil {
		ns.PhotoEventT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PhotoEventT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPhotoEventT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PhotoEventT), nil
}

func (e PhotoEventT) Valid() bool {
	switch e {
	case PhotoEventTWEIGHTBRIDGETARE,
		PhotoEventTWEIGHTBRIDGEGROSS,
		PhotoEventTCOMPARTMENTSEALED,
		PhotoEventTSTATIONTANKBEFORE,
		PhotoEventTPUMPMETERREADING,
		PhotoEventTSTATIONTANKAFTER,
		PhotoEventTVARIANCEEVIDENCE:
		return true
	}
	return false
}

func AllPhotoEventTValues() []PhotoEventT {
	return []PhotoEventT{
		PhotoEventTWEIGHTBRIDGETARE,
		PhotoEventTWEIGHTBRIDGEGROSS,
		PhotoEventTCOMPARTMENTSEALED,
		PhotoEventTSTATIONTANKBEFORE,
		PhotoEventTPUMPMETERREADING,
		PhotoEventTSTATIONTANKAFTER,
		PhotoEventTVARIANCEEVIDENCE,
	}
}

type RoleScopeT string

const (
	RoleScopeTCOMPANY  RoleScopeT = "COMPANY"
	RoleScopeTREGION   RoleScopeT = "REGION"
	RoleScopeTREFINERY RoleScopeT = "REFINERY"
	RoleScopeTFACILITY RoleScopeT = "FACILITY"
	RoleScopeTDEPOT    RoleScopeT = "DEPOT"
	RoleScopeTSTATION  RoleScopeT = "STATION"
)

func (e *RoleScopeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleScopeT(s)
	case string:
		*e = RoleScopeT(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleScopeT: %T", src)
	}
	return nil
}

type NullRoleScopeT struct {
	RoleScopeT RoleScopeT `json:"role_scope_t"`
	Valid      bool       `json:"valid"` // Valid is true if RoleScopeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleScopeT) Scan(value interface{}) error {
	if value == nil {
		ns.RoleScopeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleScopeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleScopeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleScopeT), nil
}

func (e RoleScopeT) Valid() bool {
	switch e {
	case RoleScopeTCOMPANY,
		RoleScopeTREGION,
		RoleScopeTREFINERY,
		RoleScopeTFACILITY,
		RoleScopeTDEPOT,
		RoleScopeTSTATION:
		return true
	}
	return false
}

func AllRoleScopeTValues() []RoleScopeT {
	return []RoleScopeT{
		RoleScopeTCOMPANY,
		RoleScopeTREGION,
		RoleScopeTREFINERY,
		RoleScopeTFACILITY,
		RoleScopeTDEPOT,
		RoleScopeTSTATION,
	}
}

type SealStatusT string

const (
	SealStatusTINTACT     SealStatusT = "INTACT"
	SealStatusTMISMATCHED SealStatusT = "MISMATCHED"
	SealStatusTBROKEN     SealStatusT = "BROKEN"
	SealStatusTMISSING    SealStatusT = "MISSING"
)

func (e *SealStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SealStatusT(s)
	case string:
		*e = SealStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for SealStatusT: %T", src)
	}
	return nil
}

type NullSealStatusT struct {
	SealStatusT SealStatusT `json:"seal_status_t"`
	Valid       bool        `json:"valid"` // Valid is true if SealStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSealStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.SealStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SealStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSealStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SealStatusT), nil
}

func (e SealStatusT) Valid() bool {
	switch e {
	case SealStatusTINTACT,
		SealStatusTMISMATCHED,
		SealStatusTBROKEN,
		SealStatusTMISSING:
		return true
	}
	return false
}

func AllSealStatusTValues() []SealStatusT {
	return []SealStatusT{
		SealStatusTINTACT,
		SealStatusTMISMATCHED,
		SealStatusTBROKEN,
		SealStatusTMISSING,
	}
}

type TripEventTypeT string

const (
	TripEventTypeTDRIVERACKNOWLEDGED         TripEventTypeT = "DRIVER_ACKNOWLEDGED"
	TripEventTypeTPRETRIPINSPECTIONSTARTED   TripEventTypeT = "PRE_TRIP_INSPECTION_STARTED"
	TripEventTypeTPRETRIPINSPECTIONCOMPLETED TripEventTypeT = "PRE_TRIP_INSPECTION_COMPLETED"
	TripEventTypeTARRIVEDATFACILITY          TripEventTypeT = "ARRIVED_AT_FACILITY"
	TripEventTypeTLOADINGSTARTED             TripEventTypeT = "LOADING_STARTED"
	TripEventTypeTCOMPARTMENTFILLED          TripEventTypeT = "COMPARTMENT_FILLED"
	TripEventTypeTCOMPARTMENTSEALED          TripEventTypeT = "COMPARTMENT_SEALED"
	TripEventTypeTWEIGHTBRIDGETARERECORDED   TripEventTypeT = "WEIGHT_BRIDGE_TARE_RECORDED"
	TripEventTypeTWEIGHTBRIDGEGROSSRECORDED  TripEventTypeT = "WEIGHT_BRIDGE_GROSS_RECORDED"
	TripEventTypeTWEIGHTBRIDGEAPPROVED       TripEventTypeT = "WEIGHT_BRIDGE_APPROVED"
	TripEventTypeTLOADINGCOMPLETED           TripEventTypeT = "LOADING_COMPLETED"
	TripEventTypeTDEPARTEDFACILITY           TripEventTypeT = "DEPARTED_FACILITY"
	TripEventTypeTROUTEDEVIATIONDETECTED     TripEventTypeT = "ROUTE_DEVIATION_DETECTED"
	TripEventTypeTARRIVEDATDESTINATION       TripEventTypeT = "ARRIVED_AT_DESTINATION"
	TripEventTypeTUNLOADINGSTARTED           TripEventTypeT = "UNLOADING_STARTED"
	TripEventTypeTCOMPARTMENTDELIVERED       TripEventTypeT = "COMPARTMENT_DELIVERED"
	TripEventTypeTSEALVERIFIED               TripEventTypeT = "SEAL_VERIFIED"
	TripEventTypeTSEALMISMATCHFLAGGED        TripEventTypeT = "SEAL_MISMATCH_FLAGGED"
	TripEventTypeTDELIVERYCOMPLETED          TripEventTypeT = "DELIVERY_COMPLETED"
	TripEventTypeTVARIANCEFLAGGED            TripEventTypeT = "VARIANCE_FLAGGED"
	TripEventTypeTTRIPCANCELLED              TripEventTypeT = "TRIP_CANCELLED"
	TripEventTypeTRETURNINITIATED            TripEventTypeT = "RETURN_INITIATED"
)

func (e *TripEventTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripEventTypeT(s)
	case string:
		*e = TripEventTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for TripEventTypeT: %T", src)
	}
	return nil
}

type NullTripEventTypeT struct {
	TripEventTypeT TripEventTypeT `json:"trip_event_type_t"`
	Valid          bool           `json:"valid"` // Valid is true if TripEventTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripEventTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.TripEventTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripEventTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripEventTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripEventTypeT), nil
}

func (e TripEventTypeT) Valid() bool {
	switch e {
	case TripEventTypeTDRIVERACKNOWLEDGED,
		TripEventTypeTPRETRIPINSPECTIONSTARTED,
		TripEventTypeTPRETRIPINSPECTIONCOMPLETED,
		TripEventTypeTARRIVEDATFACILITY,
		TripEventTypeTLOADINGSTARTED,
		TripEventTypeTCOMPARTMENTFILLED,
		TripEventTypeTCOMPARTMENTSEALED,
		TripEventTypeTWEIGHTBRIDGETARERECORDED,
		TripEventTypeTWEIGHTBRIDGEGROSSRECORDED,
		TripEventTypeTWEIGHTBRIDGEAPPROVED,
		TripEventTypeTLOADINGCOMPLETED,
		TripEventTypeTDEPARTEDFACILITY,
		TripEventTypeTROUTEDEVIATIONDETECTED,
		TripEventTypeTARRIVEDATDESTINATION,
		TripEventTypeTUNLOADINGSTARTED,
		TripEventTypeTCOMPARTMENTDELIVERED,
		TripEventTypeTSEALVERIFIED,
		TripEventTypeTSEALMISMATCHFLAGGED,
		TripEventTypeTDELIVERYCOMPLETED,
		TripEventTypeTVARIANCEFLAGGED,
		TripEventTypeTTRIPCANCELLED,
		TripEventTypeTRETURNINITIATED:
		return true
	}
	return false
}

func AllTripEventTypeTValues() []TripEventTypeT {
	return []TripEventTypeT{
		TripEventTypeTDRIVERACKNOWLEDGED,
		TripEventTypeTPRETRIPINSPECTIONSTARTED,
		TripEventTypeTPRETRIPINSPECTIONCOMPLETED,
		TripEventTypeTARRIVEDATFACILITY,
		TripEventTypeTLOADINGSTARTED,
		TripEventTypeTCOMPARTMENTFILLED,
		TripEventTypeTCOMPARTMENTSEALED,
		TripEventTypeTWEIGHTBRIDGETARERECORDED,
		TripEventTypeTWEIGHTBRIDGEGROSSRECORDED,
		TripEventTypeTWEIGHTBRIDGEAPPROVED,
		TripEventTypeTLOADINGCOMPLETED,
		TripEventTypeTDEPARTEDFACILITY,
		TripEventTypeTROUTEDEVIATIONDETECTED,
		TripEventTypeTARRIVEDATDESTINATION,
		TripEventTypeTUNLOADINGSTARTED,
		TripEventTypeTCOMPARTMENTDELIVERED,
		TripEventTypeTSEALVERIFIED,
		TripEventTypeTSEALMISMATCHFLAGGED,
		TripEventTypeTDELIVERYCOMPLETED,
		TripEventTypeTVARIANCEFLAGGED,
		TripEventTypeTTRIPCANCELLED,
		TripEventTypeTRETURNINITIATED,
	}
}

type TripStatusT string

const (
	TripStatusTCREATED            TripStatusT = "CREATED"
	TripStatusTDRIVERACKNOWLEDGED TripStatusT = "DRIVER_ACKNOWLEDGED"
	TripStatusTPRETRIPINSPECTION  TripStatusT = "PRE_TRIP_INSPECTION"
	TripStatusTLOADING            TripStatusT = "LOADING"
	TripStatusTLOADED             TripStatusT = "LOADED"
	TripStatusTINTRANSIT          TripStatusT = "IN_TRANSIT"
	TripStatusTARRIVED            TripStatusT = "ARRIVED"
	TripStatusTUNLOADING          TripStatusT = "UNLOADING"
	TripStatusTDELIVERED          TripStatusT = "DELIVERED"
	TripStatusTRECONCILED         TripStatusT = "RECONCILED"
	TripStatusTCLOSED             TripStatusT = "CLOSED"
	TripStatusTDISPUTED           TripStatusT = "DISPUTED"
	TripStatusTCANCELLED          TripStatusT = "CANCELLED"
)

func (e *TripStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatusT(s)
	case string:
		*e = TripStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatusT: %T", src)
	}
	return nil
}

type NullTripStatusT struct {
	TripStatusT TripStatusT `json:"trip_status_t"`
	Valid       bool        `json:"valid"` // Valid is true if TripStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatusT), nil
}

func (e TripStatusT) Valid() bool {
	switch e {
	case TripStatusTCREATED,
		TripStatusTDRIVERACKNOWLEDGED,
		TripStatusTPRETRIPINSPECTION,
		TripStatusTLOADING,
		TripStatusTLOADED,
		TripStatusTINTRANSIT,
		TripStatusTARRIVED,
		TripStatusTUNLOADING,
		TripStatusTDELIVERED,
		TripStatusTRECONCILED,
		TripStatusTCLOSED,
		TripStatusTDISPUTED,
		TripStatusTCANCELLED:
		return true
	}
	return false
}

func AllTripStatusTValues() []TripStatusT {
	return []TripStatusT{
		TripStatusTCREATED,
		TripStatusTDRIVERACKNOWLEDGED,
		TripStatusTPRETRIPINSPECTION,
		TripStatusTLOADING,
		TripStatusTLOADED,
		TripStatusTINTRANSIT,
		TripStatusTARRIVED,
		TripStatusTUNLOADING,
		TripStatusTDELIVERED,
		TripStatusTRECONCILED,
		TripStatusTCLOSED,
		TripStatusTDISPUTED,
		TripStatusTCANCELLED,
	}
}

type UserRoleT string

const (
	UserRoleTSYSTEMADMIN      UserRoleT = "SYSTEM_ADMIN"
	UserRoleTREFINERYADMIN    UserRoleT = "REFINERY_ADMIN"
	UserRoleTFACILITYMANAGER  UserRoleT = "FACILITY_MANAGER"
	UserRoleTFACILITYOPERATOR UserRoleT = "FACILITY_OPERATOR"
	UserRoleTDEPOTSTAFF       UserRoleT = "DEPOT_STAFF"
	UserRoleTSTATIONMANAGER   UserRoleT = "STATION_MANAGER"
	UserRoleTDRIVER           UserRoleT = "DRIVER"
)

func (e *UserRoleT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleT(s)
	case string:
		*e = UserRoleT(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleT: %T", src)
	}
	return nil
}

type NullUserRoleT struct {
	UserRoleT UserRoleT `json:"user_role_t"`
	Valid     bool      `json:"valid"` // Valid is true if UserRoleT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleT) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleT), nil
}

func (e UserRoleT) Valid() bool {
	switch e {
	case UserRoleTSYSTEMADMIN,
		UserRoleTREFINERYADMIN,
		UserRoleTFACILITYMANAGER,
		UserRoleTFACILITYOPERATOR,
		UserRoleTDEPOTSTAFF,
		UserRoleTSTATIONMANAGER,
		UserRoleTDRIVER:
		return true
	}
	return false
}

func AllUserRoleTValues() []UserRoleT {
	return []UserRoleT{
		UserRoleTSYSTEMADMIN,
		UserRoleTREFINERYADMIN,
		UserRoleTFACILITYMANAGER,
		UserRoleTFACILITYOPERATOR,
		UserRoleTDEPOTSTAFF,
		UserRoleTSTATIONMANAGER,
		UserRoleTDRIVER,
	}
}

type VehicleStatusT string

const (
	VehicleStatusTAVAILABLE        VehicleStatusT = "AVAILABLE"
	VehicleStatusTASSIGNED         VehicleStatusT = "ASSIGNED"
	VehicleStatusTINTRANSIT        VehicleStatusT = "IN_TRANSIT"
	VehicleStatusTUNDERMAINTENANCE VehicleStatusT = "UNDER_MAINTENANCE"
	VehicleStatusTDECOMMISSIONED   VehicleStatusT = "DECOMMISSIONED"
)

func (e *VehicleStatusT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleStatusT(s)
	case string:
		*e = VehicleStatusT(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleStatusT: %T", src)
	}
	return nil
}

type NullVehicleStatusT struct {
	VehicleStatusT VehicleStatusT `json:"vehicle_status_t"`
	Valid          bool           `json:"valid"` // Valid is true if VehicleStatusT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleStatusT) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleStatusT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleStatusT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleStatusT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleStatusT), nil
}

func (e VehicleStatusT) Valid() bool {
	switch e {
	case VehicleStatusTAVAILABLE,
		VehicleStatusTASSIGNED,
		VehicleStatusTINTRANSIT,
		VehicleStatusTUNDERMAINTENANCE,
		VehicleStatusTDECOMMISSIONED:
		return true
	}
	return false
}

func AllVehicleStatusTValues() []VehicleStatusT {
	return []VehicleStatusT{
		VehicleStatusTAVAILABLE,
		VehicleStatusTASSIGNED,
		VehicleStatusTINTRANSIT,
		VehicleStatusTUNDERMAINTENANCE,
		VehicleStatusTDECOMMISSIONED,
	}
}

type AuditLog struct {
	ID          int64              `json:"id"`
	UserID      pgtype.Int8        `json:"user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	BeforeState json.RawMessage    `json:"before_state"`
	AfterState  json.RawMessage    `json:"after_state"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CompartmentSeal struct {
	ID                 int64              `json:"id"`
	TripID             int64              `json:"trip_id"`
	CompartmentID      int64              `json:"compartment_id"`
	SealNumberIssued   string             `json:"seal_number_issued"`
	IssuedBy           int64              `json:"issued_by"`
	IssuedAt           pgtype.Timestamptz `json:"issued_at"`
	SealNumberVerified pgtype.Text        `json:"seal_number_verified"`
	VerifiedBy         pgtype.Int8        `json:"verified_by"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	VerificationStatus NullSealStatusT    `json:"verification_status"`
	Notes              pgtype.Text        `json:"notes"`
}

type DeliveryOrder struct {
	ID                    int64              `json:"id"`
	DoNumber              string             `json:"do_number"`
	Status                DoStatusT          `json:"status"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	ScheduledDate         pgtype.Date        `json:"scheduled_date"`
	Notes                 pgtype.Text        `json:"notes"`
	RaisedBy              int64              `json:"raised_by"`
	ApprovedBy            pgtype.Int8        `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	AssignedVehicleID     pgtype.Int8        `json:"assigned_vehicle_id"`
	AssignedDriverID      pgtype.Int8        `json:"assigned_driver_id"`
	AssignedAt            pgtype.Timestamptz `json:"assigned_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryOrderItem struct {
	ID               int64              `json:"id"`
	DoID             int64              `json:"do_id"`
	FuelTypeCode     string             `json:"fuel_type_code"`
	CompartmentID    pgtype.Int8        `json:"compartment_id"`
	RequestedVolumeL pgtype.Numeric     `json:"requested_volume_l"`
	AllocatedVolumeL pgtype.Numeric     `json:"allocated_volume_l"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Driver struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	EmployeeNumber    pgtype.Text        `json:"employee_number"`
	SimB2Number       string             `json:"sim_b2_number"`
	SimB2Expiry       pgtype.Date        `json:"sim_b2_expiry"`
	HomeDepotID       pgtype.Int8        `json:"home_depot_id"`
	CurrentShiftStart pgtype.Timestamptz `json:"current_shift_start"`
	CurrentShiftEnd   pgtype.Timestamptz `json:"current_shift_end"`
	IsOnShift         bool               `json:"is_on_shift"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type FacilityLoadingBay struct {
	ID           int64              `json:"id"`
	FacilityID   int64              `json:"facility_id"`
	BayCode      string             `json:"bay_code"`
	QrPayload    string             `json:"qr_payload"`
	FuelTypeCode pgtype.Text        `json:"fuel_type_code"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type FacilityStorageTank struct {
	ID              int64              `json:"id"`
	FacilityID      int64              `json:"facility_id"`
	TankCode        string             `json:"tank_code"`
	FuelTypeCode    string             `json:"fuel_type_code"`
	CapacityL       pgtype.Numeric     `json:"capacity_l"`
	CurrentVolumeL  pgtype.Numeric     `json:"current_volume_l"`
	ReservedVolumeL pgtype.Numeric     `json:"reserved_volume_l"`
	MinOperationalL pgtype.Numeric     `json:"min_operational_l"`
	Active          bool               `json:"active"`
	LastUpdatedAt   pgtype.Timestamptz `json:"last_updated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type FuelType struct {
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Category             FuelCategoryT      `json:"category"`
	RonCn                pgtype.Int2        `json:"ron_cn"`
	DensityKgPerLAt15c   pgtype.Numeric     `json:"density_kg_per_l_at_15c"`
	EvaporationFactorPct pgtype.Numeric     `json:"evaporation_factor_pct"`
	IsSubsidized         bool               `json:"is_subsidized"`
	Active               bool               `json:"active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type GasStation struct {
	ID                  int64              `json:"id"`
	Code                string             `json:"code"`
	Name                string             `json:"name"`
	SpbuLicenseNumber   string             `json:"spbu_license_number"`
	RegionCode          string             `json:"region_code"`
	PrimaryFacilityID   int64              `json:"primary_facility_id"`
	Location            interface{}        `json:"location"`
	Address             pgtype.Text        `json:"address"`
	OperatingHoursStart pgtype.Time        `json:"operating_hours_start"`
	OperatingHoursEnd   pgtype.Time        `json:"operating_hours_end"`
	ContactName         pgtype.Text        `json:"contact_name"`
	ContactPhone        pgtype.Text        `json:"contact_phone"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type GpsEvent struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202501 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202502 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202503 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202504 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202505 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202506 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202507 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202508 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202509 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202510 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202511 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202512 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202601 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202602 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202603 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202604 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202605 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202606 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202607 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202608 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202609 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202610 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202611 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202612 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202701 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202702 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202703 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202704 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202705 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202706 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202707 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202708 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202709 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202710 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202711 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type GpsEvents202712 struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Location       interface{}        `json:"location"`
	SpeedKmh       pgtype.Numeric     `json:"speed_kmh"`
	HeadingDeg     pgtype.Numeric     `json:"heading_deg"`
	AccuracyM      pgtype.Numeric     `json:"accuracy_m"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

type NotificationLog struct {
	ID                  int64              `json:"id"`
	TripID              pgtype.Int8        `json:"trip_id"`
	DoID                pgtype.Int8        `json:"do_id"`
	RecipientTelegramID int64              `json:"recipient_telegram_id"`
	RecipientUserID     pgtype.Int8        `json:"recipient_user_id"`
	NotificationType    NotificationTypeT  `json:"notification_type"`
	MessageText         string             `json:"message_text"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	DeliveryStatus      string             `json:"delivery_status"`
	TelegramMessageID   pgtype.Int8        `json:"telegram_message_id"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
}

type Refinery struct {
	ID               int64              `json:"id"`
	Code             string             `json:"code"`
	Name             string             `json:"name"`
	RegionCode       string             `json:"region_code"`
	CommissionedYear pgtype.Int2        `json:"commissioned_year"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RefineryFacility struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Region struct {
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RouteDeviationEvent struct {
	ID                 int64              `json:"id"`
	TripID             int64              `json:"trip_id"`
	DetectedAt         pgtype.Timestamptz `json:"detected_at"`
	DurationSeconds    pgtype.Int4        `json:"duration_seconds"`
	DeviationMeters    pgtype.Numeric     `json:"deviation_meters"`
	OccurrenceCount    int16              `json:"occurrence_count"`
	TelegramNotified   bool               `json:"telegram_notified"`
	TelegramNotifiedAt pgtype.Timestamptz `json:"telegram_notified_at"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
	Notes              pgtype.Text        `json:"notes"`
}

type StationFacilityWhitelist struct {
	StationID  int64 `json:"station_id"`
	FacilityID int64 `json:"facility_id"`
}

type StationQrCode struct {
	ID        int64              `json:"id"`
	StationID int64              `json:"station_id"`
	QrPayload string             `json:"qr_payload"`
	Label     pgtype.Text        `json:"label"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StationTank struct {
	ID                int64              `json:"id"`
	StationID         int64              `json:"station_id"`
	TankCode          string             `json:"tank_code"`
	FuelTypeCode      string             `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric     `json:"capacity_l"`
	CurrentVolumeL    pgtype.Numeric     `json:"current_volume_l"`
	ReorderThresholdL pgtype.Numeric     `json:"reorder_threshold_l"`
	LastDipReadingL   pgtype.Numeric     `json:"last_dip_reading_l"`
	LastDipAt         pgtype.Timestamptz `json:"last_dip_at"`
	Active            bool               `json:"active"`
	LastUpdatedAt     pgtype.Timestamptz `json:"last_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SystemSetting struct {
	ID          int64              `json:"id"`
	FacilityID  pgtype.Int8        `json:"facility_id"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TelegramLinkToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Trip struct {
	ID                    int64              `json:"id"`
	DoID                  int64              `json:"do_id"`
	VehicleID             int64              `json:"vehicle_id"`
	DriverID              int64              `json:"driver_id"`
	Status                TripStatusT        `json:"status"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	RoutePolyline         interface{}        `json:"route_polyline"`
	DepartedAt            pgtype.Timestamptz `json:"departed_at"`
	ArrivedAt             pgtype.Timestamptz `json:"arrived_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	ParentTripID          pgtype.Int8        `json:"parent_trip_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type TripCompartmentDelivery struct {
	ID                int64                      `json:"id"`
	TripID            int64                      `json:"trip_id"`
	CompartmentID     int64                      `json:"compartment_id"`
	FuelTypeCode      string                     `json:"fuel_type_code"`
	LoadedVolumeL     pgtype.Numeric             `json:"loaded_volume_l"`
	LoadedWeightKg    pgtype.Numeric             `json:"loaded_weight_kg"`
	DeliveredVolumeL  pgtype.Numeric             `json:"delivered_volume_l"`
	DeliveredWeightKg pgtype.Numeric             `json:"delivered_weight_kg"`
	VarianceL         pgtype.Numeric             `json:"variance_l"`
	VariancePct       pgtype.Numeric             `json:"variance_pct"`
	MeasurementMethod NullMeasurementMethodT     `json:"measurement_method"`
	DeliveryStatus    CompartmentDeliveryStatusT `json:"delivery_status"`
	CreatedAt         pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz         `json:"updated_at"`
}

type TripDocument struct {
	ID              int64              `json:"id"`
	TripID          int64              `json:"trip_id"`
	DocumentType    DocumentTypeT      `json:"document_type"`
	DocumentNumber  pgtype.Text        `json:"document_number"`
	GarageObjectKey string             `json:"garage_object_key"`
	GeneratedBy     pgtype.Int8        `json:"generated_by"`
	GeneratedAt     pgtype.Timestamptz `json:"generated_at"`
}

type TripEvent struct {
	ID             int64              `json:"id"`
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	EventType      TripEventTypeT     `json:"event_type"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	Location       interface{}        `json:"location"`
	Payload        json.RawMessage    `json:"payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TripPhoto struct {
	ID              int64              `json:"id"`
	TripID          int64              `json:"trip_id"`
	CompartmentID   pgtype.Int8        `json:"compartment_id"`
	EventType       PhotoEventT        `json:"event_type"`
	GarageObjectKey string             `json:"garage_object_key"`
	FileSizeBytes   pgtype.Int8        `json:"file_size_bytes"`
	MimeType        string             `json:"mime_type"`
	UploadedBy      int64              `json:"uploaded_by"`
	TakenAt         pgtype.Timestamptz `json:"taken_at"`
	UploadedAt      pgtype.Timestamptz `json:"uploaded_at"`
	Notes           pgtype.Text        `json:"notes"`
}

type User struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	PasswordHash        string             `json:"password_hash"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserRoleGrant struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Role      UserRoleT          `json:"role"`
	ScopeType RoleScopeT         `json:"scope_type"`
	ScopeID   pgtype.Int8        `json:"scope_id"`
	GrantedBy pgtype.Int8        `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Vehicle struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type VehicleCompartment struct {
	ID                int64              `json:"id"`
	VehicleID         int64              `json:"vehicle_id"`
	CompartmentNumber int16              `json:"compartment_number"`
	FuelTypeCode      pgtype.Text        `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric     `json:"capacity_l"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type VehicleDepot struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	PrimaryFacilityID     int64              `json:"primary_facility_id"`
	Location              interface{}        `json:"location"`
	DefaultTruckCapacityL int32              `json:"default_truck_capacity_l"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type VehicleMaintenanceRecord struct {
	ID                int64              `json:"id"`
	VehicleID         int64              `json:"vehicle_id"`
	RecordedBy        pgtype.Int8        `json:"recorded_by"`
	MaintenanceType   string             `json:"maintenance_type"`
	Description       pgtype.Text        `json:"description"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EstimatedReturnAt pgtype.Timestamptz `json:"estimated_return_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type WeightBridgeReading struct {
	ID                 int64              `json:"id"`
	TripID             pgtype.Int8        `json:"trip_id"`
	VehicleID          int64              `json:"vehicle_id"`
	ReadingType        string             `json:"reading_type"`
	WeightKg           pgtype.Numeric     `json:"weight_kg"`
	Method             MeasurementMethodT `json:"method"`
	AmbientTempCelsius pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy         int64              `json:"recorded_by"`
	ApprovalStatus     ApprovalStatusT    `json:"approval_status"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	EscalatedAt        pgtype.Timestamptz `json:"escalated_at"`
	EscalatedTo        pgtype.Int8        `json:"escalated_to"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
