// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByTypeAndTrip = `-- name: CountNotificationsByTypeAndTrip :one
SELECT COUNT(*)::INT AS count
FROM notification_log
WHERE trip_id           = $1
  AND notification_type = $2
`

type CountNotificationsByTypeAndTripParams struct {
	TripID           pgtype.Int8       `json:"trip_id"`
	NotificationType NotificationTypeT `json:"notification_type"`
}

func (q *Queries) CountNotificationsByTypeAndTrip(ctx context.Context, arg CountNotificationsByTypeAndTripParams) (int32, error) {
	row := q.db.QueryRow(ctx, countNotificationsByTypeAndTrip, arg.TripID, arg.NotificationType)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notification_log (
    trip_id, do_id, recipient_telegram_id, recipient_user_id,
    notification_type, message_text, delivery_status, telegram_message_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, trip_id, do_id, recipient_telegram_id, recipient_user_id, notification_type, message_text, sent_at, delivery_status, telegram_message_id, error_message
`

type InsertNotificationParams struct {
	TripID              pgtype.Int8       `json:"trip_id"`
	DoID                pgtype.Int8       `json:"do_id"`
	RecipientTelegramID int64             `json:"recipient_telegram_id"`
	RecipientUserID     pgtype.Int8       `json:"recipient_user_id"`
	NotificationType    NotificationTypeT `json:"notification_type"`
	MessageText         string            `json:"message_text"`
	DeliveryStatus      string            `json:"delivery_status"`
	TelegramMessageID   pgtype.Int8       `json:"telegram_message_id"`
}

// =============================================================================
// SECTION 30 — NOTIFICATION LOG (APPEND-ONLY)
// =============================================================================
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.TripID,
		arg.DoID,
		arg.RecipientTelegramID,
		arg.RecipientUserID,
		arg.NotificationType,
		arg.MessageText,
		arg.DeliveryStatus,
		arg.TelegramMessageID,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DoID,
		&i.RecipientTelegramID,
		&i.RecipientUserID,
		&i.NotificationType,
		&i.MessageText,
		&i.SentAt,
		&i.DeliveryStatus,
		&i.TelegramMessageID,
		&i.ErrorMessage,
	)
	return i, err
}

const listNotificationsByRecipient = `-- name: ListNotificationsByRecipient :many
SELECT id, trip_id, do_id, recipient_telegram_id, recipient_user_id, notification_type, message_text, sent_at, delivery_status, telegram_message_id, error_message
FROM notification_log
WHERE recipient_user_id = $1
ORDER BY sent_at DESC
LIMIT $2
`

type ListNotificationsByRecipientParams struct {
	RecipientUserID pgtype.Int8 `json:"recipient_user_id"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListNotificationsByRecipient(ctx context.Context, arg ListNotificationsByRecipientParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationsByRecipient, arg.RecipientUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DoID,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.NotificationType,
			&i.MessageText,
			&i.SentAt,
			&i.DeliveryStatus,
			&i.TelegramMessageID,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByTrip = `-- name: ListNotificationsByTrip :many
SELECT id, trip_id, do_id, recipient_telegram_id, recipient_user_id, notification_type, message_text, sent_at, delivery_status, telegram_message_id, error_message
FROM notification_log
WHERE trip_id = $1
ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationsByTrip(ctx context.Context, tripID pgtype.Int8) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DoID,
			&i.RecipientTelegramID,
			&i.RecipientUserID,
			&i.NotificationType,
			&i.MessageText,
			&i.SentAt,
			&i.DeliveryStatus,
			&i.TelegramMessageID,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
