// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFacilityToStationWhitelist(ctx context.Context, arg AddFacilityToStationWhitelistParams) error
	// Extends route polyline with the latest GPS coordinate (called by background worker).
	AppendTripRoutePoint(ctx context.Context, arg AppendTripRoutePointParams) error
	ApproveDeliveryOrder(ctx context.Context, arg ApproveDeliveryOrderParams) (DeliveryOrder, error)
	ApproveWeightBridgeReading(ctx context.Context, arg ApproveWeightBridgeReadingParams) (WeightBridgeReading, error)
	AssignCompartmentToDOItem(ctx context.Context, arg AssignCompartmentToDOItemParams) (DeliveryOrderItem, error)
	AssignVehicleAndDriverToDO(ctx context.Context, arg AssignVehicleAndDriverToDOParams) (DeliveryOrder, error)
	CancelDeliveryOrder(ctx context.Context, id int64) (DeliveryOrder, error)
	CheckFacilityCanServeStation(ctx context.Context, arg CheckFacilityCanServeStationParams) (bool, error)
	CheckGPSEventUUIDExists(ctx context.Context, eventUuid uuid.UUID) (bool, error)
	CheckUserHasCompanyRole(ctx context.Context, arg CheckUserHasCompanyRoleParams) (bool, error)
	// Returns TRUE if the user has the given role active for the given scope.
	CheckUserHasRoleInScope(ctx context.Context, arg CheckUserHasRoleInScopeParams) (bool, error)
	CompleteMaintenanceRecord(ctx context.Context, arg CompleteMaintenanceRecordParams) (VehicleMaintenanceRecord, error)
	CountNotificationsByTypeAndTrip(ctx context.Context, arg CountNotificationsByTypeAndTripParams) (int32, error)
	CountSealMismatchesByTrip(ctx context.Context, tripID int64) (int32, error)
	// Determines escalation tier (1 = log, 2 = warn, >2 = Telegram alert).
	CountTripDeviations(ctx context.Context, tripID int64) (int32, error)
	CreateCompartment(ctx context.Context, arg CreateCompartmentParams) (VehicleCompartment, error)
	CreateCompartmentDelivery(ctx context.Context, arg CreateCompartmentDeliveryParams) (TripCompartmentDelivery, error)
	CreateDeliveryOrder(ctx context.Context, arg CreateDeliveryOrderParams) (DeliveryOrder, error)
	CreateDeliveryOrderItem(ctx context.Context, arg CreateDeliveryOrderItemParams) (DeliveryOrderItem, error)
	CreateDepot(ctx context.Context, arg CreateDepotParams) (VehicleDepot, error)
	CreateDeviationEvent(ctx context.Context, arg CreateDeviationEventParams) (RouteDeviationEvent, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateFacility(ctx context.Context, arg CreateFacilityParams) (RefineryFacility, error)
	CreateFuelType(ctx context.Context, arg CreateFuelTypeParams) (FuelType, error)
	CreateLoadingBay(ctx context.Context, arg CreateLoadingBayParams) (FacilityLoadingBay, error)
	CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (VehicleMaintenanceRecord, error)
	CreateRefinery(ctx context.Context, arg CreateRefineryParams) (Refinery, error)
	CreateStation(ctx context.Context, arg CreateStationParams) (GasStation, error)
	CreateStationQRCode(ctx context.Context, arg CreateStationQRCodeParams) (StationQrCode, error)
	CreateStationTank(ctx context.Context, arg CreateStationTankParams) (StationTank, error)
	CreateStorageTank(ctx context.Context, arg CreateStorageTankParams) (FacilityStorageTank, error)
	// =============================================================================
	// SECTION 32 — TELEGRAM LINK TOKENS
	// =============================================================================
	CreateTelegramLinkToken(ctx context.Context, arg CreateTelegramLinkTokenParams) (TelegramLinkToken, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	CreateTripDocument(ctx context.Context, arg CreateTripDocumentParams) (TripDocument, error)
	CreateTripPhoto(ctx context.Context, arg CreateTripPhotoParams) (TripPhoto, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	CreateWeightBridgeReading(ctx context.Context, arg CreateWeightBridgeReadingParams) (WeightBridgeReading, error)
	// Credit volume on return-to-facility trip delivery.
	CreditStorageTankVolume(ctx context.Context, arg CreditStorageTankVolumeParams) (FacilityStorageTank, error)
	DeactivateAllStationQRCodes(ctx context.Context, stationID int64) error
	DeactivateCompartment(ctx context.Context, id int64) error
	DeactivateFacility(ctx context.Context, id int64) error
	DeactivateFuelType(ctx context.Context, code string) error
	DeactivateLoadingBay(ctx context.Context, id int64) error
	DeactivateStation(ctx context.Context, id int64) error
	DeactivateStationQRCode(ctx context.Context, id int64) error
	DeactivateStationTank(ctx context.Context, id int64) error
	DeactivateUser(ctx context.Context, id int64) error
	DeactivateVehicle(ctx context.Context, id int64) error
	// Deduct from current volume at loading completion (simultaneously clears reservation).
	DeductStorageTankVolume(ctx context.Context, arg DeductStorageTankVolumeParams) (FacilityStorageTank, error)
	DeleteDOItem(ctx context.Context, id int64) error
	// Called by cron worker nightly.
	DeleteExpiredTelegramLinkTokens(ctx context.Context) (int64, error)
	DeleteFacilitySetting(ctx context.Context, arg DeleteFacilitySettingParams) error
	EndDriverShift(ctx context.Context, id int64) error
	// Called by background worker when Facility Manager window expires.
	EscalateWeightBridgeReading(ctx context.Context, arg EscalateWeightBridgeReadingParams) (WeightBridgeReading, error)
	GetActiveRoleForUserAndScope(ctx context.Context, arg GetActiveRoleForUserAndScopeParams) (UserRoleGrant, error)
	// =============================================================================
	// SECTION 13 — USER ROLE GRANTS
	// =============================================================================
	GetActiveRolesForUser(ctx context.Context, userID int64) ([]UserRoleGrant, error)
	// Multi-refinery ops view: one row per facility.
	GetCompanyWideDashboardSummary(ctx context.Context) ([]GetCompanyWideDashboardSummaryRow, error)
	// =============================================================================
	// SECTION 10 — VEHICLE COMPARTMENTS
	// =============================================================================
	GetCompartment(ctx context.Context, id int64) (VehicleCompartment, error)
	// =============================================================================
	// SECTION 24 — TRIP COMPARTMENT DELIVERIES
	// =============================================================================
	GetCompartmentDelivery(ctx context.Context, id int64) (TripCompartmentDelivery, error)
	GetCompartmentDeliveryByTripAndCompartment(ctx context.Context, arg GetCompartmentDeliveryByTripAndCompartmentParams) (TripCompartmentDelivery, error)
	// =============================================================================
	// SECTION 19 — DELIVERY ORDERS
	// =============================================================================
	GetDeliveryOrder(ctx context.Context, id int64) (DeliveryOrder, error)
	GetDeliveryOrderByNumber(ctx context.Context, doNumber string) (DeliveryOrder, error)
	// =============================================================================
	// SECTION 20 — DELIVERY ORDER ITEMS
	// =============================================================================
	GetDeliveryOrderItem(ctx context.Context, id int64) (DeliveryOrderItem, error)
	// =============================================================================
	// SECTION 6 — VEHICLE DEPOTS
	// =============================================================================
	GetDepot(ctx context.Context, id int64) (GetDepotRow, error)
	GetDepotByCode(ctx context.Context, code string) (GetDepotByCodeRow, error)
	// =============================================================================
	// SECTION 14 — DRIVERS
	// =============================================================================
	GetDriver(ctx context.Context, id int64) (GetDriverRow, error)
	GetDriverByUserID(ctx context.Context, userID int64) (GetDriverByUserIDRow, error)
	// Compliance scoring: variance, deviation, and seal mismatch history per driver.
	GetDriverComplianceSummary(ctx context.Context, arg GetDriverComplianceSummaryParams) (GetDriverComplianceSummaryRow, error)
	// Resolve effective value: facility-specific overrides global default.
	GetEffectiveSetting(ctx context.Context, arg GetEffectiveSettingParams) (string, error)
	// =============================================================================
	// SECTION 5 — REFINERY FACILITIES
	// =============================================================================
	GetFacility(ctx context.Context, id int64) (GetFacilityRow, error)
	GetFacilityByCode(ctx context.Context, code string) (GetFacilityByCodeRow, error)
	// =============================================================================
	// SECTION 33 — REPORTING & CROSS-TABLE QUERIES
	// =============================================================================
	// Central ops dashboard: inventory + active trip count for one facility.
	GetFacilityDashboardSummary(ctx context.Context, id int64) (GetFacilityDashboardSummaryRow, error)
	GetFacilitySetting(ctx context.Context, arg GetFacilitySettingParams) (SystemSetting, error)
	// =============================================================================
	// SECTION 2 — FUEL TYPES
	// =============================================================================
	GetFuelType(ctx context.Context, code string) (FuelType, error)
	// =============================================================================
	// SECTION 3 — SYSTEM SETTINGS
	// =============================================================================
	GetGlobalSetting(ctx context.Context, key string) (SystemSetting, error)
	GetGrossReadingByTrip(ctx context.Context, tripID pgtype.Int8) (WeightBridgeReading, error)
	GetLatestGPSEventByTrip(ctx context.Context, tripID int64) (GetLatestGPSEventByTripRow, error)
	GetLatestTripEvent(ctx context.Context, tripID int64) (TripEvent, error)
	GetLatestTripEventByType(ctx context.Context, arg GetLatestTripEventByTypeParams) (TripEvent, error)
	// =============================================================================
	// SECTION 7 — FACILITY LOADING BAYS
	// =============================================================================
	GetLoadingBay(ctx context.Context, id int64) (FacilityLoadingBay, error)
	GetLoadingBayByQRPayload(ctx context.Context, qrPayload string) (GetLoadingBayByQRPayloadRow, error)
	// =============================================================================
	// SECTION 11 — VEHICLE MAINTENANCE RECORDS
	// =============================================================================
	GetMaintenanceRecord(ctx context.Context, id int64) (VehicleMaintenanceRecord, error)
	// Verifies all mandatory photo events are present for a trip before allowing progression.
	// Returns a bitmask-style row showing which required events have at least one photo.
	// IMPORTANT: has_compartment_sealed_photo returns TRUE if >= 1 sealed photo exists.
	// The service layer must separately verify the sealed photo count matches the trip's
	// compartment count (ListCompartmentsByVehicle) before allowing LOADING → LOADED.
	GetMandatoryPhotoCheckByTrip(ctx context.Context, tripID int64) (GetMandatoryPhotoCheckByTripRow, error)
	// Reporting: delivered volume by fuel type per facility per month.
	GetMonthlyDeliveryStatsByFacility(ctx context.Context, arg GetMonthlyDeliveryStatsByFacilityParams) ([]GetMonthlyDeliveryStatsByFacilityRow, error)
	// Returns the current max sequence for a facility prefix in the current year.
	// Application formats this into DO number: DO-{RU}-{YYYY}-{seq:05d}.
	GetNextDOSequenceNumber(ctx context.Context, doNumber string) (interface{}, error)
	// Returns the most recent unresolved deviation (for cooldown state machine).
	GetOpenDeviationByTrip(ctx context.Context, tripID int64) (RouteDeviationEvent, error)
	GetPrimaryFacilityByRefinery(ctx context.Context, refineryID int64) (GetPrimaryFacilityByRefineryRow, error)
	// =============================================================================
	// SECTION 4 — REFINERIES
	// =============================================================================
	GetRefinery(ctx context.Context, id int64) (Refinery, error)
	GetRefineryByCode(ctx context.Context, code string) (Refinery, error)
	// =============================================================================
	// SECTION 1 — REGIONS
	// =============================================================================
	GetRegion(ctx context.Context, code string) (Region, error)
	// =============================================================================
	// SECTION 25 — COMPARTMENT SEALS
	// =============================================================================
	GetSealByTripAndCompartment(ctx context.Context, arg GetSealByTripAndCompartmentParams) (CompartmentSeal, error)
	// =============================================================================
	// SECTION 15 — GAS STATIONS
	// =============================================================================
	GetStation(ctx context.Context, id int64) (GetStationRow, error)
	GetStationByCode(ctx context.Context, code string) (GetStationByCodeRow, error)
	// Validates QR payload belongs to the expected station and is active.
	GetStationByQRPayload(ctx context.Context, qrPayload string) (GetStationByQRPayloadRow, error)
	// Full inventory snapshot for a station (all active tanks).
	GetStationInventorySnapshot(ctx context.Context, stationID int64) ([]GetStationInventorySnapshotRow, error)
	// =============================================================================
	// SECTION 17 — STATION QR CODES
	// =============================================================================
	GetStationQRCode(ctx context.Context, id int64) (StationQrCode, error)
	// =============================================================================
	// SECTION 18 — STATION TANKS
	// =============================================================================
	GetStationTank(ctx context.Context, id int64) (StationTank, error)
	GetStationTankByFuel(ctx context.Context, arg GetStationTankByFuelParams) (StationTank, error)
	// =============================================================================
	// SECTION 8 — FACILITY STORAGE TANKS
	// =============================================================================
	GetStorageTank(ctx context.Context, id int64) (FacilityStorageTank, error)
	GetStorageTankAvailableVolume(ctx context.Context, id int64) (GetStorageTankAvailableVolumeRow, error)
	GetStorageTankByFacilityAndFuel(ctx context.Context, arg GetStorageTankByFacilityAndFuelParams) (FacilityStorageTank, error)
	GetTareReadingByTrip(ctx context.Context, tripID pgtype.Int8) (WeightBridgeReading, error)
	GetTotalCapacityByVehicle(ctx context.Context, vehicleID int64) (GetTotalCapacityByVehicleRow, error)
	// =============================================================================
	// SECTION 22 — TRIPS
	// =============================================================================
	GetTrip(ctx context.Context, id int64) (GetTripRow, error)
	GetTripByDO(ctx context.Context, doID int64) (GetTripByDORow, error)
	// =============================================================================
	// SECTION 28 — TRIP DOCUMENTS
	// =============================================================================
	GetTripDocument(ctx context.Context, id int64) (TripDocument, error)
	GetTripDocumentByType(ctx context.Context, arg GetTripDocumentByTypeParams) (TripDocument, error)
	// =============================================================================
	// SECTION 23 — TRIP EVENTS (APPEND-ONLY)
	// =============================================================================
	// Used by idempotency check before inserting from offline queue.
	GetTripEventByUUID(ctx context.Context, eventUuid uuid.UUID) (TripEvent, error)
	// =============================================================================
	// SECTION 27 — TRIP PHOTOS
	// =============================================================================
	GetTripPhoto(ctx context.Context, id int64) (TripPhoto, error)
	// Aggregate variance across all compartments for a trip (used by reconciliation engine).
	GetTripVarianceSummary(ctx context.Context, tripID int64) (GetTripVarianceSummaryRow, error)
	GetTripWithDetails(ctx context.Context, id int64) (GetTripWithDetailsRow, error)
	// =============================================================================
	// SECTION 12 — USERS
	// =============================================================================
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	GetUserByTelegramID(ctx context.Context, telegramUserID pgtype.Int8) (GetUserByTelegramIDRow, error)
	// Used during login — includes password_hash for bcrypt comparison.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPasswordHash(ctx context.Context, id int64) (string, error)
	// Returns token only if unused and not expired.
	GetValidTelegramLinkToken(ctx context.Context, token string) (GetValidTelegramLinkTokenRow, error)
	// =============================================================================
	// SECTION 9 — VEHICLES
	// =============================================================================
	GetVehicle(ctx context.Context, id int64) (GetVehicleRow, error)
	GetVehicleByPlate(ctx context.Context, plateNumber string) (GetVehicleByPlateRow, error)
	// =============================================================================
	// SECTION 21 — WEIGHT BRIDGE READINGS
	// =============================================================================
	GetWeightBridgeReading(ctx context.Context, id int64) (WeightBridgeReading, error)
	GrantRole(ctx context.Context, arg GrantRoleParams) (UserRoleGrant, error)
	// =============================================================================
	// SECTION 31 — AUDIT LOG (APPEND-ONLY)
	// =============================================================================
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error)
	// =============================================================================
	// SECTION 26 — GPS EVENTS (APPEND-ONLY, PARTITIONED)
	// =============================================================================
	// Partition routing is transparent; insert to parent table.
	InsertGPSEvent(ctx context.Context, arg InsertGPSEventParams) (InsertGPSEventRow, error)
	// =============================================================================
	// SECTION 30 — NOTIFICATION LOG (APPEND-ONLY)
	// =============================================================================
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (NotificationLog, error)
	// Append-only. event_uuid checked for duplicate before calling this.
	InsertTripEvent(ctx context.Context, arg InsertTripEventParams) (TripEvent, error)
	IssueSeal(ctx context.Context, arg IssueSealParams) (CompartmentSeal, error)
	LinkTelegramAccount(ctx context.Context, arg LinkTelegramAccountParams) error
	ListActiveFuelTypes(ctx context.Context) ([]FuelType, error)
	ListActiveTokensForUser(ctx context.Context, userID int64) ([]TelegramLinkToken, error)
	// All in-flight trips across all facilities (for dashboard map feed).
	ListActiveTrips(ctx context.Context) ([]ListActiveTripsRow, error)
	ListActiveTripsByDriverUserScope(ctx context.Context, id int64) ([]ListActiveTripsByDriverUserScopeRow, error)
	ListActiveTripsByFacility(ctx context.Context, originFacilityID int64) ([]Trip, error)
	ListActiveTripsByFacilityScope(ctx context.Context, originFacilityID int64) ([]ListActiveTripsByFacilityScopeRow, error)
	ListActiveTripsByRefineryScope(ctx context.Context, refineryID int64) ([]ListActiveTripsByRefineryScopeRow, error)
	ListActiveTripsByStationScope(ctx context.Context, destinationStationID pgtype.Int8) ([]ListActiveTripsByStationScopeRow, error)
	// Real-time dashboard map: latest GPS position per active trip via LATERAL join.
	ListActiveTripsWithLatestGPS(ctx context.Context) ([]ListActiveTripsWithLatestGPSRow, error)
	ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error)
	ListAllActiveDepots(ctx context.Context) ([]ListAllActiveDepotsRow, error)
	ListAllActiveFacilities(ctx context.Context) ([]ListAllActiveFacilitiesRow, error)
	ListAllActiveStations(ctx context.Context) ([]ListAllActiveStationsRow, error)
	ListAllActiveStationsByRefineryScope(ctx context.Context, refineryID int64) ([]ListAllActiveStationsByRefineryScopeRow, error)
	ListAllActiveStationsByStationScope(ctx context.Context, id int64) ([]ListAllActiveStationsByStationScopeRow, error)
	// Includes inactive compartments (admin view).
	ListAllCompartmentsByVehicle(ctx context.Context, vehicleID int64) ([]VehicleCompartment, error)
	ListAllOpenMaintenance(ctx context.Context) ([]ListAllOpenMaintenanceRow, error)
	ListAuditLogByAction(ctx context.Context, arg ListAuditLogByActionParams) ([]ListAuditLogByActionRow, error)
	ListAuditLogByEntity(ctx context.Context, arg ListAuditLogByEntityParams) ([]ListAuditLogByEntityRow, error)
	ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]AuditLog, error)
	// Available = on shift, valid SIM B2, no active trip.
	ListAvailableDriversForDispatch(ctx context.Context) ([]ListAvailableDriversForDispatchRow, error)
	ListCompartmentDeliveriesByTrip(ctx context.Context, tripID int64) ([]ListCompartmentDeliveriesByTripRow, error)
	ListCompartmentsByVehicle(ctx context.Context, vehicleID int64) ([]VehicleCompartment, error)
	ListCompartmentsByVehicleAndFuel(ctx context.Context, arg ListCompartmentsByVehicleAndFuelParams) ([]VehicleCompartment, error)
	ListDOItemsByDO(ctx context.Context, doID int64) ([]ListDOItemsByDORow, error)
	ListDOsByDriver(ctx context.Context, assignedDriverID pgtype.Int8) ([]DeliveryOrder, error)
	ListDOsByOriginFacility(ctx context.Context, originFacilityID int64) ([]DeliveryOrder, error)
	ListDOsByStatus(ctx context.Context, status DoStatusT) ([]ListDOsByStatusRow, error)
	ListDOsByVehicle(ctx context.Context, assignedVehicleID pgtype.Int8) ([]DeliveryOrder, error)
	// Approved DOs awaiting or having vehicle assignment, scoped to a facility.
	ListDOsForDispatchQueue(ctx context.Context, originFacilityID int64) ([]ListDOsForDispatchQueueRow, error)
	ListDepotsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListDepotsByFacilityRow, error)
	// =============================================================================
	// SECTION 29 — ROUTE DEVIATION EVENTS
	// =============================================================================
	ListDeviationsByTrip(ctx context.Context, tripID int64) ([]RouteDeviationEvent, error)
	// Primary dispatch query. Finds available trucks near a facility ordered by:
	// 1. Depot proximity to origin facility (home depot first)
	// 2. Distance from current GPS location to facility
	// 3. Least recently assigned (fairness)
	// Returns up to $2 candidates. Caller filters by required fuel type separately.
	ListDispatchCandidateVehicles(ctx context.Context, arg ListDispatchCandidateVehiclesParams) ([]ListDispatchCandidateVehiclesRow, error)
	// Supervisor view: all disputed compartment deliveries across all trips.
	ListDisputedDeliveries(ctx context.Context) ([]ListDisputedDeliveriesRow, error)
	ListDocumentsByTrip(ctx context.Context, tripID int64) ([]TripDocument, error)
	ListDriversByDepot(ctx context.Context, homeDepotID pgtype.Int8) ([]ListDriversByDepotRow, error)
	// 30-day advance warning window.
	ListDriversWithExpiringLicense(ctx context.Context) ([]ListDriversWithExpiringLicenseRow, error)
	// Refinery Admin escalation queue (company-wide).
	ListEscalatedApprovals(ctx context.Context) ([]ListEscalatedApprovalsRow, error)
	ListFacilitiesByRefinery(ctx context.Context, refineryID int64) ([]ListFacilitiesByRefineryRow, error)
	// =============================================================================
	// SECTION 16 — STATION FACILITY WHITELIST
	// =============================================================================
	ListFacilitiesForStation(ctx context.Context, stationID int64) ([]ListFacilitiesForStationRow, error)
	ListFuelTypes(ctx context.Context) ([]FuelType, error)
	ListFuelTypesByCategory(ctx context.Context, category FuelCategoryT) ([]FuelType, error)
	ListGPSEventsByTrip(ctx context.Context, tripID int64) ([]ListGPSEventsByTripRow, error)
	// Route reconstruction for a trip segment.
	ListGPSEventsByTripAndTimeRange(ctx context.Context, arg ListGPSEventsByTripAndTimeRangeParams) ([]ListGPSEventsByTripAndTimeRangeRow, error)
	ListGlobalSettings(ctx context.Context) ([]SystemSetting, error)
	ListLoadingBaysByFacility(ctx context.Context, facilityID int64) ([]FacilityLoadingBay, error)
	ListMaintenanceByVehicle(ctx context.Context, vehicleID int64) ([]VehicleMaintenanceRecord, error)
	ListMismatchedSealsByTrip(ctx context.Context, tripID int64) ([]CompartmentSeal, error)
	ListNotificationsByRecipient(ctx context.Context, arg ListNotificationsByRecipientParams) ([]NotificationLog, error)
	ListNotificationsByTrip(ctx context.Context, tripID pgtype.Int8) ([]NotificationLog, error)
	ListOpenMaintenanceByVehicle(ctx context.Context, vehicleID int64) ([]VehicleMaintenanceRecord, error)
	ListOverduePendingManualApprovals(ctx context.Context, hours int32) ([]ListOverduePendingManualApprovalsRow, error)
	// Facility manager approval queue. Scoped to a specific facility via vehicle's current depot.
	ListPendingManualApprovals(ctx context.Context, primaryFacilityID int64) ([]ListPendingManualApprovalsRow, error)
	// Combines both PENDING and ESCALATED readings needing action from this facility's managers.
	ListPendingWeightBridgeApprovalsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListPendingWeightBridgeApprovalsByFacilityRow, error)
	ListPhotosByTrip(ctx context.Context, tripID int64) ([]TripPhoto, error)
	ListPhotosByTripAndCompartment(ctx context.Context, arg ListPhotosByTripAndCompartmentParams) ([]TripPhoto, error)
	ListPhotosByTripAndEvent(ctx context.Context, arg ListPhotosByTripAndEventParams) ([]TripPhoto, error)
	ListQRCodesByStation(ctx context.Context, stationID int64) ([]StationQrCode, error)
	ListRefineries(ctx context.Context) ([]Refinery, error)
	ListRefineriesByRegion(ctx context.Context, regionCode string) ([]Refinery, error)
	ListRegions(ctx context.Context) ([]Region, error)
	// All auto-created return-to-facility trips (have parent_trip_id set).
	ListReturnTrips(ctx context.Context) ([]Trip, error)
	ListSealsByTrip(ctx context.Context, tripID int64) ([]ListSealsByTripRow, error)
	ListSettingsByFacility(ctx context.Context, facilityID pgtype.Int8) ([]SystemSetting, error)
	// Phase 3: auto-DO trigger source. Returns all under-threshold active tanks.
	ListStationTanksBelowReorderThreshold(ctx context.Context) ([]ListStationTanksBelowReorderThresholdRow, error)
	ListStationTanksByStation(ctx context.Context, stationID int64) ([]StationTank, error)
	ListStationsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListStationsByFacilityRow, error)
	ListStationsByRegion(ctx context.Context, regionCode string) ([]ListStationsByRegionRow, error)
	// Returns all stations where the facility is in the supply whitelist.
	ListStationsServedByFacility(ctx context.Context, facilityID int64) ([]ListStationsServedByFacilityRow, error)
	ListStorageTanksByFacility(ctx context.Context, facilityID int64) ([]FacilityStorageTank, error)
	ListTripDeliveredVolumeByFuel(ctx context.Context, tripID int64) ([]ListTripDeliveredVolumeByFuelRow, error)
	ListTripEventsByTrip(ctx context.Context, tripID int64) ([]TripEvent, error)
	ListTripEventsByTripAndType(ctx context.Context, arg ListTripEventsByTripAndTypeParams) ([]TripEvent, error)
	ListTripLoadedVolumeByFuel(ctx context.Context, tripID int64) ([]ListTripLoadedVolumeByFuelRow, error)
	ListTripsByDriver(ctx context.Context, arg ListTripsByDriverParams) ([]Trip, error)
	ListTripsByStatus(ctx context.Context, status TripStatusT) ([]Trip, error)
	ListTripsByVehicle(ctx context.Context, arg ListTripsByVehicleParams) ([]Trip, error)
	// Background worker: fetch deviations that have exceeded alert threshold and not yet notified.
	ListUnnotifiedDeviationsAboveThreshold(ctx context.Context, dollar_1 pgtype.Text) ([]ListUnnotifiedDeviationsAboveThresholdRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersWithCompanyRole(ctx context.Context, role UserRoleT) ([]ListUsersWithCompanyRoleRow, error)
	ListUsersWithRoleInScope(ctx context.Context, arg ListUsersWithRoleInScopeParams) ([]ListUsersWithRoleInScopeRow, error)
	ListVehiclesByDepot(ctx context.Context, currentDepotID pgtype.Int8) ([]ListVehiclesByDepotRow, error)
	ListVehiclesByStatus(ctx context.Context, status VehicleStatusT) ([]ListVehiclesByStatusRow, error)
	ListVehiclesByStatusAndDepot(ctx context.Context, arg ListVehiclesByStatusAndDepotParams) ([]ListVehiclesByStatusAndDepotRow, error)
	ListVehiclesByStatusAndFacility(ctx context.Context, arg ListVehiclesByStatusAndFacilityParams) ([]ListVehiclesByStatusAndFacilityRow, error)
	ListVehiclesByStatusAndRefinery(ctx context.Context, arg ListVehiclesByStatusAndRefineryParams) ([]ListVehiclesByStatusAndRefineryRow, error)
	// Used for 30-day advance expiry notification.
	ListVehiclesWithExpiringKeur(ctx context.Context) ([]ListVehiclesWithExpiringKeurRow, error)
	// Operations notice board: trucks needing attention in next 30 days.
	ListVehiclesWithMaintenanceOrExpiryDue(ctx context.Context) ([]ListVehiclesWithMaintenanceOrExpiryDueRow, error)
	ListWeightBridgeReadingsByTrip(ctx context.Context, tripID pgtype.Int8) ([]WeightBridgeReading, error)
	MarkDeviationTelegramNotified(ctx context.Context, id int64) error
	MarkVehicleLastAssigned(ctx context.Context, id int64) error
	RecordSealBreak(ctx context.Context, arg RecordSealBreakParams) (CompartmentSeal, error)
	RecordUserLogin(ctx context.Context, id int64) error
	RejectWeightBridgeReading(ctx context.Context, arg RejectWeightBridgeReadingParams) (WeightBridgeReading, error)
	// Release reservation (on DO cancellation or manual override).
	ReleaseStorageTankReservation(ctx context.Context, arg ReleaseStorageTankReservationParams) (FacilityStorageTank, error)
	RemoveFacilityFromStationWhitelist(ctx context.Context, arg RemoveFacilityFromStationWhitelistParams) error
	// Atomically reserve volume at DO approval. Fails if insufficient available.
	ReserveStorageTankVolume(ctx context.Context, arg ReserveStorageTankVolumeParams) (FacilityStorageTank, error)
	RevokeAllRolesForUser(ctx context.Context, userID int64) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	// Called by admin password reset flow before sending temp password via Telegram.
	SetForcePasswordChange(ctx context.Context, id int64) error
	SetTripArrived(ctx context.Context, id int64) (Trip, error)
	SetTripCompleted(ctx context.Context, id int64) (Trip, error)
	SetTripDeparted(ctx context.Context, id int64) (Trip, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (SetUserActiveRow, error)
	StartDriverShift(ctx context.Context, id int64) error
	UnlinkTelegramAccount(ctx context.Context, id int64) error
	UpdateCompartmentDeliveryStatus(ctx context.Context, arg UpdateCompartmentDeliveryStatusParams) (TripCompartmentDelivery, error)
	UpdateCompartmentFuelType(ctx context.Context, arg UpdateCompartmentFuelTypeParams) (VehicleCompartment, error)
	UpdateDOItemAllocatedVolume(ctx context.Context, arg UpdateDOItemAllocatedVolumeParams) (DeliveryOrderItem, error)
	UpdateDOStatus(ctx context.Context, arg UpdateDOStatusParams) (DeliveryOrder, error)
	UpdateDeliveredVolume(ctx context.Context, arg UpdateDeliveredVolumeParams) (TripCompartmentDelivery, error)
	UpdateDepot(ctx context.Context, arg UpdateDepotParams) (VehicleDepot, error)
	// Called when a deviation is resolved to record total duration.
	UpdateDeviationDuration(ctx context.Context, id int64) (RouteDeviationEvent, error)
	UpdateDipReading(ctx context.Context, arg UpdateDipReadingParams) (StationTank, error)
	UpdateDriverHomeDepot(ctx context.Context, arg UpdateDriverHomeDepotParams) error
	UpdateDriverLicense(ctx context.Context, arg UpdateDriverLicenseParams) (Driver, error)
	UpdateFacility(ctx context.Context, arg UpdateFacilityParams) (RefineryFacility, error)
	UpdateFacilityLocation(ctx context.Context, arg UpdateFacilityLocationParams) (RefineryFacility, error)
	UpdateFuelType(ctx context.Context, arg UpdateFuelTypeParams) (FuelType, error)
	UpdateLoadedVolume(ctx context.Context, arg UpdateLoadedVolumeParams) (TripCompartmentDelivery, error)
	UpdateLoadingBayFuelType(ctx context.Context, arg UpdateLoadingBayFuelTypeParams) (FacilityLoadingBay, error)
	UpdateRefinery(ctx context.Context, arg UpdateRefineryParams) (Refinery, error)
	UpdateStation(ctx context.Context, arg UpdateStationParams) (GasStation, error)
	UpdateStationTankReorderThreshold(ctx context.Context, arg UpdateStationTankReorderThresholdParams) (StationTank, error)
	// Manual correction. Caller must write to audit_log.
	UpdateStationTankVolume(ctx context.Context, arg UpdateStationTankVolumeParams) (StationTank, error)
	// Called by reconciliation engine after delivery is confirmed.
	UpdateStationTankVolumeAfterDelivery(ctx context.Context, arg UpdateStationTankVolumeAfterDeliveryParams) (StationTank, error)
	// Manual correction by SYSTEM_ADMIN (audited separately via audit_log).
	UpdateStorageTankVolume(ctx context.Context, arg UpdateStorageTankVolumeParams) (FacilityStorageTank, error)
	// Called if a document is regenerated (e.g., after variance resolution).
	UpdateTripDocumentKey(ctx context.Context, arg UpdateTripDocumentKeyParams) (TripDocument, error)
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVehicleDepot(ctx context.Context, arg UpdateVehicleDepotParams) error
	UpdateVehicleKeurDetails(ctx context.Context, arg UpdateVehicleKeurDetailsParams) (Vehicle, error)
	UpdateVehicleLocation(ctx context.Context, arg UpdateVehicleLocationParams) error
	UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (Vehicle, error)
	UpsertFacilitySetting(ctx context.Context, arg UpsertFacilitySettingParams) (SystemSetting, error)
	UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (SystemSetting, error)
	UseTelegramLinkToken(ctx context.Context, token string) (TelegramLinkToken, error)
	// Validates QR payload belongs to the expected facility and is active.
	ValidateLoadingBayQR(ctx context.Context, arg ValidateLoadingBayQRParams) (ValidateLoadingBayQRRow, error)
	VerifySeal(ctx context.Context, arg VerifySealParams) (CompartmentSeal, error)
}

var _ Querier = (*Queries)(nil)
