// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refinery_facilities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFacility = `-- name: CreateFacility :one
INSERT INTO refinery_facilities (
    code, refinery_id, name, location, is_primary, max_assignment_radius_km, address
) VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_MakePoint($4, $5), 4326),
    $6, $7, $8
)
RETURNING id, code, refinery_id, name, location, address, is_primary, max_assignment_radius_km, active, created_at, updated_at
`

type CreateFacilityParams struct {
	Code                  string         `json:"code"`
	RefineryID            int64          `json:"refinery_id"`
	Name                  string         `json:"name"`
	StMakepoint           interface{}    `json:"st_makepoint"`
	StMakepoint_2         interface{}    `json:"st_makepoint_2"`
	IsPrimary             bool           `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric `json:"max_assignment_radius_km"`
	Address               pgtype.Text    `json:"address"`
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (RefineryFacility, error) {
	row := q.db.QueryRow(ctx, createFacility,
		arg.Code,
		arg.RefineryID,
		arg.Name,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.IsPrimary,
		arg.MaxAssignmentRadiusKm,
		arg.Address,
	)
	var i RefineryFacility
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateFacility = `-- name: DeactivateFacility :exec
UPDATE refinery_facilities
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateFacility(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateFacility, id)
	return err
}

const getFacility = `-- name: GetFacility :one

SELECT
    rf.id, rf.code, rf.refinery_id, rf.name, rf.location, rf.address, rf.is_primary, rf.max_assignment_radius_km, rf.active, rf.created_at, rf.updated_at,
    ST_X(rf.location) AS longitude,
    ST_Y(rf.location) AS latitude
FROM refinery_facilities rf
WHERE rf.id = $1
`

type GetFacilityRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

// =============================================================================
// SECTION 5 — REFINERY FACILITIES
// =============================================================================
func (q *Queries) GetFacility(ctx context.Context, id int64) (GetFacilityRow, error) {
	row := q.db.QueryRow(ctx, getFacility, id)
	var i GetFacilityRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getFacilityByCode = `-- name: GetFacilityByCode :one
SELECT
    rf.id, rf.code, rf.refinery_id, rf.name, rf.location, rf.address, rf.is_primary, rf.max_assignment_radius_km, rf.active, rf.created_at, rf.updated_at,
    ST_X(rf.location) AS longitude,
    ST_Y(rf.location) AS latitude
FROM refinery_facilities rf
WHERE rf.code = $1
`

type GetFacilityByCodeRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) GetFacilityByCode(ctx context.Context, code string) (GetFacilityByCodeRow, error) {
	row := q.db.QueryRow(ctx, getFacilityByCode, code)
	var i GetFacilityByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getPrimaryFacilityByRefinery = `-- name: GetPrimaryFacilityByRefinery :one
SELECT
    rf.id, rf.code, rf.refinery_id, rf.name, rf.location, rf.address, rf.is_primary, rf.max_assignment_radius_km, rf.active, rf.created_at, rf.updated_at,
    ST_X(rf.location) AS longitude,
    ST_Y(rf.location) AS latitude
FROM refinery_facilities rf
WHERE rf.refinery_id = $1
  AND rf.is_primary = TRUE
  AND rf.active = TRUE
`

type GetPrimaryFacilityByRefineryRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) GetPrimaryFacilityByRefinery(ctx context.Context, refineryID int64) (GetPrimaryFacilityByRefineryRow, error) {
	row := q.db.QueryRow(ctx, getPrimaryFacilityByRefinery, refineryID)
	var i GetPrimaryFacilityByRefineryRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const listAllActiveFacilities = `-- name: ListAllActiveFacilities :many
SELECT
    rf.id, rf.code, rf.refinery_id, rf.name, rf.location, rf.address, rf.is_primary, rf.max_assignment_radius_km, rf.active, rf.created_at, rf.updated_at,
    r.code  AS refinery_code,
    r.name  AS refinery_name,
    ST_X(rf.location) AS longitude,
    ST_Y(rf.location) AS latitude
FROM refinery_facilities rf
JOIN refineries r ON r.id = rf.refinery_id
WHERE rf.active = TRUE
ORDER BY r.code, rf.is_primary DESC
`

type ListAllActiveFacilitiesRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RefineryCode          string             `json:"refinery_code"`
	RefineryName          string             `json:"refinery_name"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) ListAllActiveFacilities(ctx context.Context) ([]ListAllActiveFacilitiesRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveFacilitiesRow{}
	for rows.Next() {
		var i ListAllActiveFacilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RefineryID,
			&i.Name,
			&i.Location,
			&i.Address,
			&i.IsPrimary,
			&i.MaxAssignmentRadiusKm,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RefineryCode,
			&i.RefineryName,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilitiesByRefinery = `-- name: ListFacilitiesByRefinery :many
SELECT
    rf.id, rf.code, rf.refinery_id, rf.name, rf.location, rf.address, rf.is_primary, rf.max_assignment_radius_km, rf.active, rf.created_at, rf.updated_at,
    ST_X(rf.location) AS longitude,
    ST_Y(rf.location) AS latitude
FROM refinery_facilities rf
WHERE rf.refinery_id = $1
  AND rf.active = TRUE
ORDER BY rf.is_primary DESC, rf.name
`

type ListFacilitiesByRefineryRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	RefineryID            int64              `json:"refinery_id"`
	Name                  string             `json:"name"`
	Location              interface{}        `json:"location"`
	Address               pgtype.Text        `json:"address"`
	IsPrimary             bool               `json:"is_primary"`
	MaxAssignmentRadiusKm pgtype.Numeric     `json:"max_assignment_radius_km"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) ListFacilitiesByRefinery(ctx context.Context, refineryID int64) ([]ListFacilitiesByRefineryRow, error) {
	rows, err := q.db.Query(ctx, listFacilitiesByRefinery, refineryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilitiesByRefineryRow{}
	for rows.Next() {
		var i ListFacilitiesByRefineryRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RefineryID,
			&i.Name,
			&i.Location,
			&i.Address,
			&i.IsPrimary,
			&i.MaxAssignmentRadiusKm,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFacility = `-- name: UpdateFacility :one
UPDATE refinery_facilities
SET
    name                     = $2,
    address                  = $3,
    max_assignment_radius_km = $4,
    updated_at               = NOW()
WHERE id = $1
RETURNING id, code, refinery_id, name, location, address, is_primary, max_assignment_radius_km, active, created_at, updated_at
`

type UpdateFacilityParams struct {
	ID                    int64          `json:"id"`
	Name                  string         `json:"name"`
	Address               pgtype.Text    `json:"address"`
	MaxAssignmentRadiusKm pgtype.Numeric `json:"max_assignment_radius_km"`
}

func (q *Queries) UpdateFacility(ctx context.Context, arg UpdateFacilityParams) (RefineryFacility, error) {
	row := q.db.QueryRow(ctx, updateFacility,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.MaxAssignmentRadiusKm,
	)
	var i RefineryFacility
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFacilityLocation = `-- name: UpdateFacilityLocation :one
UPDATE refinery_facilities
SET
    location   = ST_SetSRID(ST_MakePoint($2, $3), 4326),
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, refinery_id, name, location, address, is_primary, max_assignment_radius_km, active, created_at, updated_at
`

type UpdateFacilityLocationParams struct {
	ID            int64       `json:"id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) UpdateFacilityLocation(ctx context.Context, arg UpdateFacilityLocationParams) (RefineryFacility, error) {
	row := q.db.QueryRow(ctx, updateFacilityLocation, arg.ID, arg.StMakepoint, arg.StMakepoint_2)
	var i RefineryFacility
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RefineryID,
		&i.Name,
		&i.Location,
		&i.Address,
		&i.IsPrimary,
		&i.MaxAssignmentRadiusKm,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
