// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refineries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefinery = `-- name: CreateRefinery :one
INSERT INTO refineries (code, name, region_code, commissioned_year)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, region_code, commissioned_year, active, created_at, updated_at
`

type CreateRefineryParams struct {
	Code             string      `json:"code"`
	Name             string      `json:"name"`
	RegionCode       string      `json:"region_code"`
	CommissionedYear pgtype.Int2 `json:"commissioned_year"`
}

func (q *Queries) CreateRefinery(ctx context.Context, arg CreateRefineryParams) (Refinery, error) {
	row := q.db.QueryRow(ctx, createRefinery,
		arg.Code,
		arg.Name,
		arg.RegionCode,
		arg.CommissionedYear,
	)
	var i Refinery
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RegionCode,
		&i.CommissionedYear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefinery = `-- name: GetRefinery :one

SELECT id, code, name, region_code, commissioned_year, active, created_at, updated_at
FROM refineries
WHERE id = $1
`

// =============================================================================
// SECTION 4 — REFINERIES
// =============================================================================
func (q *Queries) GetRefinery(ctx context.Context, id int64) (Refinery, error) {
	row := q.db.QueryRow(ctx, getRefinery, id)
	var i Refinery
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RegionCode,
		&i.CommissionedYear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefineryByCode = `-- name: GetRefineryByCode :one
SELECT id, code, name, region_code, commissioned_year, active, created_at, updated_at
FROM refineries
WHERE code = $1
`

func (q *Queries) GetRefineryByCode(ctx context.Context, code string) (Refinery, error) {
	row := q.db.QueryRow(ctx, getRefineryByCode, code)
	var i Refinery
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RegionCode,
		&i.CommissionedYear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRefineries = `-- name: ListRefineries :many
SELECT id, code, name, region_code, commissioned_year, active, created_at, updated_at
FROM refineries
WHERE active = TRUE
ORDER BY code
`

func (q *Queries) ListRefineries(ctx context.Context) ([]Refinery, error) {
	rows, err := q.db.Query(ctx, listRefineries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refinery{}
	for rows.Next() {
		var i Refinery
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.RegionCode,
			&i.CommissionedYear,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefineriesByRegion = `-- name: ListRefineriesByRegion :many
SELECT id, code, name, region_code, commissioned_year, active, created_at, updated_at
FROM refineries
WHERE region_code = $1
  AND active = TRUE
ORDER BY code
`

func (q *Queries) ListRefineriesByRegion(ctx context.Context, regionCode string) ([]Refinery, error) {
	rows, err := q.db.Query(ctx, listRefineriesByRegion, regionCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Refinery{}
	for rows.Next() {
		var i Refinery
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.RegionCode,
			&i.CommissionedYear,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefinery = `-- name: UpdateRefinery :one
UPDATE refineries
SET
    name               = $2,
    region_code        = $3,
    commissioned_year  = $4,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, code, name, region_code, commissioned_year, active, created_at, updated_at
`

type UpdateRefineryParams struct {
	ID               int64       `json:"id"`
	Name             string      `json:"name"`
	RegionCode       string      `json:"region_code"`
	CommissionedYear pgtype.Int2 `json:"commissioned_year"`
}

func (q *Queries) UpdateRefinery(ctx context.Context, arg UpdateRefineryParams) (Refinery, error) {
	row := q.db.QueryRow(ctx, updateRefinery,
		arg.ID,
		arg.Name,
		arg.RegionCode,
		arg.CommissionedYear,
	)
	var i Refinery
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RegionCode,
		&i.CommissionedYear,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
