// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regions.sql

package db

import (
	"context"
)

const getRegion = `-- name: GetRegion :one

SELECT code, name, created_at
FROM regions
WHERE code = $1
`

// =============================================================================
// SECTION 1 — REGIONS
// =============================================================================
func (q *Queries) GetRegion(ctx context.Context, code string) (Region, error) {
	row := q.db.QueryRow(ctx, getRegion, code)
	var i Region
	err := row.Scan(&i.Code, &i.Name, &i.CreatedAt)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT code, name, created_at
FROM regions
ORDER BY name
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.Query(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Region{}
	for rows.Next() {
		var i Region
		if err := rows.Scan(&i.Code, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
