// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getCompanyWideDashboardSummary = `-- name: GetCompanyWideDashboardSummary :many
SELECT
    rf.id                                          AS facility_id,
    rf.code                                        AS facility_code,
    rf.name                                        AS facility_name,
    r.code                                         AS refinery_code,
    COUNT(DISTINCT t.id) FILTER (
        WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
    )                                              AS active_trips,
    COUNT(DISTINCT v.id) FILTER (
        WHERE v.status = 'AVAILABLE' AND v.active = TRUE
    )                                              AS available_vehicles
FROM refinery_facilities rf
JOIN refineries           r  ON r.id  = rf.refinery_id
LEFT JOIN vehicle_depots  vd ON vd.primary_facility_id = rf.id
LEFT JOIN vehicles         v ON v.current_depot_id = vd.id
LEFT JOIN trips            t ON t.origin_facility_id = rf.id
WHERE rf.active = TRUE
GROUP BY rf.id, rf.code, rf.name, r.code
ORDER BY r.code, rf.is_primary DESC
`

type GetCompanyWideDashboardSummaryRow struct {
	FacilityID        int64  `json:"facility_id"`
	FacilityCode      string `json:"facility_code"`
	FacilityName      string `json:"facility_name"`
	RefineryCode      string `json:"refinery_code"`
	ActiveTrips       int64  `json:"active_trips"`
	AvailableVehicles int64  `json:"available_vehicles"`
}

// Multi-refinery ops view: one row per facility.
func (q *Queries) GetCompanyWideDashboardSummary(ctx context.Context) ([]GetCompanyWideDashboardSummaryRow, error) {
	rows, err := q.db.Query(ctx, getCompanyWideDashboardSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompanyWideDashboardSummaryRow{}
	for rows.Next() {
		var i GetCompanyWideDashboardSummaryRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.FacilityCode,
			&i.FacilityName,
			&i.RefineryCode,
			&i.ActiveTrips,
			&i.AvailableVehicles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDriverComplianceSummary = `-- name: GetDriverComplianceSummary :one
SELECT
    d.id                   AS driver_id,
    u.full_name,
    COUNT(DISTINCT t.id)   AS total_trips,
    COUNT(DISTINCT t.id) FILTER (
        WHERE EXISTS (
            SELECT 1 FROM trip_compartment_deliveries tcd2
            WHERE tcd2.trip_id = t.id AND tcd2.delivery_status = 'DISPUTED'
        )
    )                      AS disputed_trips,
    COUNT(DISTINCT rde.trip_id) AS trips_with_deviation,
    COUNT(DISTINCT cs.trip_id)  AS trips_with_seal_mismatch,
    ROUND(
        (1 - (COUNT(DISTINCT t.id) FILTER (
            WHERE EXISTS (
                SELECT 1 FROM trip_compartment_deliveries tcd2
                WHERE tcd2.trip_id = t.id AND tcd2.delivery_status = 'DISPUTED'
            )
        ))::NUMERIC / NULLIF(COUNT(DISTINCT t.id), 0)) * 100, 1
    )                      AS compliance_score_pct
FROM drivers d
JOIN users   u ON u.id = d.user_id
LEFT JOIN trips t ON t.driver_id = d.id AND t.status = 'CLOSED'
    AND t.completed_at >= $2
    AND t.completed_at <  $3
LEFT JOIN route_deviation_events rde ON rde.trip_id = t.id
LEFT JOIN compartment_seals cs ON cs.trip_id = t.id
    AND cs.verification_status IN ('MISMATCHED','BROKEN','MISSING')
WHERE d.id = $1
GROUP BY d.id, u.full_name
`

type GetDriverComplianceSummaryParams struct {
	ID            int64              `json:"id"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CompletedAt_2 pgtype.Timestamptz `json:"completed_at_2"`
}

type GetDriverComplianceSummaryRow struct {
	DriverID              int64           `json:"driver_id"`
	FullName              string          `json:"full_name"`
	TotalTrips            int64           `json:"total_trips"`
	DisputedTrips         int64           `json:"disputed_trips"`
	TripsWithDeviation    int64           `json:"trips_with_deviation"`
	TripsWithSealMismatch int64           `json:"trips_with_seal_mismatch"`
	ComplianceScorePct    decimal.Decimal `json:"compliance_score_pct"`
}

// Compliance scoring: variance, deviation, and seal mismatch history per driver.
func (q *Queries) GetDriverComplianceSummary(ctx context.Context, arg GetDriverComplianceSummaryParams) (GetDriverComplianceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDriverComplianceSummary, arg.ID, arg.CompletedAt, arg.CompletedAt_2)
	var i GetDriverComplianceSummaryRow
	err := row.Scan(
		&i.DriverID,
		&i.FullName,
		&i.TotalTrips,
		&i.DisputedTrips,
		&i.TripsWithDeviation,
		&i.TripsWithSealMismatch,
		&i.ComplianceScorePct,
	)
	return i, err
}

const getFacilityDashboardSummary = `-- name: GetFacilityDashboardSummary :one

SELECT
    rf.id                                          AS facility_id,
    rf.name                                        AS facility_name,
    COUNT(DISTINCT t.id) FILTER (
        WHERE t.status NOT IN ('CLOSED','CANCELLED','RECONCILED')
    )                                              AS active_trips,
    COUNT(DISTINCT v.id) FILTER (
        WHERE v.status = 'AVAILABLE'
    )                                              AS available_vehicles,
    COUNT(DISTINCT v.id) FILTER (
        WHERE v.status = 'UNDER_MAINTENANCE'
    )                                              AS vehicles_in_maintenance
FROM refinery_facilities rf
LEFT JOIN vehicle_depots  vd ON vd.primary_facility_id = rf.id
LEFT JOIN vehicles         v ON v.current_depot_id     = vd.id AND v.active = TRUE
LEFT JOIN trips            t ON t.origin_facility_id   = rf.id
WHERE rf.id = $1
GROUP BY rf.id, rf.name
`

type GetFacilityDashboardSummaryRow struct {
	FacilityID            int64  `json:"facility_id"`
	FacilityName          string `json:"facility_name"`
	ActiveTrips           int64  `json:"active_trips"`
	AvailableVehicles     int64  `json:"available_vehicles"`
	VehiclesInMaintenance int64  `json:"vehicles_in_maintenance"`
}

// =============================================================================
// SECTION 33 — REPORTING & CROSS-TABLE QUERIES
// =============================================================================
// Central ops dashboard: inventory + active trip count for one facility.
func (q *Queries) GetFacilityDashboardSummary(ctx context.Context, id int64) (GetFacilityDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFacilityDashboardSummary, id)
	var i GetFacilityDashboardSummaryRow
	err := row.Scan(
		&i.FacilityID,
		&i.FacilityName,
		&i.ActiveTrips,
		&i.AvailableVehicles,
		&i.VehiclesInMaintenance,
	)
	return i, err
}

const getMonthlyDeliveryStatsByFacility = `-- name: GetMonthlyDeliveryStatsByFacility :many
SELECT
    DATE_TRUNC('month', t.completed_at) AS month,
    tcd.fuel_type_code,
    COUNT(DISTINCT t.id)                AS trip_count,
    SUM(tcd.loaded_volume_l)            AS total_loaded_l,
    SUM(tcd.delivered_volume_l)         AS total_delivered_l,
    SUM(tcd.variance_l)                 AS total_variance_l,
    ROUND(
        (SUM(tcd.variance_l) / NULLIF(SUM(tcd.loaded_volume_l), 0) * 100)::NUMERIC, 4
    )                                   AS overall_variance_pct
FROM trips t
JOIN trip_compartment_deliveries tcd ON tcd.trip_id = t.id
WHERE t.origin_facility_id = $1
  AND t.status             = 'CLOSED'
  AND t.completed_at      >= $2
  AND t.completed_at      <  $3
GROUP BY DATE_TRUNC('month', t.completed_at), tcd.fuel_type_code
ORDER BY month DESC, tcd.fuel_type_code
`

type GetMonthlyDeliveryStatsByFacilityParams struct {
	OriginFacilityID int64              `json:"origin_facility_id"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CompletedAt_2    pgtype.Timestamptz `json:"completed_at_2"`
}

type GetMonthlyDeliveryStatsByFacilityRow struct {
	Month              pgtype.Interval `json:"month"`
	FuelTypeCode       string          `json:"fuel_type_code"`
	TripCount          int64           `json:"trip_count"`
	TotalLoadedL       int64           `json:"total_loaded_l"`
	TotalDeliveredL    int64           `json:"total_delivered_l"`
	TotalVarianceL     int64           `json:"total_variance_l"`
	OverallVariancePct decimal.Decimal `json:"overall_variance_pct"`
}

// Reporting: delivered volume by fuel type per facility per month.
func (q *Queries) GetMonthlyDeliveryStatsByFacility(ctx context.Context, arg GetMonthlyDeliveryStatsByFacilityParams) ([]GetMonthlyDeliveryStatsByFacilityRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyDeliveryStatsByFacility, arg.OriginFacilityID, arg.CompletedAt, arg.CompletedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyDeliveryStatsByFacilityRow{}
	for rows.Next() {
		var i GetMonthlyDeliveryStatsByFacilityRow
		if err := rows.Scan(
			&i.Month,
			&i.FuelTypeCode,
			&i.TripCount,
			&i.TotalLoadedL,
			&i.TotalDeliveredL,
			&i.TotalVarianceL,
			&i.OverallVariancePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStationInventorySnapshot = `-- name: GetStationInventorySnapshot :many
SELECT
    st.id, st.station_id, st.tank_code, st.fuel_type_code, st.capacity_l, st.current_volume_l, st.reorder_threshold_l, st.last_dip_reading_l, st.last_dip_at, st.active, st.last_updated_at, st.created_at,
    ft.name                  AS fuel_name,
    ft.category              AS fuel_category,
    ROUND(
        (st.current_volume_l / NULLIF(st.capacity_l, 0) * 100)::NUMERIC, 1
    )                        AS fill_pct,
    (st.current_volume_l <= st.reorder_threshold_l) AS needs_reorder
FROM station_tanks st
JOIN fuel_types    ft ON ft.code = st.fuel_type_code
WHERE st.station_id = $1
  AND st.active     = TRUE
ORDER BY ft.category, ft.ron_cn
`

type GetStationInventorySnapshotRow struct {
	ID                int64              `json:"id"`
	StationID         int64              `json:"station_id"`
	TankCode          string             `json:"tank_code"`
	FuelTypeCode      string             `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric     `json:"capacity_l"`
	CurrentVolumeL    pgtype.Numeric     `json:"current_volume_l"`
	ReorderThresholdL pgtype.Numeric     `json:"reorder_threshold_l"`
	LastDipReadingL   pgtype.Numeric     `json:"last_dip_reading_l"`
	LastDipAt         pgtype.Timestamptz `json:"last_dip_at"`
	Active            bool               `json:"active"`
	LastUpdatedAt     pgtype.Timestamptz `json:"last_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	FuelName          string             `json:"fuel_name"`
	FuelCategory      FuelCategoryT      `json:"fuel_category"`
	FillPct           decimal.Decimal    `json:"fill_pct"`
	NeedsReorder      bool               `json:"needs_reorder"`
}

// Full inventory snapshot for a station (all active tanks).
func (q *Queries) GetStationInventorySnapshot(ctx context.Context, stationID int64) ([]GetStationInventorySnapshotRow, error) {
	rows, err := q.db.Query(ctx, getStationInventorySnapshot, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStationInventorySnapshotRow{}
	for rows.Next() {
		var i GetStationInventorySnapshotRow
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.TankCode,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.CurrentVolumeL,
			&i.ReorderThresholdL,
			&i.LastDipReadingL,
			&i.LastDipAt,
			&i.Active,
			&i.LastUpdatedAt,
			&i.CreatedAt,
			&i.FuelName,
			&i.FuelCategory,
			&i.FillPct,
			&i.NeedsReorder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWeightBridgeApprovalsByFacility = `-- name: ListPendingWeightBridgeApprovalsByFacility :many
SELECT
    wbr.id, wbr.trip_id, wbr.vehicle_id, wbr.reading_type, wbr.weight_kg, wbr.method, wbr.ambient_temp_celsius, wbr.recorded_by, wbr.approval_status, wbr.approved_by, wbr.approved_at, wbr.escalated_at, wbr.escalated_to, wbr.notes, wbr.created_at,
    v.plate_number,
    uro.full_name  AS recorded_by_name,
    t.id           AS trip_id,
    dor.do_number,
    CASE
        WHEN wbr.approval_status = 'PENDING'   THEN 'FACILITY_MANAGER'
        WHEN wbr.approval_status = 'ESCALATED' THEN 'REFINERY_ADMIN'
        ELSE wbr.approval_status::TEXT
    END            AS required_approver_role
FROM weight_bridge_readings wbr
JOIN vehicles v  ON v.id  = wbr.vehicle_id
JOIN users    uro ON uro.id = wbr.recorded_by
LEFT JOIN trips t  ON t.id = wbr.trip_id
LEFT JOIN delivery_orders dor ON dor.id = t.do_id
WHERE wbr.method NOT IN ('WEIGHT_BRIDGE')
  AND wbr.approval_status IN ('PENDING', 'ESCALATED')
  AND v.current_depot_id IN (
        SELECT id FROM vehicle_depots WHERE primary_facility_id = $1
      )
ORDER BY wbr.created_at ASC
`

type ListPendingWeightBridgeApprovalsByFacilityRow struct {
	ID                   int64              `json:"id"`
	TripID               pgtype.Int8        `json:"trip_id"`
	VehicleID            int64              `json:"vehicle_id"`
	ReadingType          string             `json:"reading_type"`
	WeightKg             pgtype.Numeric     `json:"weight_kg"`
	Method               MeasurementMethodT `json:"method"`
	AmbientTempCelsius   pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy           int64              `json:"recorded_by"`
	ApprovalStatus       ApprovalStatusT    `json:"approval_status"`
	ApprovedBy           pgtype.Int8        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	EscalatedAt          pgtype.Timestamptz `json:"escalated_at"`
	EscalatedTo          pgtype.Int8        `json:"escalated_to"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	PlateNumber          string             `json:"plate_number"`
	RecordedByName       string             `json:"recorded_by_name"`
	TripID_2             pgtype.Int8        `json:"trip_id_2"`
	DoNumber             pgtype.Text        `json:"do_number"`
	RequiredApproverRole string             `json:"required_approver_role"`
}

// Combines both PENDING and ESCALATED readings needing action from this facility's managers.
func (q *Queries) ListPendingWeightBridgeApprovalsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListPendingWeightBridgeApprovalsByFacilityRow, error) {
	rows, err := q.db.Query(ctx, listPendingWeightBridgeApprovalsByFacility, primaryFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingWeightBridgeApprovalsByFacilityRow{}
	for rows.Next() {
		var i ListPendingWeightBridgeApprovalsByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VehicleID,
			&i.ReadingType,
			&i.WeightKg,
			&i.Method,
			&i.AmbientTempCelsius,
			&i.RecordedBy,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.Notes,
			&i.CreatedAt,
			&i.PlateNumber,
			&i.RecordedByName,
			&i.TripID_2,
			&i.DoNumber,
			&i.RequiredApproverRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesWithMaintenanceOrExpiryDue = `-- name: ListVehiclesWithMaintenanceOrExpiryDue :many
SELECT
    v.id,
    v.plate_number,
    v.status,
    v.keur_expiry,
    v.next_inspection_due,
    vd.name AS depot_name,
    rf.code AS facility_code,
    CASE
        WHEN v.status = 'UNDER_MAINTENANCE'                                       THEN 'UNDER_MAINTENANCE'
        WHEN v.keur_expiry       <= (CURRENT_DATE + INTERVAL '30 days')           THEN 'KEUR_EXPIRING'
        WHEN v.next_inspection_due <= (CURRENT_DATE + INTERVAL '30 days')         THEN 'INSPECTION_DUE'
        ELSE 'OK'
    END AS notice_type
FROM vehicles v
JOIN vehicle_depots      vd ON vd.id = v.current_depot_id
JOIN refinery_facilities rf ON rf.id = vd.primary_facility_id
WHERE v.active = TRUE
  AND (
        v.status = 'UNDER_MAINTENANCE'
        OR v.keur_expiry       <= (CURRENT_DATE + INTERVAL '30 days')
        OR v.next_inspection_due <= (CURRENT_DATE + INTERVAL '30 days')
      )
ORDER BY rf.code, vd.name, v.keur_expiry ASC NULLS LAST
`

type ListVehiclesWithMaintenanceOrExpiryDueRow struct {
	ID                int64          `json:"id"`
	PlateNumber       string         `json:"plate_number"`
	Status            VehicleStatusT `json:"status"`
	KeurExpiry        pgtype.Date    `json:"keur_expiry"`
	NextInspectionDue pgtype.Date    `json:"next_inspection_due"`
	DepotName         string         `json:"depot_name"`
	FacilityCode      string         `json:"facility_code"`
	NoticeType        string         `json:"notice_type"`
}

// Operations notice board: trucks needing attention in next 30 days.
func (q *Queries) ListVehiclesWithMaintenanceOrExpiryDue(ctx context.Context) ([]ListVehiclesWithMaintenanceOrExpiryDueRow, error) {
	rows, err := q.db.Query(ctx, listVehiclesWithMaintenanceOrExpiryDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesWithMaintenanceOrExpiryDueRow{}
	for rows.Next() {
		var i ListVehiclesWithMaintenanceOrExpiryDueRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.Status,
			&i.KeurExpiry,
			&i.NextInspectionDue,
			&i.DepotName,
			&i.FacilityCode,
			&i.NoticeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
