// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_deviation_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countTripDeviations = `-- name: CountTripDeviations :one
SELECT COUNT(*)::INT AS deviation_count
FROM route_deviation_events
WHERE trip_id = $1
`

// Determines escalation tier (1 = log, 2 = warn, >2 = Telegram alert).
func (q *Queries) CountTripDeviations(ctx context.Context, tripID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTripDeviations, tripID)
	var deviation_count int32
	err := row.Scan(&deviation_count)
	return deviation_count, err
}

const createDeviationEvent = `-- name: CreateDeviationEvent :one
INSERT INTO route_deviation_events (
    trip_id, detected_at, deviation_meters, occurrence_count
) VALUES (
    $1, NOW(), $2, $3
)
RETURNING id, trip_id, detected_at, duration_seconds, deviation_meters, occurrence_count, telegram_notified, telegram_notified_at, resolved_at, notes
`

type CreateDeviationEventParams struct {
	TripID          int64          `json:"trip_id"`
	DeviationMeters pgtype.Numeric `json:"deviation_meters"`
	OccurrenceCount int16          `json:"occurrence_count"`
}

func (q *Queries) CreateDeviationEvent(ctx context.Context, arg CreateDeviationEventParams) (RouteDeviationEvent, error) {
	row := q.db.QueryRow(ctx, createDeviationEvent, arg.TripID, arg.DeviationMeters, arg.OccurrenceCount)
	var i RouteDeviationEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DetectedAt,
		&i.DurationSeconds,
		&i.DeviationMeters,
		&i.OccurrenceCount,
		&i.TelegramNotified,
		&i.TelegramNotifiedAt,
		&i.ResolvedAt,
		&i.Notes,
	)
	return i, err
}

const getOpenDeviationByTrip = `-- name: GetOpenDeviationByTrip :one
SELECT id, trip_id, detected_at, duration_seconds, deviation_meters, occurrence_count, telegram_notified, telegram_notified_at, resolved_at, notes
FROM route_deviation_events
WHERE trip_id    = $1
  AND resolved_at IS NULL
ORDER BY detected_at DESC
LIMIT 1
`

// Returns the most recent unresolved deviation (for cooldown state machine).
func (q *Queries) GetOpenDeviationByTrip(ctx context.Context, tripID int64) (RouteDeviationEvent, error) {
	row := q.db.QueryRow(ctx, getOpenDeviationByTrip, tripID)
	var i RouteDeviationEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DetectedAt,
		&i.DurationSeconds,
		&i.DeviationMeters,
		&i.OccurrenceCount,
		&i.TelegramNotified,
		&i.TelegramNotifiedAt,
		&i.ResolvedAt,
		&i.Notes,
	)
	return i, err
}

const listActiveTripsOffRoute = `-- name: ListActiveTripsOffRoute :many
SELECT
    t.id               AS trip_id,
    t.origin_facility_id,
    t.driver_id,
    t.vehicle_id,
    ge.event_timestamp AS last_gps_at,
    ROUND(
        ST_Distance(
            t.route_polyline::geography,
            ST_SetSRID(ST_MakePoint(ge.longitude, ge.latitude), 4326)::geography
        )::NUMERIC,
        2
    )                  AS deviation_meters
FROM trips t
JOIN LATERAL (
    SELECT latitude, longitude, event_timestamp
    FROM gps_events
    WHERE trip_id = t.id
    ORDER BY event_timestamp DESC
    LIMIT 1
) ge ON TRUE
WHERE t.status IN ('IN_TRANSIT', 'ARRIVED', 'UNLOADING')
  AND t.route_polyline IS NOT NULL
`

type ListActiveTripsOffRouteRow struct {
	TripID           int64              `json:"trip_id"`
	OriginFacilityID int64              `json:"origin_facility_id"`
	DriverID         int64              `json:"driver_id"`
	VehicleID        int64              `json:"vehicle_id"`
	LastGpsAt        pgtype.Timestamptz `json:"last_gps_at"`
	DeviationMeters  decimal.Decimal    `json:"deviation_meters"`
}

func (q *Queries) ListActiveTripsOffRoute(ctx context.Context) ([]ListActiveTripsOffRouteRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsOffRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsOffRouteRow{}
	for rows.Next() {
		var i ListActiveTripsOffRouteRow
		if err := rows.Scan(
			&i.TripID,
			&i.OriginFacilityID,
			&i.DriverID,
			&i.VehicleID,
			&i.LastGpsAt,
			&i.DeviationMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviationsByTrip = `-- name: ListDeviationsByTrip :many

SELECT id, trip_id, detected_at, duration_seconds, deviation_meters, occurrence_count, telegram_notified, telegram_notified_at, resolved_at, notes
FROM route_deviation_events
WHERE trip_id = $1
ORDER BY detected_at ASC
`

// =============================================================================
// SECTION 29 — ROUTE DEVIATION EVENTS
// =============================================================================
func (q *Queries) ListDeviationsByTrip(ctx context.Context, tripID int64) ([]RouteDeviationEvent, error) {
	rows, err := q.db.Query(ctx, listDeviationsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouteDeviationEvent{}
	for rows.Next() {
		var i RouteDeviationEvent
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DetectedAt,
			&i.DurationSeconds,
			&i.DeviationMeters,
			&i.OccurrenceCount,
			&i.TelegramNotified,
			&i.TelegramNotifiedAt,
			&i.ResolvedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotifiedDeviationsAboveThreshold = `-- name: ListUnnotifiedDeviationsAboveThreshold :many
SELECT rde.id, rde.trip_id, rde.detected_at, rde.duration_seconds, rde.deviation_meters, rde.occurrence_count, rde.telegram_notified, rde.telegram_notified_at, rde.resolved_at, rde.notes, t.driver_id, t.vehicle_id
FROM route_deviation_events rde
JOIN trips t ON t.id = rde.trip_id
WHERE rde.telegram_notified = FALSE
  AND rde.resolved_at IS NULL
  AND rde.detected_at <= (NOW() - ($1 || ' minutes')::INTERVAL)
ORDER BY rde.detected_at ASC
`

type ListUnnotifiedDeviationsAboveThresholdRow struct {
	ID                 int64              `json:"id"`
	TripID             int64              `json:"trip_id"`
	DetectedAt         pgtype.Timestamptz `json:"detected_at"`
	DurationSeconds    pgtype.Int4        `json:"duration_seconds"`
	DeviationMeters    pgtype.Numeric     `json:"deviation_meters"`
	OccurrenceCount    int16              `json:"occurrence_count"`
	TelegramNotified   bool               `json:"telegram_notified"`
	TelegramNotifiedAt pgtype.Timestamptz `json:"telegram_notified_at"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
	Notes              pgtype.Text        `json:"notes"`
	DriverID           int64              `json:"driver_id"`
	VehicleID          int64              `json:"vehicle_id"`
}

// Background worker: fetch deviations that have exceeded alert threshold and not yet notified.
func (q *Queries) ListUnnotifiedDeviationsAboveThreshold(ctx context.Context, dollar_1 pgtype.Text) ([]ListUnnotifiedDeviationsAboveThresholdRow, error) {
	rows, err := q.db.Query(ctx, listUnnotifiedDeviationsAboveThreshold, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnnotifiedDeviationsAboveThresholdRow{}
	for rows.Next() {
		var i ListUnnotifiedDeviationsAboveThresholdRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DetectedAt,
			&i.DurationSeconds,
			&i.DeviationMeters,
			&i.OccurrenceCount,
			&i.TelegramNotified,
			&i.TelegramNotifiedAt,
			&i.ResolvedAt,
			&i.Notes,
			&i.DriverID,
			&i.VehicleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviationTelegramNotified = `-- name: MarkDeviationTelegramNotified :exec
UPDATE route_deviation_events
SET
    telegram_notified    = TRUE,
    telegram_notified_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDeviationTelegramNotified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDeviationTelegramNotified, id)
	return err
}

const updateDeviationDuration = `-- name: UpdateDeviationDuration :one
UPDATE route_deviation_events
SET
    duration_seconds = EXTRACT(EPOCH FROM (NOW() - detected_at))::INT,
    resolved_at      = NOW()
WHERE id = $1
RETURNING id, trip_id, detected_at, duration_seconds, deviation_meters, occurrence_count, telegram_notified, telegram_notified_at, resolved_at, notes
`

// Called when a deviation is resolved to record total duration.
func (q *Queries) UpdateDeviationDuration(ctx context.Context, id int64) (RouteDeviationEvent, error) {
	row := q.db.QueryRow(ctx, updateDeviationDuration, id)
	var i RouteDeviationEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DetectedAt,
		&i.DurationSeconds,
		&i.DeviationMeters,
		&i.OccurrenceCount,
		&i.TelegramNotified,
		&i.TelegramNotifiedAt,
		&i.ResolvedAt,
		&i.Notes,
	)
	return i, err
}
