// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: station_tanks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createStationTank = `-- name: CreateStationTank :one
INSERT INTO station_tanks (
    station_id, tank_code, fuel_type_code,
    capacity_l, current_volume_l, reorder_threshold_l
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
`

type CreateStationTankParams struct {
	StationID         int64          `json:"station_id"`
	TankCode          string         `json:"tank_code"`
	FuelTypeCode      string         `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric `json:"capacity_l"`
	CurrentVolumeL    pgtype.Numeric `json:"current_volume_l"`
	ReorderThresholdL pgtype.Numeric `json:"reorder_threshold_l"`
}

func (q *Queries) CreateStationTank(ctx context.Context, arg CreateStationTankParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, createStationTank,
		arg.StationID,
		arg.TankCode,
		arg.FuelTypeCode,
		arg.CapacityL,
		arg.CurrentVolumeL,
		arg.ReorderThresholdL,
	)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateStationTank = `-- name: DeactivateStationTank :exec
UPDATE station_tanks
SET active = FALSE, last_updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStationTank(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateStationTank, id)
	return err
}

const getStationTank = `-- name: GetStationTank :one

SELECT id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
FROM station_tanks
WHERE id = $1
`

// =============================================================================
// SECTION 18 — STATION TANKS
// =============================================================================
func (q *Queries) GetStationTank(ctx context.Context, id int64) (StationTank, error) {
	row := q.db.QueryRow(ctx, getStationTank, id)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getStationTankByFuel = `-- name: GetStationTankByFuel :one
SELECT id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
FROM station_tanks
WHERE station_id    = $1
  AND fuel_type_code = $2
  AND active = TRUE
`

type GetStationTankByFuelParams struct {
	StationID    int64  `json:"station_id"`
	FuelTypeCode string `json:"fuel_type_code"`
}

func (q *Queries) GetStationTankByFuel(ctx context.Context, arg GetStationTankByFuelParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, getStationTankByFuel, arg.StationID, arg.FuelTypeCode)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listStationTanksBelowReorderThreshold = `-- name: ListStationTanksBelowReorderThreshold :many
SELECT
    st.id, st.station_id, st.tank_code, st.fuel_type_code, st.capacity_l, st.current_volume_l, st.reorder_threshold_l, st.last_dip_reading_l, st.last_dip_at, st.active, st.last_updated_at, st.created_at,
    gs.name                AS station_name,
    gs.code                AS station_code,
    gs.primary_facility_id,
    gs.region_code,
    ROUND((st.current_volume_l / NULLIF(st.reorder_threshold_l, 0) * 100)::NUMERIC, 1) AS fill_pct
FROM station_tanks st
JOIN gas_stations  gs ON gs.id = st.station_id
WHERE st.active           = TRUE
  AND gs.active           = TRUE
  AND st.current_volume_l <= st.reorder_threshold_l
ORDER BY fill_pct ASC
`

type ListStationTanksBelowReorderThresholdRow struct {
	ID                int64              `json:"id"`
	StationID         int64              `json:"station_id"`
	TankCode          string             `json:"tank_code"`
	FuelTypeCode      string             `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric     `json:"capacity_l"`
	CurrentVolumeL    pgtype.Numeric     `json:"current_volume_l"`
	ReorderThresholdL pgtype.Numeric     `json:"reorder_threshold_l"`
	LastDipReadingL   pgtype.Numeric     `json:"last_dip_reading_l"`
	LastDipAt         pgtype.Timestamptz `json:"last_dip_at"`
	Active            bool               `json:"active"`
	LastUpdatedAt     pgtype.Timestamptz `json:"last_updated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StationName       string             `json:"station_name"`
	StationCode       string             `json:"station_code"`
	PrimaryFacilityID int64              `json:"primary_facility_id"`
	RegionCode        string             `json:"region_code"`
	FillPct           decimal.Decimal    `json:"fill_pct"`
}

// Phase 3: auto-DO trigger source. Returns all under-threshold active tanks.
func (q *Queries) ListStationTanksBelowReorderThreshold(ctx context.Context) ([]ListStationTanksBelowReorderThresholdRow, error) {
	rows, err := q.db.Query(ctx, listStationTanksBelowReorderThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStationTanksBelowReorderThresholdRow{}
	for rows.Next() {
		var i ListStationTanksBelowReorderThresholdRow
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.TankCode,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.CurrentVolumeL,
			&i.ReorderThresholdL,
			&i.LastDipReadingL,
			&i.LastDipAt,
			&i.Active,
			&i.LastUpdatedAt,
			&i.CreatedAt,
			&i.StationName,
			&i.StationCode,
			&i.PrimaryFacilityID,
			&i.RegionCode,
			&i.FillPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStationTanksByStation = `-- name: ListStationTanksByStation :many
SELECT id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
FROM station_tanks
WHERE station_id = $1
  AND active = TRUE
ORDER BY fuel_type_code
`

func (q *Queries) ListStationTanksByStation(ctx context.Context, stationID int64) ([]StationTank, error) {
	rows, err := q.db.Query(ctx, listStationTanksByStation, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StationTank{}
	for rows.Next() {
		var i StationTank
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.TankCode,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.CurrentVolumeL,
			&i.ReorderThresholdL,
			&i.LastDipReadingL,
			&i.LastDipAt,
			&i.Active,
			&i.LastUpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDipReading = `-- name: UpdateDipReading :one
UPDATE station_tanks
SET
    last_dip_reading_l  = $2,
    last_dip_at         = NOW(),
    last_updated_at     = NOW()
WHERE id = $1
RETURNING id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
`

type UpdateDipReadingParams struct {
	ID              int64          `json:"id"`
	LastDipReadingL pgtype.Numeric `json:"last_dip_reading_l"`
}

func (q *Queries) UpdateDipReading(ctx context.Context, arg UpdateDipReadingParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, updateDipReading, arg.ID, arg.LastDipReadingL)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStationTankReorderThreshold = `-- name: UpdateStationTankReorderThreshold :one
UPDATE station_tanks
SET
    reorder_threshold_l = $2,
    last_updated_at     = NOW()
WHERE id = $1
RETURNING id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
`

type UpdateStationTankReorderThresholdParams struct {
	ID                int64          `json:"id"`
	ReorderThresholdL pgtype.Numeric `json:"reorder_threshold_l"`
}

func (q *Queries) UpdateStationTankReorderThreshold(ctx context.Context, arg UpdateStationTankReorderThresholdParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, updateStationTankReorderThreshold, arg.ID, arg.ReorderThresholdL)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStationTankVolume = `-- name: UpdateStationTankVolume :one
UPDATE station_tanks
SET
    current_volume_l = $2,
    last_updated_at  = NOW()
WHERE id = $1
RETURNING id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
`

type UpdateStationTankVolumeParams struct {
	ID             int64          `json:"id"`
	CurrentVolumeL pgtype.Numeric `json:"current_volume_l"`
}

// Manual correction. Caller must write to audit_log.
func (q *Queries) UpdateStationTankVolume(ctx context.Context, arg UpdateStationTankVolumeParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, updateStationTankVolume, arg.ID, arg.CurrentVolumeL)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateStationTankVolumeAfterDelivery = `-- name: UpdateStationTankVolumeAfterDelivery :one
UPDATE station_tanks
SET
    current_volume_l = current_volume_l + $2,
    last_updated_at  = NOW()
WHERE id = $1
  AND active = TRUE
RETURNING id, station_id, tank_code, fuel_type_code, capacity_l, current_volume_l, reorder_threshold_l, last_dip_reading_l, last_dip_at, active, last_updated_at, created_at
`

type UpdateStationTankVolumeAfterDeliveryParams struct {
	ID             int64          `json:"id"`
	CurrentVolumeL pgtype.Numeric `json:"current_volume_l"`
}

// Called by reconciliation engine after delivery is confirmed.
func (q *Queries) UpdateStationTankVolumeAfterDelivery(ctx context.Context, arg UpdateStationTankVolumeAfterDeliveryParams) (StationTank, error) {
	row := q.db.QueryRow(ctx, updateStationTankVolumeAfterDelivery, arg.ID, arg.CurrentVolumeL)
	var i StationTank
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.TankCode,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.CurrentVolumeL,
		&i.ReorderThresholdL,
		&i.LastDipReadingL,
		&i.LastDipAt,
		&i.Active,
		&i.LastUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
