// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: station_facility_whitelist.sql

package db

import (
	"context"
)

const addFacilityToStationWhitelist = `-- name: AddFacilityToStationWhitelist :exec
INSERT INTO station_facility_whitelist (station_id, facility_id)
VALUES ($1, $2)
ON CONFLICT (station_id, facility_id) DO NOTHING
`

type AddFacilityToStationWhitelistParams struct {
	StationID  int64 `json:"station_id"`
	FacilityID int64 `json:"facility_id"`
}

func (q *Queries) AddFacilityToStationWhitelist(ctx context.Context, arg AddFacilityToStationWhitelistParams) error {
	_, err := q.db.Exec(ctx, addFacilityToStationWhitelist, arg.StationID, arg.FacilityID)
	return err
}

const checkFacilityCanServeStation = `-- name: CheckFacilityCanServeStation :one
SELECT EXISTS (
    SELECT 1
    FROM station_facility_whitelist
    WHERE station_id  = $1
      AND facility_id = $2
) AS can_serve
`

type CheckFacilityCanServeStationParams struct {
	StationID  int64 `json:"station_id"`
	FacilityID int64 `json:"facility_id"`
}

func (q *Queries) CheckFacilityCanServeStation(ctx context.Context, arg CheckFacilityCanServeStationParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFacilityCanServeStation, arg.StationID, arg.FacilityID)
	var can_serve bool
	err := row.Scan(&can_serve)
	return can_serve, err
}

const listFacilitiesForStation = `-- name: ListFacilitiesForStation :many

SELECT
    sfw.facility_id,
    rf.code AS facility_code,
    rf.name AS facility_name,
    r.name  AS refinery_name,
    (gs.primary_facility_id = sfw.facility_id) AS is_primary
FROM station_facility_whitelist sfw
JOIN refinery_facilities rf ON rf.id = sfw.facility_id
JOIN refineries           r  ON r.id  = rf.refinery_id
JOIN gas_stations         gs ON gs.id = sfw.station_id
WHERE sfw.station_id = $1
`

type ListFacilitiesForStationRow struct {
	FacilityID   int64  `json:"facility_id"`
	FacilityCode string `json:"facility_code"`
	FacilityName string `json:"facility_name"`
	RefineryName string `json:"refinery_name"`
	IsPrimary    bool   `json:"is_primary"`
}

// =============================================================================
// SECTION 16 — STATION FACILITY WHITELIST
// =============================================================================
func (q *Queries) ListFacilitiesForStation(ctx context.Context, stationID int64) ([]ListFacilitiesForStationRow, error) {
	rows, err := q.db.Query(ctx, listFacilitiesForStation, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilitiesForStationRow{}
	for rows.Next() {
		var i ListFacilitiesForStationRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.FacilityCode,
			&i.FacilityName,
			&i.RefineryName,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFacilityFromStationWhitelist = `-- name: RemoveFacilityFromStationWhitelist :exec
DELETE FROM station_facility_whitelist
WHERE station_id  = $1
  AND facility_id = $2
`

type RemoveFacilityFromStationWhitelistParams struct {
	StationID  int64 `json:"station_id"`
	FacilityID int64 `json:"facility_id"`
}

func (q *Queries) RemoveFacilityFromStationWhitelist(ctx context.Context, arg RemoveFacilityFromStationWhitelistParams) error {
	_, err := q.db.Exec(ctx, removeFacilityFromStationWhitelist, arg.StationID, arg.FacilityID)
	return err
}
