// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: station_qr_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStationQRCode = `-- name: CreateStationQRCode :one
INSERT INTO station_qr_codes (station_id, qr_payload, label)
VALUES ($1, $2, $3)
RETURNING id, station_id, qr_payload, label, active, created_at
`

type CreateStationQRCodeParams struct {
	StationID int64       `json:"station_id"`
	QrPayload string      `json:"qr_payload"`
	Label     pgtype.Text `json:"label"`
}

func (q *Queries) CreateStationQRCode(ctx context.Context, arg CreateStationQRCodeParams) (StationQrCode, error) {
	row := q.db.QueryRow(ctx, createStationQRCode, arg.StationID, arg.QrPayload, arg.Label)
	var i StationQrCode
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.QrPayload,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAllStationQRCodes = `-- name: DeactivateAllStationQRCodes :exec
UPDATE station_qr_codes
SET active = FALSE
WHERE station_id = $1
`

func (q *Queries) DeactivateAllStationQRCodes(ctx context.Context, stationID int64) error {
	_, err := q.db.Exec(ctx, deactivateAllStationQRCodes, stationID)
	return err
}

const deactivateStationQRCode = `-- name: DeactivateStationQRCode :exec
UPDATE station_qr_codes
SET active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateStationQRCode(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateStationQRCode, id)
	return err
}

const getStationByQRPayload = `-- name: GetStationByQRPayload :one
SELECT
    sqr.id       AS qr_id,
    sqr.label,
    gs.id        AS station_id,
    gs.code      AS station_code,
    gs.name      AS station_name,
    gs.primary_facility_id
FROM station_qr_codes sqr
JOIN gas_stations      gs ON gs.id = sqr.station_id
WHERE sqr.qr_payload = $1
  AND sqr.active     = TRUE
  AND gs.active      = TRUE
`

type GetStationByQRPayloadRow struct {
	QrID              int64       `json:"qr_id"`
	Label             pgtype.Text `json:"label"`
	StationID         int64       `json:"station_id"`
	StationCode       string      `json:"station_code"`
	StationName       string      `json:"station_name"`
	PrimaryFacilityID int64       `json:"primary_facility_id"`
}

// Validates QR payload belongs to the expected station and is active.
func (q *Queries) GetStationByQRPayload(ctx context.Context, qrPayload string) (GetStationByQRPayloadRow, error) {
	row := q.db.QueryRow(ctx, getStationByQRPayload, qrPayload)
	var i GetStationByQRPayloadRow
	err := row.Scan(
		&i.QrID,
		&i.Label,
		&i.StationID,
		&i.StationCode,
		&i.StationName,
		&i.PrimaryFacilityID,
	)
	return i, err
}

const getStationQRCode = `-- name: GetStationQRCode :one

SELECT id, station_id, qr_payload, label, active, created_at
FROM station_qr_codes
WHERE id = $1
`

// =============================================================================
// SECTION 17 — STATION QR CODES
// =============================================================================
func (q *Queries) GetStationQRCode(ctx context.Context, id int64) (StationQrCode, error) {
	row := q.db.QueryRow(ctx, getStationQRCode, id)
	var i StationQrCode
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.QrPayload,
		&i.Label,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listQRCodesByStation = `-- name: ListQRCodesByStation :many
SELECT id, station_id, qr_payload, label, active, created_at
FROM station_qr_codes
WHERE station_id = $1
ORDER BY label
`

func (q *Queries) ListQRCodesByStation(ctx context.Context, stationID int64) ([]StationQrCode, error) {
	rows, err := q.db.Query(ctx, listQRCodesByStation, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StationQrCode{}
	for rows.Next() {
		var i StationQrCode
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.QrPayload,
			&i.Label,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
