// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFacilitySetting = `-- name: DeleteFacilitySetting :exec
DELETE FROM system_settings
WHERE key = $1
  AND facility_id = $2
`

type DeleteFacilitySettingParams struct {
	Key        string      `json:"key"`
	FacilityID pgtype.Int8 `json:"facility_id"`
}

func (q *Queries) DeleteFacilitySetting(ctx context.Context, arg DeleteFacilitySettingParams) error {
	_, err := q.db.Exec(ctx, deleteFacilitySetting, arg.Key, arg.FacilityID)
	return err
}

const getEffectiveSetting = `-- name: GetEffectiveSetting :one
SELECT COALESCE(fac.value, gbl.value) AS value
FROM system_settings gbl
LEFT JOIN system_settings fac
       ON fac.key = gbl.key
      AND fac.facility_id = $2
WHERE gbl.key = $1
  AND gbl.facility_id IS NULL
`

type GetEffectiveSettingParams struct {
	Key        string      `json:"key"`
	FacilityID pgtype.Int8 `json:"facility_id"`
}

// Resolve effective value: facility-specific overrides global default.
func (q *Queries) GetEffectiveSetting(ctx context.Context, arg GetEffectiveSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getEffectiveSetting, arg.Key, arg.FacilityID)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getFacilitySetting = `-- name: GetFacilitySetting :one
SELECT id, facility_id, key, value, description, updated_by, updated_at
FROM system_settings
WHERE key = $1
  AND facility_id = $2
`

type GetFacilitySettingParams struct {
	Key        string      `json:"key"`
	FacilityID pgtype.Int8 `json:"facility_id"`
}

func (q *Queries) GetFacilitySetting(ctx context.Context, arg GetFacilitySettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getFacilitySetting, arg.Key, arg.FacilityID)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalSetting = `-- name: GetGlobalSetting :one

SELECT id, facility_id, key, value, description, updated_by, updated_at
FROM system_settings
WHERE key = $1
  AND facility_id IS NULL
`

// =============================================================================
// SECTION 3 — SYSTEM SETTINGS
// =============================================================================
func (q *Queries) GetGlobalSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getGlobalSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalSettings = `-- name: ListGlobalSettings :many
SELECT id, facility_id, key, value, description, updated_by, updated_at
FROM system_settings
WHERE facility_id IS NULL
ORDER BY key
`

func (q *Queries) ListGlobalSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listGlobalSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettingsByFacility = `-- name: ListSettingsByFacility :many
SELECT id, facility_id, key, value, description, updated_by, updated_at
FROM system_settings
WHERE facility_id = $1
ORDER BY key
`

func (q *Queries) ListSettingsByFacility(ctx context.Context, facilityID pgtype.Int8) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSettingsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacilitySetting = `-- name: UpsertFacilitySetting :one
INSERT INTO system_settings (facility_id, key, value, description, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT idx_system_settings_facility
DO UPDATE SET
    value       = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_settings.description),
    updated_by  = EXCLUDED.updated_by,
    updated_at  = NOW()
RETURNING id, facility_id, key, value, description, updated_by, updated_at
`

type UpsertFacilitySettingParams struct {
	FacilityID  pgtype.Int8 `json:"facility_id"`
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
	UpdatedBy   pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertFacilitySetting(ctx context.Context, arg UpsertFacilitySettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertFacilitySetting,
		arg.FacilityID,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGlobalSetting = `-- name: UpsertGlobalSetting :one
INSERT INTO system_settings (facility_id, key, value, description, updated_by)
VALUES (NULL, $1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT idx_system_settings_global
DO UPDATE SET
    value      = EXCLUDED.value,
    description = COALESCE(EXCLUDED.description, system_settings.description),
    updated_by  = EXCLUDED.updated_by,
    updated_at  = NOW()
RETURNING id, facility_id, key, value, description, updated_by, updated_at
`

type UpsertGlobalSettingParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
	UpdatedBy   pgtype.Int8 `json:"updated_by"`
}

func (q *Queries) UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertGlobalSetting,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.UpdatedBy,
	)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
