// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: telegram_link_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTelegramLinkToken = `-- name: CreateTelegramLinkToken :one

INSERT INTO telegram_link_tokens (user_id, token, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '48 hours')
RETURNING id, user_id, token, expires_at, used_at, created_at
`

type CreateTelegramLinkTokenParams struct {
	UserID int64  `json:"user_id"`
	Token  string `json:"token"`
}

// =============================================================================
// SECTION 32 — TELEGRAM LINK TOKENS
// =============================================================================
func (q *Queries) CreateTelegramLinkToken(ctx context.Context, arg CreateTelegramLinkTokenParams) (TelegramLinkToken, error) {
	row := q.db.QueryRow(ctx, createTelegramLinkToken, arg.UserID, arg.Token)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredTelegramLinkTokens = `-- name: DeleteExpiredTelegramLinkTokens :execrows
DELETE FROM telegram_link_tokens
WHERE expires_at < NOW()
  AND used_at IS NOT NULL
`

// Called by cron worker nightly.
func (q *Queries) DeleteExpiredTelegramLinkTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredTelegramLinkTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getValidTelegramLinkToken = `-- name: GetValidTelegramLinkToken :one
SELECT tlt.id, tlt.user_id, tlt.token, tlt.expires_at, tlt.used_at, tlt.created_at, u.username, u.full_name, u.telegram_user_id
FROM telegram_link_tokens tlt
JOIN users u ON u.id = tlt.user_id
WHERE tlt.token      = $1
  AND tlt.used_at    IS NULL
  AND tlt.expires_at >  NOW()
`

type GetValidTelegramLinkTokenRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Username       string             `json:"username"`
	FullName       string             `json:"full_name"`
	TelegramUserID pgtype.Int8        `json:"telegram_user_id"`
}

// Returns token only if unused and not expired.
func (q *Queries) GetValidTelegramLinkToken(ctx context.Context, token string) (GetValidTelegramLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, getValidTelegramLinkToken, token)
	var i GetValidTelegramLinkTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
	)
	return i, err
}

const listActiveTokensForUser = `-- name: ListActiveTokensForUser :many
SELECT id, user_id, token, expires_at, used_at, created_at
FROM telegram_link_tokens
WHERE user_id    = $1
  AND used_at    IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveTokensForUser(ctx context.Context, userID int64) ([]TelegramLinkToken, error) {
	rows, err := q.db.Query(ctx, listActiveTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelegramLinkToken{}
	for rows.Next() {
		var i TelegramLinkToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useTelegramLinkToken = `-- name: UseTelegramLinkToken :one
UPDATE telegram_link_tokens
SET used_at = NOW()
WHERE token   = $1
  AND used_at IS NULL
RETURNING id, user_id, token, expires_at, used_at, created_at
`

func (q *Queries) UseTelegramLinkToken(ctx context.Context, token string) (TelegramLinkToken, error) {
	row := q.db.QueryRow(ctx, useTelegramLinkToken, token)
	var i TelegramLinkToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
