// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip_compartment_deliveries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCompartmentDelivery = `-- name: CreateCompartmentDelivery :one
INSERT INTO trip_compartment_deliveries (
    trip_id, compartment_id, fuel_type_code, measurement_method
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
`

type CreateCompartmentDeliveryParams struct {
	TripID            int64                  `json:"trip_id"`
	CompartmentID     int64                  `json:"compartment_id"`
	FuelTypeCode      string                 `json:"fuel_type_code"`
	MeasurementMethod NullMeasurementMethodT `json:"measurement_method"`
}

func (q *Queries) CreateCompartmentDelivery(ctx context.Context, arg CreateCompartmentDeliveryParams) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, createCompartmentDelivery,
		arg.TripID,
		arg.CompartmentID,
		arg.FuelTypeCode,
		arg.MeasurementMethod,
	)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompartmentDelivery = `-- name: GetCompartmentDelivery :one

SELECT id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
FROM trip_compartment_deliveries
WHERE id = $1
`

// =============================================================================
// SECTION 24 — TRIP COMPARTMENT DELIVERIES
// =============================================================================
func (q *Queries) GetCompartmentDelivery(ctx context.Context, id int64) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, getCompartmentDelivery, id)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompartmentDeliveryByTripAndCompartment = `-- name: GetCompartmentDeliveryByTripAndCompartment :one
SELECT id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
FROM trip_compartment_deliveries
WHERE trip_id      = $1
  AND compartment_id = $2
`

type GetCompartmentDeliveryByTripAndCompartmentParams struct {
	TripID        int64 `json:"trip_id"`
	CompartmentID int64 `json:"compartment_id"`
}

func (q *Queries) GetCompartmentDeliveryByTripAndCompartment(ctx context.Context, arg GetCompartmentDeliveryByTripAndCompartmentParams) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, getCompartmentDeliveryByTripAndCompartment, arg.TripID, arg.CompartmentID)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripVarianceSummary = `-- name: GetTripVarianceSummary :one
SELECT
    trip_id,
    COUNT(*)                     AS compartment_count,
    SUM(loaded_volume_l)         AS total_loaded_l,
    SUM(delivered_volume_l)      AS total_delivered_l,
    SUM(variance_l)              AS total_variance_l,
    ROUND(
        (SUM(variance_l) / NULLIF(SUM(loaded_volume_l), 0) * 100)::NUMERIC, 4
    )                            AS overall_variance_pct,
    BOOL_OR(delivery_status = 'DISPUTED') AS has_disputed
FROM trip_compartment_deliveries
WHERE trip_id = $1
GROUP BY trip_id
`

type GetTripVarianceSummaryRow struct {
	TripID             int64           `json:"trip_id"`
	CompartmentCount   int64           `json:"compartment_count"`
	TotalLoadedL       int64           `json:"total_loaded_l"`
	TotalDeliveredL    int64           `json:"total_delivered_l"`
	TotalVarianceL     int64           `json:"total_variance_l"`
	OverallVariancePct decimal.Decimal `json:"overall_variance_pct"`
	HasDisputed        bool            `json:"has_disputed"`
}

// Aggregate variance across all compartments for a trip (used by reconciliation engine).
func (q *Queries) GetTripVarianceSummary(ctx context.Context, tripID int64) (GetTripVarianceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTripVarianceSummary, tripID)
	var i GetTripVarianceSummaryRow
	err := row.Scan(
		&i.TripID,
		&i.CompartmentCount,
		&i.TotalLoadedL,
		&i.TotalDeliveredL,
		&i.TotalVarianceL,
		&i.OverallVariancePct,
		&i.HasDisputed,
	)
	return i, err
}

const listCompartmentDeliveriesByTrip = `-- name: ListCompartmentDeliveriesByTrip :many
SELECT
    tcd.id, tcd.trip_id, tcd.compartment_id, tcd.fuel_type_code, tcd.loaded_volume_l, tcd.loaded_weight_kg, tcd.delivered_volume_l, tcd.delivered_weight_kg, tcd.variance_l, tcd.variance_pct, tcd.measurement_method, tcd.delivery_status, tcd.created_at, tcd.updated_at,
    ft.name AS fuel_type_name,
    vc.compartment_number
FROM trip_compartment_deliveries tcd
JOIN fuel_types           ft ON ft.code = tcd.fuel_type_code
JOIN vehicle_compartments vc ON vc.id   = tcd.compartment_id
WHERE tcd.trip_id = $1
ORDER BY vc.compartment_number
`

type ListCompartmentDeliveriesByTripRow struct {
	ID                int64                      `json:"id"`
	TripID            int64                      `json:"trip_id"`
	CompartmentID     int64                      `json:"compartment_id"`
	FuelTypeCode      string                     `json:"fuel_type_code"`
	LoadedVolumeL     pgtype.Numeric             `json:"loaded_volume_l"`
	LoadedWeightKg    pgtype.Numeric             `json:"loaded_weight_kg"`
	DeliveredVolumeL  pgtype.Numeric             `json:"delivered_volume_l"`
	DeliveredWeightKg pgtype.Numeric             `json:"delivered_weight_kg"`
	VarianceL         pgtype.Numeric             `json:"variance_l"`
	VariancePct       pgtype.Numeric             `json:"variance_pct"`
	MeasurementMethod NullMeasurementMethodT     `json:"measurement_method"`
	DeliveryStatus    CompartmentDeliveryStatusT `json:"delivery_status"`
	CreatedAt         pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz         `json:"updated_at"`
	FuelTypeName      string                     `json:"fuel_type_name"`
	CompartmentNumber int16                      `json:"compartment_number"`
}

func (q *Queries) ListCompartmentDeliveriesByTrip(ctx context.Context, tripID int64) ([]ListCompartmentDeliveriesByTripRow, error) {
	rows, err := q.db.Query(ctx, listCompartmentDeliveriesByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompartmentDeliveriesByTripRow{}
	for rows.Next() {
		var i ListCompartmentDeliveriesByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.FuelTypeCode,
			&i.LoadedVolumeL,
			&i.LoadedWeightKg,
			&i.DeliveredVolumeL,
			&i.DeliveredWeightKg,
			&i.VarianceL,
			&i.VariancePct,
			&i.MeasurementMethod,
			&i.DeliveryStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FuelTypeName,
			&i.CompartmentNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisputedDeliveries = `-- name: ListDisputedDeliveries :many
SELECT
    tcd.id, tcd.trip_id, tcd.compartment_id, tcd.fuel_type_code, tcd.loaded_volume_l, tcd.loaded_weight_kg, tcd.delivered_volume_l, tcd.delivered_weight_kg, tcd.variance_l, tcd.variance_pct, tcd.measurement_method, tcd.delivery_status, tcd.created_at, tcd.updated_at,
    t.id          AS trip_id,
    v.plate_number,
    gs.name       AS station_name
FROM trip_compartment_deliveries tcd
JOIN trips         t  ON t.id  = tcd.trip_id
JOIN vehicles      v  ON v.id  = t.vehicle_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
WHERE tcd.delivery_status = 'DISPUTED'
ORDER BY t.completed_at DESC
`

type ListDisputedDeliveriesRow struct {
	ID                int64                      `json:"id"`
	TripID            int64                      `json:"trip_id"`
	CompartmentID     int64                      `json:"compartment_id"`
	FuelTypeCode      string                     `json:"fuel_type_code"`
	LoadedVolumeL     pgtype.Numeric             `json:"loaded_volume_l"`
	LoadedWeightKg    pgtype.Numeric             `json:"loaded_weight_kg"`
	DeliveredVolumeL  pgtype.Numeric             `json:"delivered_volume_l"`
	DeliveredWeightKg pgtype.Numeric             `json:"delivered_weight_kg"`
	VarianceL         pgtype.Numeric             `json:"variance_l"`
	VariancePct       pgtype.Numeric             `json:"variance_pct"`
	MeasurementMethod NullMeasurementMethodT     `json:"measurement_method"`
	DeliveryStatus    CompartmentDeliveryStatusT `json:"delivery_status"`
	CreatedAt         pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz         `json:"updated_at"`
	TripID_2          int64                      `json:"trip_id_2"`
	PlateNumber       string                     `json:"plate_number"`
	StationName       pgtype.Text                `json:"station_name"`
}

// Supervisor view: all disputed compartment deliveries across all trips.
func (q *Queries) ListDisputedDeliveries(ctx context.Context) ([]ListDisputedDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDisputedDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisputedDeliveriesRow{}
	for rows.Next() {
		var i ListDisputedDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.FuelTypeCode,
			&i.LoadedVolumeL,
			&i.LoadedWeightKg,
			&i.DeliveredVolumeL,
			&i.DeliveredWeightKg,
			&i.VarianceL,
			&i.VariancePct,
			&i.MeasurementMethod,
			&i.DeliveryStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TripID_2,
			&i.PlateNumber,
			&i.StationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripDeliveredVolumeByFuel = `-- name: ListTripDeliveredVolumeByFuel :many
SELECT
    fuel_type_code,
    SUM(delivered_volume_l)::NUMERIC AS total_delivered_l
FROM trip_compartment_deliveries
WHERE trip_id = $1
GROUP BY fuel_type_code
ORDER BY fuel_type_code
`

type ListTripDeliveredVolumeByFuelRow struct {
	FuelTypeCode    string         `json:"fuel_type_code"`
	TotalDeliveredL pgtype.Numeric `json:"total_delivered_l"`
}

func (q *Queries) ListTripDeliveredVolumeByFuel(ctx context.Context, tripID int64) ([]ListTripDeliveredVolumeByFuelRow, error) {
	rows, err := q.db.Query(ctx, listTripDeliveredVolumeByFuel, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripDeliveredVolumeByFuelRow{}
	for rows.Next() {
		var i ListTripDeliveredVolumeByFuelRow
		if err := rows.Scan(&i.FuelTypeCode, &i.TotalDeliveredL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripLoadedVolumeByFuel = `-- name: ListTripLoadedVolumeByFuel :many
SELECT
    fuel_type_code,
    SUM(loaded_volume_l)::NUMERIC AS total_loaded_l
FROM trip_compartment_deliveries
WHERE trip_id = $1
GROUP BY fuel_type_code
ORDER BY fuel_type_code
`

type ListTripLoadedVolumeByFuelRow struct {
	FuelTypeCode string         `json:"fuel_type_code"`
	TotalLoadedL pgtype.Numeric `json:"total_loaded_l"`
}

func (q *Queries) ListTripLoadedVolumeByFuel(ctx context.Context, tripID int64) ([]ListTripLoadedVolumeByFuelRow, error) {
	rows, err := q.db.Query(ctx, listTripLoadedVolumeByFuel, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTripLoadedVolumeByFuelRow{}
	for rows.Next() {
		var i ListTripLoadedVolumeByFuelRow
		if err := rows.Scan(&i.FuelTypeCode, &i.TotalLoadedL); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompartmentDeliveryStatus = `-- name: UpdateCompartmentDeliveryStatus :one
UPDATE trip_compartment_deliveries
SET delivery_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
`

type UpdateCompartmentDeliveryStatusParams struct {
	ID             int64                      `json:"id"`
	DeliveryStatus CompartmentDeliveryStatusT `json:"delivery_status"`
}

func (q *Queries) UpdateCompartmentDeliveryStatus(ctx context.Context, arg UpdateCompartmentDeliveryStatusParams) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, updateCompartmentDeliveryStatus, arg.ID, arg.DeliveryStatus)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveredVolume = `-- name: UpdateDeliveredVolume :one
UPDATE trip_compartment_deliveries
SET
    delivered_volume_l  = $2,
    delivered_weight_kg = $3,
    updated_at          = NOW()
WHERE id = $1
RETURNING id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
`

type UpdateDeliveredVolumeParams struct {
	ID                int64          `json:"id"`
	DeliveredVolumeL  pgtype.Numeric `json:"delivered_volume_l"`
	DeliveredWeightKg pgtype.Numeric `json:"delivered_weight_kg"`
}

func (q *Queries) UpdateDeliveredVolume(ctx context.Context, arg UpdateDeliveredVolumeParams) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveredVolume, arg.ID, arg.DeliveredVolumeL, arg.DeliveredWeightKg)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoadedVolume = `-- name: UpdateLoadedVolume :one
UPDATE trip_compartment_deliveries
SET
    loaded_volume_l  = $2,
    loaded_weight_kg = $3,
    updated_at       = NOW()
WHERE id = $1
RETURNING id, trip_id, compartment_id, fuel_type_code, loaded_volume_l, loaded_weight_kg, delivered_volume_l, delivered_weight_kg, variance_l, variance_pct, measurement_method, delivery_status, created_at, updated_at
`

type UpdateLoadedVolumeParams struct {
	ID             int64          `json:"id"`
	LoadedVolumeL  pgtype.Numeric `json:"loaded_volume_l"`
	LoadedWeightKg pgtype.Numeric `json:"loaded_weight_kg"`
}

func (q *Queries) UpdateLoadedVolume(ctx context.Context, arg UpdateLoadedVolumeParams) (TripCompartmentDelivery, error) {
	row := q.db.QueryRow(ctx, updateLoadedVolume, arg.ID, arg.LoadedVolumeL, arg.LoadedWeightKg)
	var i TripCompartmentDelivery
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.FuelTypeCode,
		&i.LoadedVolumeL,
		&i.LoadedWeightKg,
		&i.DeliveredVolumeL,
		&i.DeliveredWeightKg,
		&i.VarianceL,
		&i.VariancePct,
		&i.MeasurementMethod,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
