// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip_events.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestTripEvent = `-- name: GetLatestTripEvent :one
SELECT id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
FROM trip_events
WHERE trip_id = $1
ORDER BY event_timestamp DESC
LIMIT 1
`

func (q *Queries) GetLatestTripEvent(ctx context.Context, tripID int64) (TripEvent, error) {
	row := q.db.QueryRow(ctx, getLatestTripEvent, tripID)
	var i TripEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventUuid,
		&i.EventType,
		&i.EventTimestamp,
		&i.ReceivedAt,
		&i.ActorUserID,
		&i.Location,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestTripEventByType = `-- name: GetLatestTripEventByType :one
SELECT id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
FROM trip_events
WHERE trip_id    = $1
  AND event_type = $2
ORDER BY event_timestamp DESC
LIMIT 1
`

type GetLatestTripEventByTypeParams struct {
	TripID    int64          `json:"trip_id"`
	EventType TripEventTypeT `json:"event_type"`
}

func (q *Queries) GetLatestTripEventByType(ctx context.Context, arg GetLatestTripEventByTypeParams) (TripEvent, error) {
	row := q.db.QueryRow(ctx, getLatestTripEventByType, arg.TripID, arg.EventType)
	var i TripEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventUuid,
		&i.EventType,
		&i.EventTimestamp,
		&i.ReceivedAt,
		&i.ActorUserID,
		&i.Location,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getTripEventByUUID = `-- name: GetTripEventByUUID :one

SELECT id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
FROM trip_events
WHERE event_uuid = $1
`

// =============================================================================
// SECTION 23 — TRIP EVENTS (APPEND-ONLY)
// =============================================================================
// Used by idempotency check before inserting from offline queue.
func (q *Queries) GetTripEventByUUID(ctx context.Context, eventUuid uuid.UUID) (TripEvent, error) {
	row := q.db.QueryRow(ctx, getTripEventByUUID, eventUuid)
	var i TripEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventUuid,
		&i.EventType,
		&i.EventTimestamp,
		&i.ReceivedAt,
		&i.ActorUserID,
		&i.Location,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertTripEvent = `-- name: InsertTripEvent :one
INSERT INTO trip_events (
    trip_id, event_uuid, event_type, event_timestamp,
    actor_user_id, location, payload
) VALUES (
    $1, $2, $3, $4, $5,
    CASE WHEN $6::FLOAT8 IS NOT NULL AND $7::FLOAT8 IS NOT NULL
         THEN ST_SetSRID(ST_MakePoint($6, $7), 4326)
         ELSE NULL
    END,
    $8
)
RETURNING id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
`

type InsertTripEventParams struct {
	TripID         int64              `json:"trip_id"`
	EventUuid      uuid.UUID          `json:"event_uuid"`
	EventType      TripEventTypeT     `json:"event_type"`
	EventTimestamp pgtype.Timestamptz `json:"event_timestamp"`
	ActorUserID    pgtype.Int8        `json:"actor_user_id"`
	Column6        float64            `json:"column_6"`
	Column7        float64            `json:"column_7"`
	Payload        json.RawMessage    `json:"payload"`
}

// Append-only. event_uuid checked for duplicate before calling this.
func (q *Queries) InsertTripEvent(ctx context.Context, arg InsertTripEventParams) (TripEvent, error) {
	row := q.db.QueryRow(ctx, insertTripEvent,
		arg.TripID,
		arg.EventUuid,
		arg.EventType,
		arg.EventTimestamp,
		arg.ActorUserID,
		arg.Column6,
		arg.Column7,
		arg.Payload,
	)
	var i TripEvent
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventUuid,
		&i.EventType,
		&i.EventTimestamp,
		&i.ReceivedAt,
		&i.ActorUserID,
		&i.Location,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listTripEventsByTrip = `-- name: ListTripEventsByTrip :many
SELECT id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
FROM trip_events
WHERE trip_id = $1
ORDER BY event_timestamp ASC
`

func (q *Queries) ListTripEventsByTrip(ctx context.Context, tripID int64) ([]TripEvent, error) {
	rows, err := q.db.Query(ctx, listTripEventsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripEvent{}
	for rows.Next() {
		var i TripEvent
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.EventUuid,
			&i.EventType,
			&i.EventTimestamp,
			&i.ReceivedAt,
			&i.ActorUserID,
			&i.Location,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripEventsByTripAndType = `-- name: ListTripEventsByTripAndType :many
SELECT id, trip_id, event_uuid, event_type, event_timestamp, received_at, actor_user_id, location, payload, created_at
FROM trip_events
WHERE trip_id    = $1
  AND event_type = $2
ORDER BY event_timestamp ASC
`

type ListTripEventsByTripAndTypeParams struct {
	TripID    int64          `json:"trip_id"`
	EventType TripEventTypeT `json:"event_type"`
}

func (q *Queries) ListTripEventsByTripAndType(ctx context.Context, arg ListTripEventsByTripAndTypeParams) ([]TripEvent, error) {
	rows, err := q.db.Query(ctx, listTripEventsByTripAndType, arg.TripID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripEvent{}
	for rows.Next() {
		var i TripEvent
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.EventUuid,
			&i.EventType,
			&i.EventTimestamp,
			&i.ReceivedAt,
			&i.ActorUserID,
			&i.Location,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
