// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip_documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTripDocument = `-- name: CreateTripDocument :one
INSERT INTO trip_documents (
    trip_id, document_type, document_number,
    garage_object_key, generated_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, trip_id, document_type, document_number, garage_object_key, generated_by, generated_at
`

type CreateTripDocumentParams struct {
	TripID          int64         `json:"trip_id"`
	DocumentType    DocumentTypeT `json:"document_type"`
	DocumentNumber  pgtype.Text   `json:"document_number"`
	GarageObjectKey string        `json:"garage_object_key"`
	GeneratedBy     pgtype.Int8   `json:"generated_by"`
}

func (q *Queries) CreateTripDocument(ctx context.Context, arg CreateTripDocumentParams) (TripDocument, error) {
	row := q.db.QueryRow(ctx, createTripDocument,
		arg.TripID,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.GarageObjectKey,
		arg.GeneratedBy,
	)
	var i TripDocument
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.GarageObjectKey,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}

const getTripDocument = `-- name: GetTripDocument :one

SELECT id, trip_id, document_type, document_number, garage_object_key, generated_by, generated_at
FROM trip_documents
WHERE id = $1
`

// =============================================================================
// SECTION 28 — TRIP DOCUMENTS
// =============================================================================
func (q *Queries) GetTripDocument(ctx context.Context, id int64) (TripDocument, error) {
	row := q.db.QueryRow(ctx, getTripDocument, id)
	var i TripDocument
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.GarageObjectKey,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}

const getTripDocumentByType = `-- name: GetTripDocumentByType :one
SELECT id, trip_id, document_type, document_number, garage_object_key, generated_by, generated_at
FROM trip_documents
WHERE trip_id      = $1
  AND document_type = $2
`

type GetTripDocumentByTypeParams struct {
	TripID       int64         `json:"trip_id"`
	DocumentType DocumentTypeT `json:"document_type"`
}

func (q *Queries) GetTripDocumentByType(ctx context.Context, arg GetTripDocumentByTypeParams) (TripDocument, error) {
	row := q.db.QueryRow(ctx, getTripDocumentByType, arg.TripID, arg.DocumentType)
	var i TripDocument
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.GarageObjectKey,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}

const listDocumentsByTrip = `-- name: ListDocumentsByTrip :many
SELECT id, trip_id, document_type, document_number, garage_object_key, generated_by, generated_at
FROM trip_documents
WHERE trip_id = $1
ORDER BY generated_at
`

func (q *Queries) ListDocumentsByTrip(ctx context.Context, tripID int64) ([]TripDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripDocument{}
	for rows.Next() {
		var i TripDocument
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.GarageObjectKey,
			&i.GeneratedBy,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTripDocumentKey = `-- name: UpdateTripDocumentKey :one
UPDATE trip_documents
SET
    garage_object_key = $2,
    generated_at      = NOW()
WHERE id = $1
RETURNING id, trip_id, document_type, document_number, garage_object_key, generated_by, generated_at
`

type UpdateTripDocumentKeyParams struct {
	ID              int64  `json:"id"`
	GarageObjectKey string `json:"garage_object_key"`
}

// Called if a document is regenerated (e.g., after variance resolution).
func (q *Queries) UpdateTripDocumentKey(ctx context.Context, arg UpdateTripDocumentKeyParams) (TripDocument, error) {
	row := q.db.QueryRow(ctx, updateTripDocumentKey, arg.ID, arg.GarageObjectKey)
	var i TripDocument
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.GarageObjectKey,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}
