// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTripRoutePoint = `-- name: AppendTripRoutePoint :exec
UPDATE trips
SET route_polyline = ST_MakeLine(
        COALESCE(route_polyline, ST_MakePoint($2, $3)::GEOMETRY),
        ST_SetSRID(ST_MakePoint($2, $3), 4326)
    ),
    updated_at = NOW()
WHERE id = $1
`

type AppendTripRoutePointParams struct {
	ID            int64       `json:"id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

// Extends route polyline with the latest GPS coordinate (called by background worker).
func (q *Queries) AppendTripRoutePoint(ctx context.Context, arg AppendTripRoutePointParams) error {
	_, err := q.db.Exec(ctx, appendTripRoutePoint, arg.ID, arg.StMakepoint, arg.StMakepoint_2)
	return err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    do_id, vehicle_id, driver_id, status,
    destination_type, origin_facility_id,
    destination_station_id, destination_facility_id,
    parent_trip_id
) VALUES (
    $1, $2, $3, 'CREATED',
    $4, $5, $6, $7, $8
)
RETURNING id, do_id, vehicle_id, driver_id, status, destination_type, origin_facility_id, destination_station_id, destination_facility_id, route_polyline, departed_at, arrived_at, completed_at, parent_trip_id, created_at, updated_at
`

type CreateTripParams struct {
	DoID                  int64            `json:"do_id"`
	VehicleID             int64            `json:"vehicle_id"`
	DriverID              int64            `json:"driver_id"`
	DestinationType       DestinationTypeT `json:"destination_type"`
	OriginFacilityID      int64            `json:"origin_facility_id"`
	DestinationStationID  pgtype.Int8      `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8      `json:"destination_facility_id"`
	ParentTripID          pgtype.Int8      `json:"parent_trip_id"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.DoID,
		arg.VehicleID,
		arg.DriverID,
		arg.DestinationType,
		arg.OriginFacilityID,
		arg.DestinationStationID,
		arg.DestinationFacilityID,
		arg.ParentTripID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrip = `-- name: GetTrip :one

SELECT
    t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at,
    ST_AsGeoJSON(t.route_polyline) AS route_geojson
FROM trips t
WHERE t.id = $1
`

type GetTripRow struct {
	ID                    int64              `json:"id"`
	DoID                  int64              `json:"do_id"`
	VehicleID             int64              `json:"vehicle_id"`
	DriverID              int64              `json:"driver_id"`
	Status                TripStatusT        `json:"status"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	RoutePolyline         interface{}        `json:"route_polyline"`
	DepartedAt            pgtype.Timestamptz `json:"departed_at"`
	ArrivedAt             pgtype.Timestamptz `json:"arrived_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	ParentTripID          pgtype.Int8        `json:"parent_trip_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RouteGeojson          interface{}        `json:"route_geojson"`
}

// =============================================================================
// SECTION 22 — TRIPS
// =============================================================================
func (q *Queries) GetTrip(ctx context.Context, id int64) (GetTripRow, error) {
	row := q.db.QueryRow(ctx, getTrip, id)
	var i GetTripRow
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteGeojson,
	)
	return i, err
}

const getTripByDO = `-- name: GetTripByDO :one
SELECT
    t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at,
    ST_AsGeoJSON(t.route_polyline) AS route_geojson
FROM trips t
WHERE t.do_id = $1
`

type GetTripByDORow struct {
	ID                    int64              `json:"id"`
	DoID                  int64              `json:"do_id"`
	VehicleID             int64              `json:"vehicle_id"`
	DriverID              int64              `json:"driver_id"`
	Status                TripStatusT        `json:"status"`
	DestinationType       DestinationTypeT   `json:"destination_type"`
	OriginFacilityID      int64              `json:"origin_facility_id"`
	DestinationStationID  pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID pgtype.Int8        `json:"destination_facility_id"`
	RoutePolyline         interface{}        `json:"route_polyline"`
	DepartedAt            pgtype.Timestamptz `json:"departed_at"`
	ArrivedAt             pgtype.Timestamptz `json:"arrived_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	ParentTripID          pgtype.Int8        `json:"parent_trip_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RouteGeojson          interface{}        `json:"route_geojson"`
}

func (q *Queries) GetTripByDO(ctx context.Context, doID int64) (GetTripByDORow, error) {
	row := q.db.QueryRow(ctx, getTripByDO, doID)
	var i GetTripByDORow
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RouteGeojson,
	)
	return i, err
}

const getTripWithDetails = `-- name: GetTripWithDetails :one
SELECT
    t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at,
    v.plate_number,
    u.full_name     AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name         AS destination_station_name,
    gs.code         AS destination_station_code,
    rf.name         AS origin_facility_name,
    ST_AsGeoJSON(t.route_polyline) AS route_geojson
FROM trips t
JOIN vehicles             v   ON v.id  = t.vehicle_id
JOIN drivers              d   ON d.id  = t.driver_id
JOIN users                u   ON u.id  = d.user_id
JOIN refinery_facilities  rf  ON rf.id = t.origin_facility_id
LEFT JOIN gas_stations    gs  ON gs.id = t.destination_station_id
WHERE t.id = $1
`

type GetTripWithDetailsRow struct {
	ID                     int64              `json:"id"`
	DoID                   int64              `json:"do_id"`
	VehicleID              int64              `json:"vehicle_id"`
	DriverID               int64              `json:"driver_id"`
	Status                 TripStatusT        `json:"status"`
	DestinationType        DestinationTypeT   `json:"destination_type"`
	OriginFacilityID       int64              `json:"origin_facility_id"`
	DestinationStationID   pgtype.Int8        `json:"destination_station_id"`
	DestinationFacilityID  pgtype.Int8        `json:"destination_facility_id"`
	RoutePolyline          interface{}        `json:"route_polyline"`
	DepartedAt             pgtype.Timestamptz `json:"departed_at"`
	ArrivedAt              pgtype.Timestamptz `json:"arrived_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	ParentTripID           pgtype.Int8        `json:"parent_trip_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	PlateNumber            string             `json:"plate_number"`
	DriverName             string             `json:"driver_name"`
	DriverTelegramID       pgtype.Int8        `json:"driver_telegram_id"`
	DestinationStationName pgtype.Text        `json:"destination_station_name"`
	DestinationStationCode pgtype.Text        `json:"destination_station_code"`
	OriginFacilityName     string             `json:"origin_facility_name"`
	RouteGeojson           interface{}        `json:"route_geojson"`
}

func (q *Queries) GetTripWithDetails(ctx context.Context, id int64) (GetTripWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getTripWithDetails, id)
	var i GetTripWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlateNumber,
		&i.DriverName,
		&i.DriverTelegramID,
		&i.DestinationStationName,
		&i.DestinationStationCode,
		&i.OriginFacilityName,
		&i.RouteGeojson,
	)
	return i, err
}

const listActiveTrips = `-- name: ListActiveTrips :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name        AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name            AS destination_name
FROM trips t
JOIN vehicles          v  ON v.id  = t.vehicle_id
JOIN drivers           d  ON d.id  = t.driver_id
JOIN users             u  ON u.id  = d.user_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
ORDER BY t.departed_at ASC NULLS LAST
`

type ListActiveTripsRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DriverTelegramID     pgtype.Int8        `json:"driver_telegram_id"`
	DestinationName      pgtype.Text        `json:"destination_name"`
}

// All in-flight trips across all facilities (for dashboard map feed).
func (q *Queries) ListActiveTrips(ctx context.Context) ([]ListActiveTripsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsRow{}
	for rows.Next() {
		var i ListActiveTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DriverTelegramID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsByDriverUserScope = `-- name: ListActiveTripsByDriverUserScope :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name        AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name            AS destination_name
FROM trips t
JOIN vehicles          v  ON v.id  = t.vehicle_id
JOIN drivers           d  ON d.id  = t.driver_id
JOIN users             u  ON u.id  = d.user_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
  AND u.id = $1
ORDER BY t.departed_at ASC NULLS LAST
`

type ListActiveTripsByDriverUserScopeRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DriverTelegramID     pgtype.Int8        `json:"driver_telegram_id"`
	DestinationName      pgtype.Text        `json:"destination_name"`
}

func (q *Queries) ListActiveTripsByDriverUserScope(ctx context.Context, id int64) ([]ListActiveTripsByDriverUserScopeRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByDriverUserScope, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsByDriverUserScopeRow{}
	for rows.Next() {
		var i ListActiveTripsByDriverUserScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DriverTelegramID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsByFacility = `-- name: ListActiveTripsByFacility :many
SELECT t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at
FROM trips t
WHERE t.origin_facility_id = $1
  AND t.status NOT IN ('CLOSED','CANCELLED','RECONCILED')
ORDER BY t.created_at DESC
`

func (q *Queries) ListActiveTripsByFacility(ctx context.Context, originFacilityID int64) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByFacility, originFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.VehicleID,
			&i.DriverID,
			&i.Status,
			&i.DestinationType,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.RoutePolyline,
			&i.DepartedAt,
			&i.ArrivedAt,
			&i.CompletedAt,
			&i.ParentTripID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsByFacilityScope = `-- name: ListActiveTripsByFacilityScope :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name        AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name            AS destination_name
FROM trips t
JOIN vehicles          v  ON v.id  = t.vehicle_id
JOIN drivers           d  ON d.id  = t.driver_id
JOIN users             u  ON u.id  = d.user_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
  AND t.origin_facility_id = $1
ORDER BY t.departed_at ASC NULLS LAST
`

type ListActiveTripsByFacilityScopeRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DriverTelegramID     pgtype.Int8        `json:"driver_telegram_id"`
	DestinationName      pgtype.Text        `json:"destination_name"`
}

func (q *Queries) ListActiveTripsByFacilityScope(ctx context.Context, originFacilityID int64) ([]ListActiveTripsByFacilityScopeRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByFacilityScope, originFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsByFacilityScopeRow{}
	for rows.Next() {
		var i ListActiveTripsByFacilityScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DriverTelegramID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsByRefineryScope = `-- name: ListActiveTripsByRefineryScope :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name        AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name            AS destination_name
FROM trips t
JOIN refinery_facilities rf ON rf.id = t.origin_facility_id
JOIN vehicles             v  ON v.id  = t.vehicle_id
JOIN drivers              d  ON d.id  = t.driver_id
JOIN users                u  ON u.id  = d.user_id
LEFT JOIN gas_stations    gs ON gs.id = t.destination_station_id
WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
  AND rf.refinery_id = $1
ORDER BY t.departed_at ASC NULLS LAST
`

type ListActiveTripsByRefineryScopeRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DriverTelegramID     pgtype.Int8        `json:"driver_telegram_id"`
	DestinationName      pgtype.Text        `json:"destination_name"`
}

func (q *Queries) ListActiveTripsByRefineryScope(ctx context.Context, refineryID int64) ([]ListActiveTripsByRefineryScopeRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByRefineryScope, refineryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsByRefineryScopeRow{}
	for rows.Next() {
		var i ListActiveTripsByRefineryScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DriverTelegramID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsByStationScope = `-- name: ListActiveTripsByStationScope :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name        AS driver_name,
    u.telegram_user_id AS driver_telegram_id,
    gs.name            AS destination_name
FROM trips t
JOIN vehicles          v  ON v.id  = t.vehicle_id
JOIN drivers           d  ON d.id  = t.driver_id
JOIN users             u  ON u.id  = d.user_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
WHERE t.status IN ('LOADING','LOADED','IN_TRANSIT','ARRIVED','UNLOADING')
  AND t.destination_station_id = $1
ORDER BY t.departed_at ASC NULLS LAST
`

type ListActiveTripsByStationScopeRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DriverTelegramID     pgtype.Int8        `json:"driver_telegram_id"`
	DestinationName      pgtype.Text        `json:"destination_name"`
}

func (q *Queries) ListActiveTripsByStationScope(ctx context.Context, destinationStationID pgtype.Int8) ([]ListActiveTripsByStationScopeRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByStationScope, destinationStationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsByStationScopeRow{}
	for rows.Next() {
		var i ListActiveTripsByStationScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DriverTelegramID,
			&i.DestinationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTripsWithLatestGPS = `-- name: ListActiveTripsWithLatestGPS :many
SELECT
    t.id,
    t.status,
    t.vehicle_id,
    t.driver_id,
    t.origin_facility_id,
    t.destination_station_id,
    t.departed_at,
    v.plate_number,
    u.full_name         AS driver_name,
    gs.name             AS destination_name,
    ge.latitude         AS last_lat,
    ge.longitude        AS last_lng,
    ge.speed_kmh        AS last_speed_kmh,
    ge.event_timestamp  AS last_gps_at
FROM trips t
JOIN vehicles          v  ON v.id  = t.vehicle_id
JOIN drivers           d  ON d.id  = t.driver_id
JOIN users             u  ON u.id  = d.user_id
LEFT JOIN gas_stations gs ON gs.id = t.destination_station_id
LEFT JOIN LATERAL (
    SELECT latitude, longitude, speed_kmh, event_timestamp
    FROM gps_events
    WHERE trip_id = t.id
    ORDER BY event_timestamp DESC
    LIMIT 1
) ge ON TRUE
WHERE t.status IN ('IN_TRANSIT', 'ARRIVED', 'UNLOADING')
`

type ListActiveTripsWithLatestGPSRow struct {
	ID                   int64              `json:"id"`
	Status               TripStatusT        `json:"status"`
	VehicleID            int64              `json:"vehicle_id"`
	DriverID             int64              `json:"driver_id"`
	OriginFacilityID     int64              `json:"origin_facility_id"`
	DestinationStationID pgtype.Int8        `json:"destination_station_id"`
	DepartedAt           pgtype.Timestamptz `json:"departed_at"`
	PlateNumber          string             `json:"plate_number"`
	DriverName           string             `json:"driver_name"`
	DestinationName      pgtype.Text        `json:"destination_name"`
	LastLat              pgtype.Numeric     `json:"last_lat"`
	LastLng              pgtype.Numeric     `json:"last_lng"`
	LastSpeedKmh         pgtype.Numeric     `json:"last_speed_kmh"`
	LastGpsAt            pgtype.Timestamptz `json:"last_gps_at"`
}

// Real-time dashboard map: latest GPS position per active trip via LATERAL join.
func (q *Queries) ListActiveTripsWithLatestGPS(ctx context.Context) ([]ListActiveTripsWithLatestGPSRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsWithLatestGPS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTripsWithLatestGPSRow{}
	for rows.Next() {
		var i ListActiveTripsWithLatestGPSRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.VehicleID,
			&i.DriverID,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DepartedAt,
			&i.PlateNumber,
			&i.DriverName,
			&i.DestinationName,
			&i.LastLat,
			&i.LastLng,
			&i.LastSpeedKmh,
			&i.LastGpsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturnTrips = `-- name: ListReturnTrips :many
SELECT t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at
FROM trips t
WHERE t.parent_trip_id IS NOT NULL
ORDER BY t.created_at DESC
`

// All auto-created return-to-facility trips (have parent_trip_id set).
func (q *Queries) ListReturnTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listReturnTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.VehicleID,
			&i.DriverID,
			&i.Status,
			&i.DestinationType,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.RoutePolyline,
			&i.DepartedAt,
			&i.ArrivedAt,
			&i.CompletedAt,
			&i.ParentTripID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByDriver = `-- name: ListTripsByDriver :many
SELECT t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at
FROM trips t
WHERE t.driver_id = $1
ORDER BY t.created_at DESC
LIMIT $2
`

type ListTripsByDriverParams struct {
	DriverID int64 `json:"driver_id"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListTripsByDriver(ctx context.Context, arg ListTripsByDriverParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByDriver, arg.DriverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.VehicleID,
			&i.DriverID,
			&i.Status,
			&i.DestinationType,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.RoutePolyline,
			&i.DepartedAt,
			&i.ArrivedAt,
			&i.CompletedAt,
			&i.ParentTripID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByStatus = `-- name: ListTripsByStatus :many
SELECT t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at
FROM trips t
WHERE t.status = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTripsByStatus(ctx context.Context, status TripStatusT) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.VehicleID,
			&i.DriverID,
			&i.Status,
			&i.DestinationType,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.RoutePolyline,
			&i.DepartedAt,
			&i.ArrivedAt,
			&i.CompletedAt,
			&i.ParentTripID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByVehicle = `-- name: ListTripsByVehicle :many
SELECT t.id, t.do_id, t.vehicle_id, t.driver_id, t.status, t.destination_type, t.origin_facility_id, t.destination_station_id, t.destination_facility_id, t.route_polyline, t.departed_at, t.arrived_at, t.completed_at, t.parent_trip_id, t.created_at, t.updated_at
FROM trips t
WHERE t.vehicle_id = $1
ORDER BY t.created_at DESC
LIMIT $2
`

type ListTripsByVehicleParams struct {
	VehicleID int64 `json:"vehicle_id"`
	Limit     int32 `json:"limit"`
}

func (q *Queries) ListTripsByVehicle(ctx context.Context, arg ListTripsByVehicleParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByVehicle, arg.VehicleID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.DoID,
			&i.VehicleID,
			&i.DriverID,
			&i.Status,
			&i.DestinationType,
			&i.OriginFacilityID,
			&i.DestinationStationID,
			&i.DestinationFacilityID,
			&i.RoutePolyline,
			&i.DepartedAt,
			&i.ArrivedAt,
			&i.CompletedAt,
			&i.ParentTripID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTripArrived = `-- name: SetTripArrived :one
UPDATE trips
SET
    status    = 'ARRIVED',
    arrived_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, do_id, vehicle_id, driver_id, status, destination_type, origin_facility_id, destination_station_id, destination_facility_id, route_polyline, departed_at, arrived_at, completed_at, parent_trip_id, created_at, updated_at
`

func (q *Queries) SetTripArrived(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripArrived, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTripCompleted = `-- name: SetTripCompleted :one
UPDATE trips
SET
    status       = 'DELIVERED',
    completed_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, do_id, vehicle_id, driver_id, status, destination_type, origin_facility_id, destination_station_id, destination_facility_id, route_polyline, departed_at, arrived_at, completed_at, parent_trip_id, created_at, updated_at
`

func (q *Queries) SetTripCompleted(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripCompleted, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTripDeparted = `-- name: SetTripDeparted :one
UPDATE trips
SET
    status     = 'IN_TRANSIT',
    departed_at = NOW(),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, do_id, vehicle_id, driver_id, status, destination_type, origin_facility_id, destination_station_id, destination_facility_id, route_polyline, departed_at, arrived_at, completed_at, parent_trip_id, created_at, updated_at
`

func (q *Queries) SetTripDeparted(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripDeparted, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTripStatus = `-- name: UpdateTripStatus :one
UPDATE trips
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, do_id, vehicle_id, driver_id, status, destination_type, origin_facility_id, destination_station_id, destination_facility_id, route_polyline, departed_at, arrived_at, completed_at, parent_trip_id, created_at, updated_at
`

type UpdateTripStatusParams struct {
	ID     int64       `json:"id"`
	Status TripStatusT `json:"status"`
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTripStatus, arg.ID, arg.Status)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.DoID,
		&i.VehicleID,
		&i.DriverID,
		&i.Status,
		&i.DestinationType,
		&i.OriginFacilityID,
		&i.DestinationStationID,
		&i.DestinationFacilityID,
		&i.RoutePolyline,
		&i.DepartedAt,
		&i.ArrivedAt,
		&i.CompletedAt,
		&i.ParentTripID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
