// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trip_photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTripPhoto = `-- name: CreateTripPhoto :one
INSERT INTO trip_photos (
    trip_id, compartment_id, event_type,
    garage_object_key, file_size_bytes, mime_type,
    uploaded_by, taken_at, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, trip_id, compartment_id, event_type, garage_object_key, file_size_bytes, mime_type, uploaded_by, taken_at, uploaded_at, notes
`

type CreateTripPhotoParams struct {
	TripID          int64              `json:"trip_id"`
	CompartmentID   pgtype.Int8        `json:"compartment_id"`
	EventType       PhotoEventT        `json:"event_type"`
	GarageObjectKey string             `json:"garage_object_key"`
	FileSizeBytes   pgtype.Int8        `json:"file_size_bytes"`
	MimeType        string             `json:"mime_type"`
	UploadedBy      int64              `json:"uploaded_by"`
	TakenAt         pgtype.Timestamptz `json:"taken_at"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateTripPhoto(ctx context.Context, arg CreateTripPhotoParams) (TripPhoto, error) {
	row := q.db.QueryRow(ctx, createTripPhoto,
		arg.TripID,
		arg.CompartmentID,
		arg.EventType,
		arg.GarageObjectKey,
		arg.FileSizeBytes,
		arg.MimeType,
		arg.UploadedBy,
		arg.TakenAt,
		arg.Notes,
	)
	var i TripPhoto
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.EventType,
		&i.GarageObjectKey,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.TakenAt,
		&i.UploadedAt,
		&i.Notes,
	)
	return i, err
}

const getMandatoryPhotoCheckByTrip = `-- name: GetMandatoryPhotoCheckByTrip :one
SELECT
    BOOL_OR(event_type = 'WEIGHT_BRIDGE_TARE')  AS has_tare_photo,
    BOOL_OR(event_type = 'WEIGHT_BRIDGE_GROSS') AS has_gross_photo,
    BOOL_OR(event_type = 'COMPARTMENT_SEALED')   AS has_compartment_sealed_photo,
    BOOL_OR(event_type = 'STATION_TANK_BEFORE') AS has_before_photo,
    BOOL_OR(event_type = 'PUMP_METER_READING')  AS has_pump_photo,
    BOOL_OR(event_type = 'STATION_TANK_AFTER')  AS has_after_photo
FROM trip_photos
WHERE trip_id = $1
`

type GetMandatoryPhotoCheckByTripRow struct {
	HasTarePhoto              bool `json:"has_tare_photo"`
	HasGrossPhoto             bool `json:"has_gross_photo"`
	HasCompartmentSealedPhoto bool `json:"has_compartment_sealed_photo"`
	HasBeforePhoto            bool `json:"has_before_photo"`
	HasPumpPhoto              bool `json:"has_pump_photo"`
	HasAfterPhoto             bool `json:"has_after_photo"`
}

// Verifies all mandatory photo events are present for a trip before allowing progression.
// Returns a bitmask-style row showing which required events have at least one photo.
// IMPORTANT: has_compartment_sealed_photo returns TRUE if >= 1 sealed photo exists.
// The service layer must separately verify the sealed photo count matches the trip's
// compartment count (ListCompartmentsByVehicle) before allowing LOADING → LOADED.
func (q *Queries) GetMandatoryPhotoCheckByTrip(ctx context.Context, tripID int64) (GetMandatoryPhotoCheckByTripRow, error) {
	row := q.db.QueryRow(ctx, getMandatoryPhotoCheckByTrip, tripID)
	var i GetMandatoryPhotoCheckByTripRow
	err := row.Scan(
		&i.HasTarePhoto,
		&i.HasGrossPhoto,
		&i.HasCompartmentSealedPhoto,
		&i.HasBeforePhoto,
		&i.HasPumpPhoto,
		&i.HasAfterPhoto,
	)
	return i, err
}

const getTripPhoto = `-- name: GetTripPhoto :one

SELECT id, trip_id, compartment_id, event_type, garage_object_key, file_size_bytes, mime_type, uploaded_by, taken_at, uploaded_at, notes
FROM trip_photos
WHERE id = $1
`

// =============================================================================
// SECTION 27 — TRIP PHOTOS
// =============================================================================
func (q *Queries) GetTripPhoto(ctx context.Context, id int64) (TripPhoto, error) {
	row := q.db.QueryRow(ctx, getTripPhoto, id)
	var i TripPhoto
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.CompartmentID,
		&i.EventType,
		&i.GarageObjectKey,
		&i.FileSizeBytes,
		&i.MimeType,
		&i.UploadedBy,
		&i.TakenAt,
		&i.UploadedAt,
		&i.Notes,
	)
	return i, err
}

const listPhotosByTrip = `-- name: ListPhotosByTrip :many
SELECT id, trip_id, compartment_id, event_type, garage_object_key, file_size_bytes, mime_type, uploaded_by, taken_at, uploaded_at, notes
FROM trip_photos
WHERE trip_id = $1
ORDER BY taken_at
`

func (q *Queries) ListPhotosByTrip(ctx context.Context, tripID int64) ([]TripPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripPhoto{}
	for rows.Next() {
		var i TripPhoto
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.EventType,
			&i.GarageObjectKey,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.TakenAt,
			&i.UploadedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByTripAndCompartment = `-- name: ListPhotosByTripAndCompartment :many
SELECT id, trip_id, compartment_id, event_type, garage_object_key, file_size_bytes, mime_type, uploaded_by, taken_at, uploaded_at, notes
FROM trip_photos
WHERE trip_id      = $1
  AND compartment_id = $2
ORDER BY taken_at
`

type ListPhotosByTripAndCompartmentParams struct {
	TripID        int64       `json:"trip_id"`
	CompartmentID pgtype.Int8 `json:"compartment_id"`
}

func (q *Queries) ListPhotosByTripAndCompartment(ctx context.Context, arg ListPhotosByTripAndCompartmentParams) ([]TripPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosByTripAndCompartment, arg.TripID, arg.CompartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripPhoto{}
	for rows.Next() {
		var i TripPhoto
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.EventType,
			&i.GarageObjectKey,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.TakenAt,
			&i.UploadedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByTripAndEvent = `-- name: ListPhotosByTripAndEvent :many
SELECT id, trip_id, compartment_id, event_type, garage_object_key, file_size_bytes, mime_type, uploaded_by, taken_at, uploaded_at, notes
FROM trip_photos
WHERE trip_id    = $1
  AND event_type = $2
ORDER BY taken_at
`

type ListPhotosByTripAndEventParams struct {
	TripID    int64       `json:"trip_id"`
	EventType PhotoEventT `json:"event_type"`
}

func (q *Queries) ListPhotosByTripAndEvent(ctx context.Context, arg ListPhotosByTripAndEventParams) ([]TripPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosByTripAndEvent, arg.TripID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TripPhoto{}
	for rows.Next() {
		var i TripPhoto
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.CompartmentID,
			&i.EventType,
			&i.GarageObjectKey,
			&i.FileSizeBytes,
			&i.MimeType,
			&i.UploadedBy,
			&i.TakenAt,
			&i.UploadedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
