// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, full_name, force_password_change)
VALUES ($1, $2, $3, $4)
RETURNING id, username, full_name, telegram_user_id,
          telegram_linked_at, force_password_change, active,
          last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Username            string `json:"username"`
	PasswordHash        string `json:"password_hash"`
	FullName            string `json:"full_name"`
	ForcePasswordChange bool   `json:"force_password_change"`
}

type CreateUserRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.ForcePasswordChange,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUser = `-- name: GetUser :one

SELECT id, username, full_name, telegram_user_id,
       telegram_linked_at, force_password_change, active,
       last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// =============================================================================
// SECTION 12 — USERS
// =============================================================================
func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, username, full_name, telegram_user_id,
       telegram_linked_at, force_password_change, active,
       last_login_at, created_at, updated_at
FROM users
WHERE telegram_user_id = $1
  AND active = TRUE
`

type GetUserByTelegramIDRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramUserID pgtype.Int8) (GetUserByTelegramIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramUserID)
	var i GetUserByTelegramIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, full_name, telegram_user_id, telegram_linked_at, force_password_change, active, last_login_at, created_at, updated_at
FROM users
WHERE username = $1
`

// Used during login — includes password_hash for bcrypt comparison.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const linkTelegramAccount = `-- name: LinkTelegramAccount :exec
UPDATE users
SET
    telegram_user_id   = $2,
    telegram_linked_at = NOW(),
    updated_at         = NOW()
WHERE id = $1
`

type LinkTelegramAccountParams struct {
	ID             int64       `json:"id"`
	TelegramUserID pgtype.Int8 `json:"telegram_user_id"`
}

func (q *Queries) LinkTelegramAccount(ctx context.Context, arg LinkTelegramAccountParams) error {
	_, err := q.db.Exec(ctx, linkTelegramAccount, arg.ID, arg.TelegramUserID)
	return err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username, full_name, telegram_user_id,
       telegram_linked_at, force_password_change, active,
       last_login_at, created_at, updated_at
FROM users
WHERE active = TRUE
ORDER BY full_name
`

type ListActiveUsersRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUsersRow{}
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.TelegramUserID,
			&i.TelegramLinkedAt,
			&i.ForcePasswordChange,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, full_name, telegram_user_id,
       telegram_linked_at, force_password_change, active,
       last_login_at, created_at, updated_at
FROM users
ORDER BY full_name
`

type ListUsersRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.TelegramUserID,
			&i.TelegramLinkedAt,
			&i.ForcePasswordChange,
			&i.Active,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserLogin = `-- name: RecordUserLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RecordUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordUserLogin, id)
	return err
}

const setForcePasswordChange = `-- name: SetForcePasswordChange :exec
UPDATE users
SET force_password_change = TRUE, updated_at = NOW()
WHERE id = $1
`

// Called by admin password reset flow before sending temp password via Telegram.
func (q *Queries) SetForcePasswordChange(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setForcePasswordChange, id)
	return err
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET
    active     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, full_name, telegram_user_id,
          telegram_linked_at, force_password_change, active,
          last_login_at, created_at, updated_at
`

type SetUserActiveParams struct {
	ID     int64 `json:"id"`
	Active bool  `json:"active"`
}

type SetUserActiveRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (SetUserActiveRow, error) {
	row := q.db.QueryRow(ctx, setUserActive, arg.ID, arg.Active)
	var i SetUserActiveRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkTelegramAccount = `-- name: UnlinkTelegramAccount :exec
UPDATE users
SET
    telegram_user_id   = NULL,
    telegram_linked_at = NULL,
    updated_at         = NOW()
WHERE id = $1
`

func (q *Queries) UnlinkTelegramAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, unlinkTelegramAccount, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username   = $2,
    full_name  = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, full_name, telegram_user_id,
          telegram_linked_at, force_password_change, active,
          last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	FullName string `json:"full_name"`
}

type UpdateUserRow struct {
	ID                  int64              `json:"id"`
	Username            string             `json:"username"`
	FullName            string             `json:"full_name"`
	TelegramUserID      pgtype.Int8        `json:"telegram_user_id"`
	TelegramLinkedAt    pgtype.Timestamptz `json:"telegram_linked_at"`
	ForcePasswordChange bool               `json:"force_password_change"`
	Active              bool               `json:"active"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Username, arg.FullName)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.TelegramUserID,
		&i.TelegramLinkedAt,
		&i.ForcePasswordChange,
		&i.Active,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash          = $2,
    force_password_change  = FALSE,
    updated_at             = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
