// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_role_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserHasCompanyRole = `-- name: CheckUserHasCompanyRole :one
SELECT EXISTS (
    SELECT 1
    FROM user_role_grants
    WHERE user_id    = $1
      AND role       = $2
      AND scope_type = 'COMPANY'
      AND revoked_at IS NULL
) AS has_role
`

type CheckUserHasCompanyRoleParams struct {
	UserID int64     `json:"user_id"`
	Role   UserRoleT `json:"role"`
}

func (q *Queries) CheckUserHasCompanyRole(ctx context.Context, arg CheckUserHasCompanyRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasCompanyRole, arg.UserID, arg.Role)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const checkUserHasRoleInScope = `-- name: CheckUserHasRoleInScope :one
SELECT EXISTS (
    SELECT 1
    FROM user_role_grants
    WHERE user_id    = $1
      AND role       = $2
      AND scope_type = $3
      AND scope_id   = $4
      AND revoked_at IS NULL
) AS has_role
`

type CheckUserHasRoleInScopeParams struct {
	UserID    int64       `json:"user_id"`
	Role      UserRoleT   `json:"role"`
	ScopeType RoleScopeT  `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

// Returns TRUE if the user has the given role active for the given scope.
func (q *Queries) CheckUserHasRoleInScope(ctx context.Context, arg CheckUserHasRoleInScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasRoleInScope,
		arg.UserID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
	)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}

const getActiveRoleForUserAndScope = `-- name: GetActiveRoleForUserAndScope :one
SELECT id, user_id, role, scope_type, scope_id, granted_by, granted_at, revoked_at
FROM user_role_grants
WHERE user_id    = $1
  AND role       = $2
  AND scope_type = $3
  AND scope_id   = $4
  AND revoked_at IS NULL
`

type GetActiveRoleForUserAndScopeParams struct {
	UserID    int64       `json:"user_id"`
	Role      UserRoleT   `json:"role"`
	ScopeType RoleScopeT  `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

func (q *Queries) GetActiveRoleForUserAndScope(ctx context.Context, arg GetActiveRoleForUserAndScopeParams) (UserRoleGrant, error) {
	row := q.db.QueryRow(ctx, getActiveRoleForUserAndScope,
		arg.UserID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i UserRoleGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveRolesForUser = `-- name: GetActiveRolesForUser :many

SELECT id, user_id, role, scope_type, scope_id, granted_by, granted_at, revoked_at
FROM user_role_grants
WHERE user_id    = $1
  AND revoked_at IS NULL
ORDER BY role, scope_type
`

// =============================================================================
// SECTION 13 — USER ROLE GRANTS
// =============================================================================
func (q *Queries) GetActiveRolesForUser(ctx context.Context, userID int64) ([]UserRoleGrant, error) {
	rows, err := q.db.Query(ctx, getActiveRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRoleGrant{}
	for rows.Next() {
		var i UserRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.ScopeType,
			&i.ScopeID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantRole = `-- name: GrantRole :one
INSERT INTO user_role_grants (user_id, role, scope_type, scope_id, granted_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, role, scope_type, scope_id)
DO UPDATE SET
    revoked_at = NULL,
    granted_by = EXCLUDED.granted_by,
    granted_at = NOW()
RETURNING id, user_id, role, scope_type, scope_id, granted_by, granted_at, revoked_at
`

type GrantRoleParams struct {
	UserID    int64       `json:"user_id"`
	Role      UserRoleT   `json:"role"`
	ScopeType RoleScopeT  `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
	GrantedBy pgtype.Int8 `json:"granted_by"`
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (UserRoleGrant, error) {
	row := q.db.QueryRow(ctx, grantRole,
		arg.UserID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
		arg.GrantedBy,
	)
	var i UserRoleGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.ScopeType,
		&i.ScopeID,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUsersWithRoleInScope = `-- name: ListUsersWithRoleInScope :many
SELECT
    u.id,
    u.username,
    u.full_name,
    u.telegram_user_id,
    u.active,
    urg.granted_at
FROM user_role_grants urg
JOIN users u ON u.id = urg.user_id
WHERE urg.role       = $1
  AND urg.scope_type = $2
  AND urg.scope_id   = $3
  AND urg.revoked_at IS NULL
  AND u.active       = TRUE
ORDER BY u.full_name
`

type ListUsersWithRoleInScopeParams struct {
	Role      UserRoleT   `json:"role"`
	ScopeType RoleScopeT  `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

type ListUsersWithRoleInScopeRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	FullName       string             `json:"full_name"`
	TelegramUserID pgtype.Int8        `json:"telegram_user_id"`
	Active         bool               `json:"active"`
	GrantedAt      pgtype.Timestamptz `json:"granted_at"`
}

func (q *Queries) ListUsersWithRoleInScope(ctx context.Context, arg ListUsersWithRoleInScopeParams) ([]ListUsersWithRoleInScopeRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRoleInScope, arg.Role, arg.ScopeType, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithRoleInScopeRow{}
	for rows.Next() {
		var i ListUsersWithRoleInScopeRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.TelegramUserID,
			&i.Active,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllRolesForUser = `-- name: RevokeAllRolesForUser :exec
UPDATE user_role_grants
SET revoked_at = NOW()
WHERE user_id    = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRolesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllRolesForUser, userID)
	return err
}

const revokeRole = `-- name: RevokeRole :exec
UPDATE user_role_grants
SET revoked_at = NOW()
WHERE user_id    = $1
  AND role       = $2
  AND scope_type = $3
  AND scope_id   = $4
  AND revoked_at IS NULL
`

type RevokeRoleParams struct {
	UserID    int64       `json:"user_id"`
	Role      UserRoleT   `json:"role"`
	ScopeType RoleScopeT  `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole,
		arg.UserID,
		arg.Role,
		arg.ScopeType,
		arg.ScopeID,
	)
	return err
}
