// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    plate_number, chassis_number, model, manufacture_year,
    total_capacity_l, tare_weight_kg, current_depot_id,
    keur_number, keur_expiry
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, plate_number, chassis_number, model, manufacture_year, total_capacity_l, tare_weight_kg, current_depot_id, current_location, status, keur_number, keur_expiry, last_inspection_date, next_inspection_due, last_assigned_at, notes, active, created_at, updated_at
`

type CreateVehicleParams struct {
	PlateNumber     string         `json:"plate_number"`
	ChassisNumber   string         `json:"chassis_number"`
	Model           pgtype.Text    `json:"model"`
	ManufactureYear pgtype.Int2    `json:"manufacture_year"`
	TotalCapacityL  pgtype.Numeric `json:"total_capacity_l"`
	TareWeightKg    pgtype.Numeric `json:"tare_weight_kg"`
	CurrentDepotID  pgtype.Int8    `json:"current_depot_id"`
	KeurNumber      pgtype.Text    `json:"keur_number"`
	KeurExpiry      pgtype.Date    `json:"keur_expiry"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.PlateNumber,
		arg.ChassisNumber,
		arg.Model,
		arg.ManufactureYear,
		arg.TotalCapacityL,
		arg.TareWeightKg,
		arg.CurrentDepotID,
		arg.KeurNumber,
		arg.KeurExpiry,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.ChassisNumber,
		&i.Model,
		&i.ManufactureYear,
		&i.TotalCapacityL,
		&i.TareWeightKg,
		&i.CurrentDepotID,
		&i.CurrentLocation,
		&i.Status,
		&i.KeurNumber,
		&i.KeurExpiry,
		&i.LastInspectionDate,
		&i.NextInspectionDue,
		&i.LastAssignedAt,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVehicle = `-- name: DeactivateVehicle :exec
UPDATE vehicles
SET active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateVehicle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one

SELECT
    v.id, v.plate_number, v.chassis_number, v.model, v.manufacture_year, v.total_capacity_l, v.tare_weight_kg, v.current_depot_id, v.current_location, v.status, v.keur_number, v.keur_expiry, v.last_inspection_date, v.next_inspection_due, v.last_assigned_at, v.notes, v.active, v.created_at, v.updated_at,
    ST_X(v.current_location) AS current_longitude,
    ST_Y(v.current_location) AS current_latitude
FROM vehicles v
WHERE v.id = $1
`

type GetVehicleRow struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentLongitude   interface{}        `json:"current_longitude"`
	CurrentLatitude    interface{}        `json:"current_latitude"`
}

// =============================================================================
// SECTION 9 — VEHICLES
// =============================================================================
func (q *Queries) GetVehicle(ctx context.Context, id int64) (GetVehicleRow, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i GetVehicleRow
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.ChassisNumber,
		&i.Model,
		&i.ManufactureYear,
		&i.TotalCapacityL,
		&i.TareWeightKg,
		&i.CurrentDepotID,
		&i.CurrentLocation,
		&i.Status,
		&i.KeurNumber,
		&i.KeurExpiry,
		&i.LastInspectionDate,
		&i.NextInspectionDue,
		&i.LastAssignedAt,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentLongitude,
		&i.CurrentLatitude,
	)
	return i, err
}

const getVehicleByPlate = `-- name: GetVehicleByPlate :one
SELECT
    v.id, v.plate_number, v.chassis_number, v.model, v.manufacture_year, v.total_capacity_l, v.tare_weight_kg, v.current_depot_id, v.current_location, v.status, v.keur_number, v.keur_expiry, v.last_inspection_date, v.next_inspection_due, v.last_assigned_at, v.notes, v.active, v.created_at, v.updated_at,
    ST_X(v.current_location) AS current_longitude,
    ST_Y(v.current_location) AS current_latitude
FROM vehicles v
WHERE v.plate_number = $1
`

type GetVehicleByPlateRow struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentLongitude   interface{}        `json:"current_longitude"`
	CurrentLatitude    interface{}        `json:"current_latitude"`
}

func (q *Queries) GetVehicleByPlate(ctx context.Context, plateNumber string) (GetVehicleByPlateRow, error) {
	row := q.db.QueryRow(ctx, getVehicleByPlate, plateNumber)
	var i GetVehicleByPlateRow
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.ChassisNumber,
		&i.Model,
		&i.ManufactureYear,
		&i.TotalCapacityL,
		&i.TareWeightKg,
		&i.CurrentDepotID,
		&i.CurrentLocation,
		&i.Status,
		&i.KeurNumber,
		&i.KeurExpiry,
		&i.LastInspectionDate,
		&i.NextInspectionDue,
		&i.LastAssignedAt,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentLongitude,
		&i.CurrentLatitude,
	)
	return i, err
}

const listDispatchCandidateVehicles = `-- name: ListDispatchCandidateVehicles :many
SELECT
    v.id,
    v.plate_number,
    v.total_capacity_l,
    v.tare_weight_kg,
    v.keur_expiry,
    v.current_depot_id,
    ST_X(v.current_location)  AS current_longitude,
    ST_Y(v.current_location)  AS current_latitude,
    (d.primary_facility_id = $1)::BOOLEAN  AS depot_matched,
    ROUND(
        (ST_Distance(
            v.current_location::GEOGRAPHY,
            f.location::GEOGRAPHY
        ) / 1000)::NUMERIC, 2
    ) AS distance_km
FROM vehicles v
JOIN refinery_facilities f ON f.id = $1
LEFT JOIN vehicle_depots  d ON d.id = v.current_depot_id
WHERE v.status   = 'AVAILABLE'
  AND v.active   = TRUE
  AND v.keur_expiry > CURRENT_DATE
  AND ST_DWithin(
        v.current_location::GEOGRAPHY,
        f.location::GEOGRAPHY,
        f.max_assignment_radius_km * 1000
      )
ORDER BY
    depot_matched DESC,
    distance_km   ASC,
    v.last_assigned_at ASC NULLS FIRST
LIMIT $2
`

type ListDispatchCandidateVehiclesParams struct {
	PrimaryFacilityID int64 `json:"primary_facility_id"`
	Limit             int32 `json:"limit"`
}

type ListDispatchCandidateVehiclesRow struct {
	ID               int64           `json:"id"`
	PlateNumber      string          `json:"plate_number"`
	TotalCapacityL   pgtype.Numeric  `json:"total_capacity_l"`
	TareWeightKg     pgtype.Numeric  `json:"tare_weight_kg"`
	KeurExpiry       pgtype.Date     `json:"keur_expiry"`
	CurrentDepotID   pgtype.Int8     `json:"current_depot_id"`
	CurrentLongitude interface{}     `json:"current_longitude"`
	CurrentLatitude  interface{}     `json:"current_latitude"`
	DepotMatched     bool            `json:"depot_matched"`
	DistanceKm       decimal.Decimal `json:"distance_km"`
}

// Primary dispatch query. Finds available trucks near a facility ordered by:
// 1. Depot proximity to origin facility (home depot first)
// 2. Distance from current GPS location to facility
// 3. Least recently assigned (fairness)
// Returns up to $2 candidates. Caller filters by required fuel type separately.
func (q *Queries) ListDispatchCandidateVehicles(ctx context.Context, arg ListDispatchCandidateVehiclesParams) ([]ListDispatchCandidateVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listDispatchCandidateVehicles, arg.PrimaryFacilityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDispatchCandidateVehiclesRow{}
	for rows.Next() {
		var i ListDispatchCandidateVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.TotalCapacityL,
			&i.TareWeightKg,
			&i.KeurExpiry,
			&i.CurrentDepotID,
			&i.CurrentLongitude,
			&i.CurrentLatitude,
			&i.DepotMatched,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByDepot = `-- name: ListVehiclesByDepot :many
SELECT
    v.id, v.plate_number, v.chassis_number, v.model, v.manufacture_year, v.total_capacity_l, v.tare_weight_kg, v.current_depot_id, v.current_location, v.status, v.keur_number, v.keur_expiry, v.last_inspection_date, v.next_inspection_due, v.last_assigned_at, v.notes, v.active, v.created_at, v.updated_at,
    ST_X(v.current_location) AS current_longitude,
    ST_Y(v.current_location) AS current_latitude
FROM vehicles v
WHERE v.current_depot_id = $1
  AND v.active = TRUE
ORDER BY v.plate_number
`

type ListVehiclesByDepotRow struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentLongitude   interface{}        `json:"current_longitude"`
	CurrentLatitude    interface{}        `json:"current_latitude"`
}

func (q *Queries) ListVehiclesByDepot(ctx context.Context, currentDepotID pgtype.Int8) ([]ListVehiclesByDepotRow, error) {
	rows, err := q.db.Query(ctx, listVehiclesByDepot, currentDepotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesByDepotRow{}
	for rows.Next() {
		var i ListVehiclesByDepotRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.ChassisNumber,
			&i.Model,
			&i.ManufactureYear,
			&i.TotalCapacityL,
			&i.TareWeightKg,
			&i.CurrentDepotID,
			&i.CurrentLocation,
			&i.Status,
			&i.KeurNumber,
			&i.KeurExpiry,
			&i.LastInspectionDate,
			&i.NextInspectionDue,
			&i.LastAssignedAt,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentLongitude,
			&i.CurrentLatitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByStatus = `-- name: ListVehiclesByStatus :many
SELECT
    v.id, v.plate_number, v.chassis_number, v.model, v.manufacture_year, v.total_capacity_l, v.tare_weight_kg, v.current_depot_id, v.current_location, v.status, v.keur_number, v.keur_expiry, v.last_inspection_date, v.next_inspection_due, v.last_assigned_at, v.notes, v.active, v.created_at, v.updated_at,
    ST_X(v.current_location) AS current_longitude,
    ST_Y(v.current_location) AS current_latitude
FROM vehicles v
WHERE v.status = $1
  AND v.active = TRUE
ORDER BY v.plate_number
`

type ListVehiclesByStatusRow struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentLongitude   interface{}        `json:"current_longitude"`
	CurrentLatitude    interface{}        `json:"current_latitude"`
}

func (q *Queries) ListVehiclesByStatus(ctx context.Context, status VehicleStatusT) ([]ListVehiclesByStatusRow, error) {
	rows, err := q.db.Query(ctx, listVehiclesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesByStatusRow{}
	for rows.Next() {
		var i ListVehiclesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.ChassisNumber,
			&i.Model,
			&i.ManufactureYear,
			&i.TotalCapacityL,
			&i.TareWeightKg,
			&i.CurrentDepotID,
			&i.CurrentLocation,
			&i.Status,
			&i.KeurNumber,
			&i.KeurExpiry,
			&i.LastInspectionDate,
			&i.NextInspectionDue,
			&i.LastAssignedAt,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentLongitude,
			&i.CurrentLatitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesWithExpiringKeur = `-- name: ListVehiclesWithExpiringKeur :many
SELECT
    v.id, v.plate_number, v.chassis_number, v.model, v.manufacture_year, v.total_capacity_l, v.tare_weight_kg, v.current_depot_id, v.current_location, v.status, v.keur_number, v.keur_expiry, v.last_inspection_date, v.next_inspection_due, v.last_assigned_at, v.notes, v.active, v.created_at, v.updated_at,
    ST_X(v.current_location) AS current_longitude,
    ST_Y(v.current_location) AS current_latitude
FROM vehicles v
WHERE v.active = TRUE
  AND v.keur_expiry BETWEEN CURRENT_DATE AND (CURRENT_DATE + INTERVAL '30 days')
ORDER BY v.keur_expiry ASC
`

type ListVehiclesWithExpiringKeurRow struct {
	ID                 int64              `json:"id"`
	PlateNumber        string             `json:"plate_number"`
	ChassisNumber      string             `json:"chassis_number"`
	Model              pgtype.Text        `json:"model"`
	ManufactureYear    pgtype.Int2        `json:"manufacture_year"`
	TotalCapacityL     pgtype.Numeric     `json:"total_capacity_l"`
	TareWeightKg       pgtype.Numeric     `json:"tare_weight_kg"`
	CurrentDepotID     pgtype.Int8        `json:"current_depot_id"`
	CurrentLocation    interface{}        `json:"current_location"`
	Status             VehicleStatusT     `json:"status"`
	KeurNumber         pgtype.Text        `json:"keur_number"`
	KeurExpiry         pgtype.Date        `json:"keur_expiry"`
	LastInspectionDate pgtype.Date        `json:"last_inspection_date"`
	NextInspectionDue  pgtype.Date        `json:"next_inspection_due"`
	LastAssignedAt     pgtype.Timestamptz `json:"last_assigned_at"`
	Notes              pgtype.Text        `json:"notes"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CurrentLongitude   interface{}        `json:"current_longitude"`
	CurrentLatitude    interface{}        `json:"current_latitude"`
}

// Used for 30-day advance expiry notification.
func (q *Queries) ListVehiclesWithExpiringKeur(ctx context.Context) ([]ListVehiclesWithExpiringKeurRow, error) {
	rows, err := q.db.Query(ctx, listVehiclesWithExpiringKeur)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesWithExpiringKeurRow{}
	for rows.Next() {
		var i ListVehiclesWithExpiringKeurRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateNumber,
			&i.ChassisNumber,
			&i.Model,
			&i.ManufactureYear,
			&i.TotalCapacityL,
			&i.TareWeightKg,
			&i.CurrentDepotID,
			&i.CurrentLocation,
			&i.Status,
			&i.KeurNumber,
			&i.KeurExpiry,
			&i.LastInspectionDate,
			&i.NextInspectionDue,
			&i.LastAssignedAt,
			&i.Notes,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentLongitude,
			&i.CurrentLatitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVehicleLastAssigned = `-- name: MarkVehicleLastAssigned :exec
UPDATE vehicles
SET last_assigned_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkVehicleLastAssigned(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markVehicleLastAssigned, id)
	return err
}

const updateVehicleDepot = `-- name: UpdateVehicleDepot :exec
UPDATE vehicles
SET current_depot_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateVehicleDepotParams struct {
	ID             int64       `json:"id"`
	CurrentDepotID pgtype.Int8 `json:"current_depot_id"`
}

func (q *Queries) UpdateVehicleDepot(ctx context.Context, arg UpdateVehicleDepotParams) error {
	_, err := q.db.Exec(ctx, updateVehicleDepot, arg.ID, arg.CurrentDepotID)
	return err
}

const updateVehicleKeurDetails = `-- name: UpdateVehicleKeurDetails :one
UPDATE vehicles
SET
    keur_number  = $2,
    keur_expiry  = $3,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, plate_number, chassis_number, model, manufacture_year, total_capacity_l, tare_weight_kg, current_depot_id, current_location, status, keur_number, keur_expiry, last_inspection_date, next_inspection_due, last_assigned_at, notes, active, created_at, updated_at
`

type UpdateVehicleKeurDetailsParams struct {
	ID         int64       `json:"id"`
	KeurNumber pgtype.Text `json:"keur_number"`
	KeurExpiry pgtype.Date `json:"keur_expiry"`
}

func (q *Queries) UpdateVehicleKeurDetails(ctx context.Context, arg UpdateVehicleKeurDetailsParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicleKeurDetails, arg.ID, arg.KeurNumber, arg.KeurExpiry)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.ChassisNumber,
		&i.Model,
		&i.ManufactureYear,
		&i.TotalCapacityL,
		&i.TareWeightKg,
		&i.CurrentDepotID,
		&i.CurrentLocation,
		&i.Status,
		&i.KeurNumber,
		&i.KeurExpiry,
		&i.LastInspectionDate,
		&i.NextInspectionDue,
		&i.LastAssignedAt,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVehicleLocation = `-- name: UpdateVehicleLocation :exec
UPDATE vehicles
SET
    current_location = ST_SetSRID(ST_MakePoint($2, $3), 4326),
    updated_at       = NOW()
WHERE id = $1
`

type UpdateVehicleLocationParams struct {
	ID            int64       `json:"id"`
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

func (q *Queries) UpdateVehicleLocation(ctx context.Context, arg UpdateVehicleLocationParams) error {
	_, err := q.db.Exec(ctx, updateVehicleLocation, arg.ID, arg.StMakepoint, arg.StMakepoint_2)
	return err
}

const updateVehicleStatus = `-- name: UpdateVehicleStatus :one
UPDATE vehicles
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, plate_number, chassis_number, model, manufacture_year, total_capacity_l, tare_weight_kg, current_depot_id, current_location, status, keur_number, keur_expiry, last_inspection_date, next_inspection_due, last_assigned_at, notes, active, created_at, updated_at
`

type UpdateVehicleStatusParams struct {
	ID     int64          `json:"id"`
	Status VehicleStatusT `json:"status"`
}

func (q *Queries) UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicleStatus, arg.ID, arg.Status)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.PlateNumber,
		&i.ChassisNumber,
		&i.Model,
		&i.ManufactureYear,
		&i.TotalCapacityL,
		&i.TareWeightKg,
		&i.CurrentDepotID,
		&i.CurrentLocation,
		&i.Status,
		&i.KeurNumber,
		&i.KeurExpiry,
		&i.LastInspectionDate,
		&i.NextInspectionDue,
		&i.LastAssignedAt,
		&i.Notes,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
