// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_maintenance_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMaintenanceRecord = `-- name: CompleteMaintenanceRecord :one
UPDATE vehicle_maintenance_records
SET
    completed_at = NOW(),
    notes        = COALESCE($2, notes)
WHERE id = $1
RETURNING id, vehicle_id, recorded_by, maintenance_type, description, started_at, estimated_return_at, completed_at, notes, created_at
`

type CompleteMaintenanceRecordParams struct {
	ID    int64       `json:"id"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) CompleteMaintenanceRecord(ctx context.Context, arg CompleteMaintenanceRecordParams) (VehicleMaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, completeMaintenanceRecord, arg.ID, arg.Notes)
	var i VehicleMaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.RecordedBy,
		&i.MaintenanceType,
		&i.Description,
		&i.StartedAt,
		&i.EstimatedReturnAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createMaintenanceRecord = `-- name: CreateMaintenanceRecord :one
INSERT INTO vehicle_maintenance_records (
    vehicle_id, recorded_by, maintenance_type,
    description, started_at, estimated_return_at, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, vehicle_id, recorded_by, maintenance_type, description, started_at, estimated_return_at, completed_at, notes, created_at
`

type CreateMaintenanceRecordParams struct {
	VehicleID         int64              `json:"vehicle_id"`
	RecordedBy        pgtype.Int8        `json:"recorded_by"`
	MaintenanceType   string             `json:"maintenance_type"`
	Description       pgtype.Text        `json:"description"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EstimatedReturnAt pgtype.Timestamptz `json:"estimated_return_at"`
	Notes             pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (VehicleMaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecord,
		arg.VehicleID,
		arg.RecordedBy,
		arg.MaintenanceType,
		arg.Description,
		arg.StartedAt,
		arg.EstimatedReturnAt,
		arg.Notes,
	)
	var i VehicleMaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.RecordedBy,
		&i.MaintenanceType,
		&i.Description,
		&i.StartedAt,
		&i.EstimatedReturnAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getMaintenanceRecord = `-- name: GetMaintenanceRecord :one

SELECT id, vehicle_id, recorded_by, maintenance_type, description, started_at, estimated_return_at, completed_at, notes, created_at
FROM vehicle_maintenance_records
WHERE id = $1
`

// =============================================================================
// SECTION 11 — VEHICLE MAINTENANCE RECORDS
// =============================================================================
func (q *Queries) GetMaintenanceRecord(ctx context.Context, id int64) (VehicleMaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRecord, id)
	var i VehicleMaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.RecordedBy,
		&i.MaintenanceType,
		&i.Description,
		&i.StartedAt,
		&i.EstimatedReturnAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listAllOpenMaintenance = `-- name: ListAllOpenMaintenance :many
SELECT
    vmr.id, vmr.vehicle_id, vmr.recorded_by, vmr.maintenance_type, vmr.description, vmr.started_at, vmr.estimated_return_at, vmr.completed_at, vmr.notes, vmr.created_at,
    v.plate_number,
    vd.name AS depot_name
FROM vehicle_maintenance_records vmr
JOIN vehicles       v  ON v.id  = vmr.vehicle_id
JOIN vehicle_depots vd ON vd.id = v.current_depot_id
WHERE vmr.completed_at IS NULL
ORDER BY vmr.started_at ASC
`

type ListAllOpenMaintenanceRow struct {
	ID                int64              `json:"id"`
	VehicleID         int64              `json:"vehicle_id"`
	RecordedBy        pgtype.Int8        `json:"recorded_by"`
	MaintenanceType   string             `json:"maintenance_type"`
	Description       pgtype.Text        `json:"description"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	EstimatedReturnAt pgtype.Timestamptz `json:"estimated_return_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	PlateNumber       string             `json:"plate_number"`
	DepotName         string             `json:"depot_name"`
}

func (q *Queries) ListAllOpenMaintenance(ctx context.Context) ([]ListAllOpenMaintenanceRow, error) {
	rows, err := q.db.Query(ctx, listAllOpenMaintenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllOpenMaintenanceRow{}
	for rows.Next() {
		var i ListAllOpenMaintenanceRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.RecordedBy,
			&i.MaintenanceType,
			&i.Description,
			&i.StartedAt,
			&i.EstimatedReturnAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.PlateNumber,
			&i.DepotName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceByVehicle = `-- name: ListMaintenanceByVehicle :many
SELECT id, vehicle_id, recorded_by, maintenance_type, description, started_at, estimated_return_at, completed_at, notes, created_at
FROM vehicle_maintenance_records
WHERE vehicle_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListMaintenanceByVehicle(ctx context.Context, vehicleID int64) ([]VehicleMaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleMaintenanceRecord{}
	for rows.Next() {
		var i VehicleMaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.RecordedBy,
			&i.MaintenanceType,
			&i.Description,
			&i.StartedAt,
			&i.EstimatedReturnAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenMaintenanceByVehicle = `-- name: ListOpenMaintenanceByVehicle :many
SELECT id, vehicle_id, recorded_by, maintenance_type, description, started_at, estimated_return_at, completed_at, notes, created_at
FROM vehicle_maintenance_records
WHERE vehicle_id   = $1
  AND completed_at IS NULL
ORDER BY started_at DESC
`

func (q *Queries) ListOpenMaintenanceByVehicle(ctx context.Context, vehicleID int64) ([]VehicleMaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listOpenMaintenanceByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleMaintenanceRecord{}
	for rows.Next() {
		var i VehicleMaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.RecordedBy,
			&i.MaintenanceType,
			&i.Description,
			&i.StartedAt,
			&i.EstimatedReturnAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
