// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_compartments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompartment = `-- name: CreateCompartment :one
INSERT INTO vehicle_compartments (
    vehicle_id, compartment_number, fuel_type_code, capacity_l
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
`

type CreateCompartmentParams struct {
	VehicleID         int64          `json:"vehicle_id"`
	CompartmentNumber int16          `json:"compartment_number"`
	FuelTypeCode      pgtype.Text    `json:"fuel_type_code"`
	CapacityL         pgtype.Numeric `json:"capacity_l"`
}

func (q *Queries) CreateCompartment(ctx context.Context, arg CreateCompartmentParams) (VehicleCompartment, error) {
	row := q.db.QueryRow(ctx, createCompartment,
		arg.VehicleID,
		arg.CompartmentNumber,
		arg.FuelTypeCode,
		arg.CapacityL,
	)
	var i VehicleCompartment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.CompartmentNumber,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCompartment = `-- name: DeactivateCompartment :exec
UPDATE vehicle_compartments
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateCompartment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateCompartment, id)
	return err
}

const getCompartment = `-- name: GetCompartment :one

SELECT id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
FROM vehicle_compartments
WHERE id = $1
`

// =============================================================================
// SECTION 10 — VEHICLE COMPARTMENTS
// =============================================================================
func (q *Queries) GetCompartment(ctx context.Context, id int64) (VehicleCompartment, error) {
	row := q.db.QueryRow(ctx, getCompartment, id)
	var i VehicleCompartment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.CompartmentNumber,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalCapacityByVehicle = `-- name: GetTotalCapacityByVehicle :one
SELECT
    vehicle_id,
    COUNT(*)                   AS compartment_count,
    SUM(capacity_l)            AS total_capacity_l
FROM vehicle_compartments
WHERE vehicle_id = $1
  AND is_active = TRUE
GROUP BY vehicle_id
`

type GetTotalCapacityByVehicleRow struct {
	VehicleID        int64 `json:"vehicle_id"`
	CompartmentCount int64 `json:"compartment_count"`
	TotalCapacityL   int64 `json:"total_capacity_l"`
}

func (q *Queries) GetTotalCapacityByVehicle(ctx context.Context, vehicleID int64) (GetTotalCapacityByVehicleRow, error) {
	row := q.db.QueryRow(ctx, getTotalCapacityByVehicle, vehicleID)
	var i GetTotalCapacityByVehicleRow
	err := row.Scan(&i.VehicleID, &i.CompartmentCount, &i.TotalCapacityL)
	return i, err
}

const listAllCompartmentsByVehicle = `-- name: ListAllCompartmentsByVehicle :many
SELECT id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
FROM vehicle_compartments
WHERE vehicle_id = $1
ORDER BY compartment_number
`

// Includes inactive compartments (admin view).
func (q *Queries) ListAllCompartmentsByVehicle(ctx context.Context, vehicleID int64) ([]VehicleCompartment, error) {
	rows, err := q.db.Query(ctx, listAllCompartmentsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleCompartment{}
	for rows.Next() {
		var i VehicleCompartment
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.CompartmentNumber,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompartmentsByVehicle = `-- name: ListCompartmentsByVehicle :many
SELECT id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
FROM vehicle_compartments
WHERE vehicle_id = $1
  AND is_active = TRUE
ORDER BY compartment_number
`

func (q *Queries) ListCompartmentsByVehicle(ctx context.Context, vehicleID int64) ([]VehicleCompartment, error) {
	rows, err := q.db.Query(ctx, listCompartmentsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleCompartment{}
	for rows.Next() {
		var i VehicleCompartment
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.CompartmentNumber,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompartmentsByVehicleAndFuel = `-- name: ListCompartmentsByVehicleAndFuel :many
SELECT id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
FROM vehicle_compartments
WHERE vehicle_id      = $1
  AND fuel_type_code  = $2
  AND is_active       = TRUE
ORDER BY compartment_number
`

type ListCompartmentsByVehicleAndFuelParams struct {
	VehicleID    int64       `json:"vehicle_id"`
	FuelTypeCode pgtype.Text `json:"fuel_type_code"`
}

func (q *Queries) ListCompartmentsByVehicleAndFuel(ctx context.Context, arg ListCompartmentsByVehicleAndFuelParams) ([]VehicleCompartment, error) {
	rows, err := q.db.Query(ctx, listCompartmentsByVehicleAndFuel, arg.VehicleID, arg.FuelTypeCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleCompartment{}
	for rows.Next() {
		var i VehicleCompartment
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.CompartmentNumber,
			&i.FuelTypeCode,
			&i.CapacityL,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompartmentFuelType = `-- name: UpdateCompartmentFuelType :one
UPDATE vehicle_compartments
SET
    fuel_type_code = $2,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, vehicle_id, compartment_number, fuel_type_code, capacity_l, is_active, created_at, updated_at
`

type UpdateCompartmentFuelTypeParams struct {
	ID           int64       `json:"id"`
	FuelTypeCode pgtype.Text `json:"fuel_type_code"`
}

func (q *Queries) UpdateCompartmentFuelType(ctx context.Context, arg UpdateCompartmentFuelTypeParams) (VehicleCompartment, error) {
	row := q.db.QueryRow(ctx, updateCompartmentFuelType, arg.ID, arg.FuelTypeCode)
	var i VehicleCompartment
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.CompartmentNumber,
		&i.FuelTypeCode,
		&i.CapacityL,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
