// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_depots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepot = `-- name: CreateDepot :one
INSERT INTO vehicle_depots (
    code, name, primary_facility_id, location, default_truck_capacity_l
) VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_MakePoint($4, $5), 4326),
    $6
)
RETURNING id, code, name, primary_facility_id, location, default_truck_capacity_l, active, created_at, updated_at
`

type CreateDepotParams struct {
	Code                  string      `json:"code"`
	Name                  string      `json:"name"`
	PrimaryFacilityID     int64       `json:"primary_facility_id"`
	StMakepoint           interface{} `json:"st_makepoint"`
	StMakepoint_2         interface{} `json:"st_makepoint_2"`
	DefaultTruckCapacityL int32       `json:"default_truck_capacity_l"`
}

func (q *Queries) CreateDepot(ctx context.Context, arg CreateDepotParams) (VehicleDepot, error) {
	row := q.db.QueryRow(ctx, createDepot,
		arg.Code,
		arg.Name,
		arg.PrimaryFacilityID,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.DefaultTruckCapacityL,
	)
	var i VehicleDepot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.DefaultTruckCapacityL,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepot = `-- name: GetDepot :one

SELECT
    vd.id, vd.code, vd.name, vd.primary_facility_id, vd.location, vd.default_truck_capacity_l, vd.active, vd.created_at, vd.updated_at,
    ST_X(vd.location) AS longitude,
    ST_Y(vd.location) AS latitude
FROM vehicle_depots vd
WHERE vd.id = $1
`

type GetDepotRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	PrimaryFacilityID     int64              `json:"primary_facility_id"`
	Location              interface{}        `json:"location"`
	DefaultTruckCapacityL int32              `json:"default_truck_capacity_l"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

// =============================================================================
// SECTION 6 — VEHICLE DEPOTS
// =============================================================================
func (q *Queries) GetDepot(ctx context.Context, id int64) (GetDepotRow, error) {
	row := q.db.QueryRow(ctx, getDepot, id)
	var i GetDepotRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.DefaultTruckCapacityL,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const getDepotByCode = `-- name: GetDepotByCode :one
SELECT
    vd.id, vd.code, vd.name, vd.primary_facility_id, vd.location, vd.default_truck_capacity_l, vd.active, vd.created_at, vd.updated_at,
    ST_X(vd.location) AS longitude,
    ST_Y(vd.location) AS latitude
FROM vehicle_depots vd
WHERE vd.code = $1
`

type GetDepotByCodeRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	PrimaryFacilityID     int64              `json:"primary_facility_id"`
	Location              interface{}        `json:"location"`
	DefaultTruckCapacityL int32              `json:"default_truck_capacity_l"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) GetDepotByCode(ctx context.Context, code string) (GetDepotByCodeRow, error) {
	row := q.db.QueryRow(ctx, getDepotByCode, code)
	var i GetDepotByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.DefaultTruckCapacityL,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Longitude,
		&i.Latitude,
	)
	return i, err
}

const listAllActiveDepots = `-- name: ListAllActiveDepots :many
SELECT
    vd.id, vd.code, vd.name, vd.primary_facility_id, vd.location, vd.default_truck_capacity_l, vd.active, vd.created_at, vd.updated_at,
    rf.code AS facility_code,
    rf.name AS facility_name,
    ST_X(vd.location) AS longitude,
    ST_Y(vd.location) AS latitude
FROM vehicle_depots vd
JOIN refinery_facilities rf ON rf.id = vd.primary_facility_id
WHERE vd.active = TRUE
ORDER BY rf.code, vd.name
`

type ListAllActiveDepotsRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	PrimaryFacilityID     int64              `json:"primary_facility_id"`
	Location              interface{}        `json:"location"`
	DefaultTruckCapacityL int32              `json:"default_truck_capacity_l"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	FacilityCode          string             `json:"facility_code"`
	FacilityName          string             `json:"facility_name"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) ListAllActiveDepots(ctx context.Context) ([]ListAllActiveDepotsRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveDepots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllActiveDepotsRow{}
	for rows.Next() {
		var i ListAllActiveDepotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.DefaultTruckCapacityL,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FacilityCode,
			&i.FacilityName,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepotsByFacility = `-- name: ListDepotsByFacility :many
SELECT
    vd.id, vd.code, vd.name, vd.primary_facility_id, vd.location, vd.default_truck_capacity_l, vd.active, vd.created_at, vd.updated_at,
    ST_X(vd.location) AS longitude,
    ST_Y(vd.location) AS latitude
FROM vehicle_depots vd
WHERE vd.primary_facility_id = $1
  AND vd.active = TRUE
ORDER BY vd.name
`

type ListDepotsByFacilityRow struct {
	ID                    int64              `json:"id"`
	Code                  string             `json:"code"`
	Name                  string             `json:"name"`
	PrimaryFacilityID     int64              `json:"primary_facility_id"`
	Location              interface{}        `json:"location"`
	DefaultTruckCapacityL int32              `json:"default_truck_capacity_l"`
	Active                bool               `json:"active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Longitude             interface{}        `json:"longitude"`
	Latitude              interface{}        `json:"latitude"`
}

func (q *Queries) ListDepotsByFacility(ctx context.Context, primaryFacilityID int64) ([]ListDepotsByFacilityRow, error) {
	rows, err := q.db.Query(ctx, listDepotsByFacility, primaryFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepotsByFacilityRow{}
	for rows.Next() {
		var i ListDepotsByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PrimaryFacilityID,
			&i.Location,
			&i.DefaultTruckCapacityL,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepot = `-- name: UpdateDepot :one
UPDATE vehicle_depots
SET
    name                     = $2,
    default_truck_capacity_l = $3,
    updated_at               = NOW()
WHERE id = $1
RETURNING id, code, name, primary_facility_id, location, default_truck_capacity_l, active, created_at, updated_at
`

type UpdateDepotParams struct {
	ID                    int64  `json:"id"`
	Name                  string `json:"name"`
	DefaultTruckCapacityL int32  `json:"default_truck_capacity_l"`
}

func (q *Queries) UpdateDepot(ctx context.Context, arg UpdateDepotParams) (VehicleDepot, error) {
	row := q.db.QueryRow(ctx, updateDepot, arg.ID, arg.Name, arg.DefaultTruckCapacityL)
	var i VehicleDepot
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PrimaryFacilityID,
		&i.Location,
		&i.DefaultTruckCapacityL,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
