// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weight_bridge_readings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveWeightBridgeReading = `-- name: ApproveWeightBridgeReading :one
UPDATE weight_bridge_readings
SET
    approval_status = 'APPROVED',
    approved_by     = $2,
    approved_at     = NOW()
WHERE id = $1
  AND approval_status IN ('PENDING', 'ESCALATED')
RETURNING id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
`

type ApproveWeightBridgeReadingParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
}

func (q *Queries) ApproveWeightBridgeReading(ctx context.Context, arg ApproveWeightBridgeReadingParams) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, approveWeightBridgeReading, arg.ID, arg.ApprovedBy)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createWeightBridgeReading = `-- name: CreateWeightBridgeReading :one
INSERT INTO weight_bridge_readings (
    trip_id, vehicle_id, reading_type, weight_kg,
    method, ambient_temp_celsius, recorded_by, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
`

type CreateWeightBridgeReadingParams struct {
	TripID             pgtype.Int8        `json:"trip_id"`
	VehicleID          int64              `json:"vehicle_id"`
	ReadingType        string             `json:"reading_type"`
	WeightKg           pgtype.Numeric     `json:"weight_kg"`
	Method             MeasurementMethodT `json:"method"`
	AmbientTempCelsius pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy         int64              `json:"recorded_by"`
	Notes              pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateWeightBridgeReading(ctx context.Context, arg CreateWeightBridgeReadingParams) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, createWeightBridgeReading,
		arg.TripID,
		arg.VehicleID,
		arg.ReadingType,
		arg.WeightKg,
		arg.Method,
		arg.AmbientTempCelsius,
		arg.RecordedBy,
		arg.Notes,
	)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const escalateWeightBridgeReading = `-- name: EscalateWeightBridgeReading :one
UPDATE weight_bridge_readings
SET
    approval_status = 'ESCALATED',
    escalated_at    = NOW(),
    escalated_to    = $2
WHERE id = $1
  AND approval_status = 'PENDING'
RETURNING id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
`

type EscalateWeightBridgeReadingParams struct {
	ID          int64       `json:"id"`
	EscalatedTo pgtype.Int8 `json:"escalated_to"`
}

// Called by background worker when Facility Manager window expires.
func (q *Queries) EscalateWeightBridgeReading(ctx context.Context, arg EscalateWeightBridgeReadingParams) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, escalateWeightBridgeReading, arg.ID, arg.EscalatedTo)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getGrossReadingByTrip = `-- name: GetGrossReadingByTrip :one
SELECT id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
FROM weight_bridge_readings
WHERE trip_id      = $1
  AND reading_type = 'GROSS'
`

func (q *Queries) GetGrossReadingByTrip(ctx context.Context, tripID pgtype.Int8) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, getGrossReadingByTrip, tripID)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getTareReadingByTrip = `-- name: GetTareReadingByTrip :one
SELECT id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
FROM weight_bridge_readings
WHERE trip_id      = $1
  AND reading_type = 'TARE'
`

func (q *Queries) GetTareReadingByTrip(ctx context.Context, tripID pgtype.Int8) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, getTareReadingByTrip, tripID)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getWeightBridgeReading = `-- name: GetWeightBridgeReading :one

SELECT id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
FROM weight_bridge_readings
WHERE id = $1
`

// =============================================================================
// SECTION 21 — WEIGHT BRIDGE READINGS
// =============================================================================
func (q *Queries) GetWeightBridgeReading(ctx context.Context, id int64) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, getWeightBridgeReading, id)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listEscalatedApprovals = `-- name: ListEscalatedApprovals :many
SELECT
    wbr.id, wbr.trip_id, wbr.vehicle_id, wbr.reading_type, wbr.weight_kg, wbr.method, wbr.ambient_temp_celsius, wbr.recorded_by, wbr.approval_status, wbr.approved_by, wbr.approved_at, wbr.escalated_at, wbr.escalated_to, wbr.notes, wbr.created_at,
    v.plate_number,
    u.full_name AS recorded_by_name
FROM weight_bridge_readings wbr
JOIN vehicles v ON v.id = wbr.vehicle_id
JOIN users    u ON u.id = wbr.recorded_by
WHERE wbr.method          = 'MANUAL_APPROVED'
  AND wbr.approval_status = 'ESCALATED'
ORDER BY wbr.escalated_at ASC
`

type ListEscalatedApprovalsRow struct {
	ID                 int64              `json:"id"`
	TripID             pgtype.Int8        `json:"trip_id"`
	VehicleID          int64              `json:"vehicle_id"`
	ReadingType        string             `json:"reading_type"`
	WeightKg           pgtype.Numeric     `json:"weight_kg"`
	Method             MeasurementMethodT `json:"method"`
	AmbientTempCelsius pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy         int64              `json:"recorded_by"`
	ApprovalStatus     ApprovalStatusT    `json:"approval_status"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	EscalatedAt        pgtype.Timestamptz `json:"escalated_at"`
	EscalatedTo        pgtype.Int8        `json:"escalated_to"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PlateNumber        string             `json:"plate_number"`
	RecordedByName     string             `json:"recorded_by_name"`
}

// Refinery Admin escalation queue (company-wide).
func (q *Queries) ListEscalatedApprovals(ctx context.Context) ([]ListEscalatedApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listEscalatedApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEscalatedApprovalsRow{}
	for rows.Next() {
		var i ListEscalatedApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VehicleID,
			&i.ReadingType,
			&i.WeightKg,
			&i.Method,
			&i.AmbientTempCelsius,
			&i.RecordedBy,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.Notes,
			&i.CreatedAt,
			&i.PlateNumber,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverduePendingManualApprovals = `-- name: ListOverduePendingManualApprovals :many
SELECT
    wbr.id, wbr.trip_id, wbr.vehicle_id, wbr.reading_type, wbr.weight_kg, wbr.method, wbr.ambient_temp_celsius, wbr.recorded_by, wbr.approval_status, wbr.approved_by, wbr.approved_at, wbr.escalated_at, wbr.escalated_to, wbr.notes, wbr.created_at,
    v.plate_number,
    u.full_name AS recorded_by_name
FROM weight_bridge_readings wbr
JOIN vehicles v ON v.id = wbr.vehicle_id
JOIN users    u ON u.id = wbr.recorded_by
WHERE wbr.method          = 'MANUAL_APPROVED'
  AND wbr.approval_status = 'PENDING'
  AND wbr.created_at < NOW() - make_interval(hours => $1)
ORDER BY wbr.created_at ASC
`

type ListOverduePendingManualApprovalsRow struct {
	ID                 int64              `json:"id"`
	TripID             pgtype.Int8        `json:"trip_id"`
	VehicleID          int64              `json:"vehicle_id"`
	ReadingType        string             `json:"reading_type"`
	WeightKg           pgtype.Numeric     `json:"weight_kg"`
	Method             MeasurementMethodT `json:"method"`
	AmbientTempCelsius pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy         int64              `json:"recorded_by"`
	ApprovalStatus     ApprovalStatusT    `json:"approval_status"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	EscalatedAt        pgtype.Timestamptz `json:"escalated_at"`
	EscalatedTo        pgtype.Int8        `json:"escalated_to"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PlateNumber        string             `json:"plate_number"`
	RecordedByName     string             `json:"recorded_by_name"`
}

func (q *Queries) ListOverduePendingManualApprovals(ctx context.Context, hours int32) ([]ListOverduePendingManualApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listOverduePendingManualApprovals, hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverduePendingManualApprovalsRow{}
	for rows.Next() {
		var i ListOverduePendingManualApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VehicleID,
			&i.ReadingType,
			&i.WeightKg,
			&i.Method,
			&i.AmbientTempCelsius,
			&i.RecordedBy,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.Notes,
			&i.CreatedAt,
			&i.PlateNumber,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingManualApprovals = `-- name: ListPendingManualApprovals :many
SELECT
    wbr.id, wbr.trip_id, wbr.vehicle_id, wbr.reading_type, wbr.weight_kg, wbr.method, wbr.ambient_temp_celsius, wbr.recorded_by, wbr.approval_status, wbr.approved_by, wbr.approved_at, wbr.escalated_at, wbr.escalated_to, wbr.notes, wbr.created_at,
    v.plate_number,
    u.full_name AS recorded_by_name,
    t.id AS trip_id
FROM weight_bridge_readings wbr
JOIN vehicles v ON v.id = wbr.vehicle_id
JOIN users    u ON u.id = wbr.recorded_by
LEFT JOIN trips t ON t.id = wbr.trip_id
WHERE wbr.method          = 'MANUAL_APPROVED'
  AND wbr.approval_status = 'PENDING'
  AND v.current_depot_id IN (
        SELECT id FROM vehicle_depots WHERE primary_facility_id = $1
      )
ORDER BY wbr.created_at ASC
`

type ListPendingManualApprovalsRow struct {
	ID                 int64              `json:"id"`
	TripID             pgtype.Int8        `json:"trip_id"`
	VehicleID          int64              `json:"vehicle_id"`
	ReadingType        string             `json:"reading_type"`
	WeightKg           pgtype.Numeric     `json:"weight_kg"`
	Method             MeasurementMethodT `json:"method"`
	AmbientTempCelsius pgtype.Numeric     `json:"ambient_temp_celsius"`
	RecordedBy         int64              `json:"recorded_by"`
	ApprovalStatus     ApprovalStatusT    `json:"approval_status"`
	ApprovedBy         pgtype.Int8        `json:"approved_by"`
	ApprovedAt         pgtype.Timestamptz `json:"approved_at"`
	EscalatedAt        pgtype.Timestamptz `json:"escalated_at"`
	EscalatedTo        pgtype.Int8        `json:"escalated_to"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PlateNumber        string             `json:"plate_number"`
	RecordedByName     string             `json:"recorded_by_name"`
	TripID_2           pgtype.Int8        `json:"trip_id_2"`
}

// Facility manager approval queue. Scoped to a specific facility via vehicle's current depot.
func (q *Queries) ListPendingManualApprovals(ctx context.Context, primaryFacilityID int64) ([]ListPendingManualApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingManualApprovals, primaryFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingManualApprovalsRow{}
	for rows.Next() {
		var i ListPendingManualApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VehicleID,
			&i.ReadingType,
			&i.WeightKg,
			&i.Method,
			&i.AmbientTempCelsius,
			&i.RecordedBy,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.Notes,
			&i.CreatedAt,
			&i.PlateNumber,
			&i.RecordedByName,
			&i.TripID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightBridgeReadingsByTrip = `-- name: ListWeightBridgeReadingsByTrip :many
SELECT id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
FROM weight_bridge_readings
WHERE trip_id = $1
ORDER BY created_at
`

func (q *Queries) ListWeightBridgeReadingsByTrip(ctx context.Context, tripID pgtype.Int8) ([]WeightBridgeReading, error) {
	rows, err := q.db.Query(ctx, listWeightBridgeReadingsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeightBridgeReading{}
	for rows.Next() {
		var i WeightBridgeReading
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VehicleID,
			&i.ReadingType,
			&i.WeightKg,
			&i.Method,
			&i.AmbientTempCelsius,
			&i.RecordedBy,
			&i.ApprovalStatus,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.EscalatedAt,
			&i.EscalatedTo,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectWeightBridgeReading = `-- name: RejectWeightBridgeReading :one
UPDATE weight_bridge_readings
SET
    approval_status = 'REJECTED',
    approved_by     = $2,
    approved_at     = NOW(),
    notes           = $3
WHERE id = $1
RETURNING id, trip_id, vehicle_id, reading_type, weight_kg, method, ambient_temp_celsius, recorded_by, approval_status, approved_by, approved_at, escalated_at, escalated_to, notes, created_at
`

type RejectWeightBridgeReadingParams struct {
	ID         int64       `json:"id"`
	ApprovedBy pgtype.Int8 `json:"approved_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) RejectWeightBridgeReading(ctx context.Context, arg RejectWeightBridgeReadingParams) (WeightBridgeReading, error) {
	row := q.db.QueryRow(ctx, rejectWeightBridgeReading, arg.ID, arg.ApprovedBy, arg.Notes)
	var i WeightBridgeReading
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.VehicleID,
		&i.ReadingType,
		&i.WeightKg,
		&i.Method,
		&i.AmbientTempCelsius,
		&i.RecordedBy,
		&i.ApprovalStatus,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.EscalatedAt,
		&i.EscalatedTo,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
